// components-react/src/Essentials/Paginator/Paginator.tsx
import { Fragment, type MouseEvent, type ReactNode, useMemo } from "react";

import {
    type InteractionSizing,
    PAGINATOR_DEFAULTS,
    type PaginatorGapEntry,
    type PaginatorPageEntry,
    type PaginatorPageRenderProps,
    type PaginatorStep,
    type PaginatorStepRenderProps,
    PaginatorStyles,
    PaginatorUtils,
} from "@thewaver/ss-components";

import { InteractionWrapper } from "../../Primitives/InteractionWrapper/InteractionWrapper";
import { PlacementBox } from "../../Primitives/PlacementBox/PlacementBox";
import { PlacementItem } from "../../Primitives/PlacementItem/PlacementItem";
import type { PaginatorItemProps, PaginatorProps } from "./Paginator.types";

const ROW_SIZING: InteractionSizing = "fit-content";
const PLACED_SIZING: InteractionSizing = "fill";

const PaginatorItem = <TExtra extends object>(props: PaginatorItemProps<TExtra>) => {
    const isDisabled = props.flags.isDisabled ?? false;

    const handleClick = (e: MouseEvent<HTMLElement>) => {
        if (isDisabled) {
            e.preventDefault();

            return;
        }

        props.onActivate();
    };

    const commonProps = {
        "className": PaginatorStyles.paginatorItem,
        "id": props.id,
        "aria-label": props.ariaLabel,
        "aria-disabled": isDisabled || undefined,
        "aria-current": props.isCurrent ? ("page" as const) : undefined,
    };

    if (props.href === undefined) {
        return (
            <button type="button" ref={props.ref} {...commonProps} onClick={handleClick}>
                {props.renderContent(props.flags)}
            </button>
        );
    }

    const Link = props.linkComponent ?? "a";

    return (
        <Link ref={props.ref} href={props.href} {...commonProps} onClick={handleClick}>
            {props.renderContent(props.flags)}
        </Link>
    );
};

export const Paginator = (props: PaginatorProps) => {
    const pageCount = PaginatorUtils.computePageCount(props.pageCount);
    const isDisabled = props.isDisabled ?? false;
    const page = props.page;

    const entries = PaginatorUtils.getEntries(page, {
        pageCount,
        siblingCount: props.siblingCount ?? PAGINATOR_DEFAULTS.siblingCount,
        boundaryCount: props.boundaryCount ?? PAGINATOR_DEFAULTS.boundaryCount,
    });

    const { leading, trailing } = PaginatorUtils.splitSteps(props.steps ?? PAGINATOR_DEFAULTS.steps);

    const itemCount = leading.length + entries.length + trailing.length;
    const computeLayout = props.computeLayout;
    const layout = useMemo(() => computeLayout?.({ itemCount }), [computeLayout, itemCount]);

    const goTo = (target: number) => {
        if (target === page) return;

        props.onPageChange?.(target);
    };

    const renderPlaced = (index: number, element: ReactNode) => {
        const placement = layout?.placements[index];

        return placement ? (
            <PlacementItem key={index} placement={placement} stackAt={index + 1}>
                {element}
            </PlacementItem>
        ) : (
            <Fragment key={index}>{element}</Fragment>
        );
    };

    const renderStepControl = (step: PaginatorStep, index: number) => {
        const placement = layout?.placements[index];
        const { targetPage, isDisabled: isStepDisabled } = PaginatorUtils.computeStepState(
            step,
            page,
            pageCount,
            isDisabled,
        );

        return renderPlaced(
            index,
            <InteractionWrapper<PaginatorStepRenderProps>
                sizing={placement === undefined ? ROW_SIZING : PLACED_SIZING}
                isDisabled={isStepDisabled}
                extraFlags={{ step, targetPage, placement }}
                renderControl={(setElementRef, renderProps) => (
                    <PaginatorItem
                        ref={setElementRef}
                        href={isStepDisabled ? undefined : props.computeHref?.(targetPage)}
                        isCurrent={false}
                        ariaLabel={props.computeStepLabel(step, targetPage)}
                        flags={renderProps}
                        linkComponent={props.linkComponent}
                        renderContent={() => props.renderStep(step, renderProps)}
                        onActivate={() => goTo(targetPage)}
                    />
                )}
            />,
        );
    };

    const renderPageControl = (entry: PaginatorPageEntry, index: number) => {
        const placement = layout?.placements[index];
        const isCurrent = entry.page === page;

        return renderPlaced(
            index,
            <InteractionWrapper<PaginatorPageRenderProps>
                sizing={placement === undefined ? ROW_SIZING : PLACED_SIZING}
                isDisabled={isDisabled}
                extraFlags={{ page: entry.page, isCurrent, placement }}
                renderControl={(setElementRef, renderProps) => (
                    <PaginatorItem
                        ref={setElementRef}
                        href={props.computeHref?.(entry.page)}
                        isCurrent={isCurrent}
                        ariaLabel={props.computePageLabel(entry.page, pageCount)}
                        flags={renderProps}
                        linkComponent={props.linkComponent}
                        renderContent={() => props.renderPage(entry, renderProps)}
                        onActivate={() => goTo(entry.page)}
                    />
                )}
            />,
        );
    };

    const renderGapControl = (entry: PaginatorGapEntry, index: number) =>
        renderPlaced(
            index,
            <span className={PaginatorStyles.paginatorGap} aria-hidden="true">
                {props.renderGap(entry, layout?.placements[index])}
            </span>,
        );

    const row = (
        <>
            {leading.map((step, index) => renderStepControl(step, index))}

            {entries.map((entry, index) =>
                entry.kind === "page"
                    ? renderPageControl(entry, leading.length + index)
                    : renderGapControl(entry, leading.length + index),
            )}

            {trailing.map((step, index) => renderStepControl(step, leading.length + entries.length + index))}
        </>
    );

    return (
        <nav
            className={PaginatorStyles.paginatorRoot}
            style={{ gap: `${props.gap ?? PAGINATOR_DEFAULTS.gap}px` }}
            aria-label={props.ariaLabel}
        >
            {layout ? (
                <PlacementBox layout={layout} computeEffect={props.computeEffect}>
                    {row}
                </PlacementBox>
            ) : (
                row
            )}
        </nav>
    );
};

// components-svelte/src/Essentials/Paginator/Paginator.svelte
<script lang="ts">
    import type { Snippet } from "svelte";

    import {
        type InteractionFlags,
        type InteractionSizing,
        PAGINATOR_DEFAULTS,
        type PaginatorGapEntry,
        type PaginatorPageEntry,
        type PaginatorPageRenderProps,
        type PaginatorStep,
        type PaginatorStepRenderProps,
        PaginatorUtils,
        PaginatorStyles as styles,
    } from "@thewaver/ss-components";

    import InteractionWrapper from "../../Primitives/InteractionWrapper/InteractionWrapper.svelte";
    import PlacementBox from "../../Primitives/PlacementBox/PlacementBox.svelte";
    import PlacementItem from "../../Primitives/PlacementItem/PlacementItem.svelte";
    import type { PaginatorProps } from "./Paginator.types.js";
    import PaginatorItem from "./PaginatorItem.svelte";

    const ROW_SIZING: InteractionSizing = "fit-content";
    const PLACED_SIZING: InteractionSizing = "fill";

    let props: PaginatorProps = $props();

    const pageCount = $derived(PaginatorUtils.computePageCount(props.pageCount));
    const isDisabled = $derived(props.isDisabled ?? false);
    const page = $derived(props.page);

    const entries = $derived(
        PaginatorUtils.getEntries(page, {
            pageCount,
            siblingCount: props.siblingCount ?? PAGINATOR_DEFAULTS.siblingCount,
            boundaryCount: props.boundaryCount ?? PAGINATOR_DEFAULTS.boundaryCount,
        }),
    );

    const steps = $derived(PaginatorUtils.splitSteps(props.steps ?? PAGINATOR_DEFAULTS.steps));

    const itemCount = $derived(steps.leading.length + entries.length + steps.trailing.length);
    const layout = $derived(props.computeLayout?.({ itemCount }));

    const goTo = (target: number) => {
        if (target === page) return;

        props.onPageChange?.(target);
    };
</script>

{#snippet placed(index: number, body: Snippet)}
    {@const placement = layout?.placements[index]}
    {#if placement}
        <PlacementItem {placement} stackAt={index + 1}>
            {@render body()}
        </PlacementItem>
    {:else}
        {@render body()}
    {/if}
{/snippet}

{#snippet stepControl(step: PaginatorStep, index: number)}
    {@const placement = layout?.placements[index]}
    {@const stepState = PaginatorUtils.computeStepState(step, page, pageCount, isDisabled)}
    {#snippet body()}
        <InteractionWrapper
            sizing={placement === undefined ? ROW_SIZING : PLACED_SIZING}
            isDisabled={stepState.isDisabled}
            extraFlags={{ step, targetPage: stepState.targetPage, placement }}
        >
            {#snippet renderControl(attachElement, renderProps)}
                {#snippet stepContent(itemFlags: InteractionFlags<PaginatorStepRenderProps>)}
                    {@render props.renderStep(step, itemFlags)}
                {/snippet}

                <PaginatorItem
                    {attachElement}
                    href={stepState.isDisabled ? undefined : props.computeHref?.(stepState.targetPage)}
                    isCurrent={false}
                    ariaLabel={props.computeStepLabel(step, stepState.targetPage)}
                    flags={renderProps}
                    linkComponent={props.linkComponent}
                    renderContent={stepContent}
                    onActivate={() => goTo(stepState.targetPage)}
                />
            {/snippet}
        </InteractionWrapper>
    {/snippet}

    {@render placed(index, body)}
{/snippet}

{#snippet pageControl(entry: PaginatorPageEntry, index: number)}
    {@const placement = layout?.placements[index]}
    {@const isCurrent = entry.page === page}
    {#snippet body()}
        <InteractionWrapper
            sizing={placement === undefined ? ROW_SIZING : PLACED_SIZING}
            {isDisabled}
            extraFlags={{ page: entry.page, isCurrent, placement }}
        >
            {#snippet renderControl(attachElement, renderProps)}
                {#snippet pageContent(itemFlags: InteractionFlags<PaginatorPageRenderProps>)}
                    {@render props.renderPage(entry, itemFlags)}
                {/snippet}

                <PaginatorItem
                    {attachElement}
                    href={props.computeHref?.(entry.page)}
                    {isCurrent}
                    ariaLabel={props.computePageLabel(entry.page, pageCount)}
                    flags={renderProps}
                    linkComponent={props.linkComponent}
                    renderContent={pageContent}
                    onActivate={() => goTo(entry.page)}
                />
            {/snippet}
        </InteractionWrapper>
    {/snippet}

    {@render placed(index, body)}
{/snippet}

{#snippet gapControl(entry: PaginatorGapEntry, index: number)}
    {#snippet body()}
        <span class={styles.paginatorGap} aria-hidden="true">
            {@render props.renderGap(entry, layout?.placements[index])}
        </span>
    {/snippet}

    {@render placed(index, body)}
{/snippet}

{#snippet row()}
    {#each steps.leading as step, index (index)}
        {@render stepControl(step, index)}
    {/each}

    {#each entries as entry, index (index)}
        {#if entry.kind === "page"}
            {@render pageControl(entry, steps.leading.length + index)}
        {:else}
            {@render gapControl(entry, steps.leading.length + index)}
        {/if}
    {/each}

    {#each steps.trailing as step, index (index)}
        {@render stepControl(step, steps.leading.length + entries.length + index)}
    {/each}
{/snippet}

<nav class={styles.paginatorRoot} style:gap={`${props.gap ?? PAGINATOR_DEFAULTS.gap}px`} aria-label={props.ariaLabel}>
    {#if layout}
        <PlacementBox {layout} computeEffect={props.computeEffect}>
            {@render row()}
        </PlacementBox>
    {:else}
        {@render row()}
    {/if}
</nav>
