// playground-react/src/App/Pages/SplitPanePage/Examples/Bounded.tsx
import { SplitPane } from "@thewaver/ss-components-react";
import { BOUNDED } from "@thewaver/ss-playground/App/Pages/SplitPanePage/SplitPanePage.const";

import {
    PageSplitPaneBox,
    PageSplitPaneFrame,
    PageSplitPaneGutter,
} from "../../../StyledComponents/SplitPaneContent/SplitPaneContent";
import type { SplitPaneExampleProps } from "../SplitPanePage.types";

type Props = SplitPaneExampleProps;

export const BoundedExample = (props: Props) => {
    return (
        <PageSplitPaneFrame>
            <SplitPane
                panes={BOUNDED}
                ratios={props.ratios}
                gutterSize={props.gutterSize}
                isDisabled={props.isDisabled}
                ariaLabel={"Bounded panes"}
                renderPane={(_pane, index) => (
                    <PageSplitPaneBox>{index === 0 ? "Sidebar 120–220px" : "Content min 160px"}</PageSplitPaneBox>
                )}
                renderGutter={(flags) => <PageSplitPaneGutter flags={flags} orientation={"horizontal"} />}
            />
        </PageSplitPaneFrame>
    );
};

// playground-vue/src/App/Pages/SplitPanePage/Examples/Bounded.vue
<script setup lang="ts">
import { useModel } from "vue";

import { SplitPane } from "@thewaver/ss-components-vue";
import { BOUNDED } from "@thewaver/ss-playground/App/Pages/SplitPanePage/SplitPanePage.const";

import PageSplitPaneBox from "../../../StyledComponents/SplitPaneContent/PageSplitPaneBox.vue";
import PageSplitPaneFrame from "../../../StyledComponents/SplitPaneContent/PageSplitPaneFrame.vue";
import PageSplitPaneGutter from "../../../StyledComponents/SplitPaneContent/PageSplitPaneGutter.vue";
import type { SplitPaneExampleProps } from "../SplitPanePage.types";

type Props = SplitPaneExampleProps;

const props = defineProps<Props>();

const ratios = useModel(props, "ratios");
</script>

<template>
    <PageSplitPaneFrame>
        <SplitPane
            v-model:ratios="ratios"
            :panes="BOUNDED"
            :gutter-size="gutterSize"
            :is-disabled="isDisabled"
            ariaLabel="Bounded panes"
        >
            <template #renderPane="{ index }">
                <PageSplitPaneBox>{{ index === 0 ? "Sidebar 120–220px" : "Content min 160px" }}</PageSplitPaneBox>
            </template>

            <template #renderGutter="flags">
                <PageSplitPaneGutter :flags="flags" orientation="horizontal" />
            </template>
        </SplitPane>
    </PageSplitPaneFrame>
</template>
