// components-react/src/Primitives/PlacementItem/PlacementItem.tsx
import { type CSSProperties, useLayoutEffect, useRef, useState } from "react";

import { PLACEMENT_ITEM_DEFAULTS, PlacementItemStyles, PlacementItemUtils } from "@thewaver/ss-components";

import { useElement } from "../../Utils/refUtils";
import { usePlacementBoxContext } from "../PlacementBox/PlacementBox.context";
import type { PlacementItemProps } from "./PlacementItem.types";

const NO_TRANSITION_MS = 0;

export const PlacementItem = (props: PlacementItemProps) => {
    const context = usePlacementBoxContext();

    const itemRef = useRef<HTMLDivElement | null>(null);
    const element = useElement(itemRef);

    const [glideWatcher] = useState(PlacementItemUtils.createGlideWatcher);
    const [isGliding, setIsGliding] = useState(false);
    const [previousPlacement, setPreviousPlacement] = useState(props.placement);

    const placement = props.placement;
    const transitionDelayMs = props.transitionDelayMs ?? PLACEMENT_ITEM_DEFAULTS.transitionDelayMs;

    if (placement !== previousPlacement) {
        setPreviousPlacement(placement);
        setIsGliding(context.getTransitionDurationMs() > NO_TRANSITION_MS);
    }

    useLayoutEffect(() => {
        if (!element || !isGliding) return;

        glideWatcher.watch(element, () => setIsGliding(false));
    }, [element, isGliding, placement, glideWatcher]);

    const effect = PlacementItemUtils.computeEffectStyle(placement, context);

    const transition = isGliding
        ? PlacementItemUtils.toTransition(context.getTransitionDurationMs(), transitionDelayMs)
        : undefined;

    const style: CSSProperties = PlacementItemUtils.computeStyleValues(placement, props.stackAt, effect, transition);

    return (
        <div ref={itemRef} className={PlacementItemStyles.placementItem} style={style} role="presentation">
            {props.children}
        </div>
    );
};

// components-solid/src/Primitives/PlacementItem/PlacementItem.tsx
import { createComputed, createEffect, createMemo, createSignal, on } from "solid-js";

import { PLACEMENT_ITEM_DEFAULTS, PlacementItemUtils, PlacementItemStyles as styles } from "@thewaver/ss-components";

import { access } from "../../Utils/propUtils";
import { usePlacementBoxContext } from "../PlacementBox/PlacementBox.context";
import type { PlacementItemProps } from "./PlacementItemSolid.types";

const NO_TRANSITION_MS = 0;

const toBoxStyle = (values: ReturnType<typeof PlacementItemUtils.computeStyleValues>) => ({
    "left": values.left,
    "top": values.top,
    "width": values.width,
    "height": values.height,
    "rotate": values.rotate,
    "transform": values.transform,
    "filter": values.filter,
    "z-index": values.zIndex,
    "clip-path": values.clipPath,
    "transition": values.transition,
});

export const PlacementItem = (props: PlacementItemProps) => {
    const context = usePlacementBoxContext();

    const [getItemRef, setItemRef] = createSignal<HTMLElement>();
    const [getIsGliding, setIsGliding] = createSignal(false);

    const glideWatcher = PlacementItemUtils.createGlideWatcher();

    const getTransitionDelayMs = createMemo(
        () => access(props.transitionDelayMs) ?? PLACEMENT_ITEM_DEFAULTS.transitionDelayMs,
    );

    createComputed(
        on(
            () => access(props.placement),
            () => setIsGliding(context.getTransitionDurationMs() > NO_TRANSITION_MS),
            { defer: true },
        ),
    );

    createEffect(() => {
        const element = getItemRef();

        if (!element || !getIsGliding()) return;

        access(props.placement);

        glideWatcher.watch(element, () => setIsGliding(false));
    });

    const getEffect = createMemo(() => PlacementItemUtils.computeEffectStyle(access(props.placement), context));

    const getTransition = createMemo(() =>
        getIsGliding()
            ? PlacementItemUtils.toTransition(context.getTransitionDurationMs(), getTransitionDelayMs())
            : undefined,
    );

    const getStyle = createMemo(() =>
        toBoxStyle(
            PlacementItemUtils.computeStyleValues(
                access(props.placement),
                access(props.stackAt),
                getEffect(),
                getTransition(),
            ),
        ),
    );

    return (
        <div ref={setItemRef} class={styles.placementItem} style={getStyle()} role="presentation">
            {props.children}
        </div>
    );
};
