// playground-solid/src/App/Pages/PaintedTextPage/Examples/CustomInput.tsx
import { createUniqueId } from "solid-js";

import { PaintedText, access } from "@thewaver/ss-components-solid";
import type { AccessorProps } from "@thewaver/ss-components-solid";
import * as styles from "@thewaver/ss-playground/App/Pages/PaintedTextPage/PaintedTextPage.css";

import { computeSampleDefs } from "../PaintedTextPage.const";
import type { PaintedTextExampleProps } from "../PaintedTextPage.types";

type Props = PaintedTextExampleProps &
    AccessorProps<{
        text: string;
    }>;

export const CustomInputExample = (props: Props) => {
    const id = createUniqueId();

    return (
        <div class={styles.paragraph}>
            <PaintedText
                computeFillDefs={(getSize, getRef) => computeSampleDefs(props, "fill", id, getSize, getRef)}
                computeStrokeDefs={(getSize, getRef) => computeSampleDefs(props, "stroke", id, getSize, getRef)}
                strokeWidth={props.strokeWidth}
                strokeAlignment={props.strokeAlignment}
            >
                {access(props.text)}
            </PaintedText>
        </div>
    );
};

// playground-react/src/App/Pages/PaintedTextPage/Examples/CustomInput.tsx
import { useId } from "react";

import { PaintedText } from "@thewaver/ss-components-react";
import * as styles from "@thewaver/ss-playground/App/Pages/PaintedTextPage/PaintedTextPage.css";

import { computeSampleDefs } from "../PaintedTextPage.const";
import type { PaintedTextExampleProps } from "../PaintedTextPage.types";

type Props = PaintedTextExampleProps & {
    text: string;
};

export const CustomInputExample = (props: Props) => {
    const id = useId();

    return (
        <div className={styles.paragraph}>
            <PaintedText
                computeFillDefs={(size, element) => computeSampleDefs(props, "fill", id, size, element)}
                computeStrokeDefs={(size, element) => computeSampleDefs(props, "stroke", id, size, element)}
                strokeWidth={props.strokeWidth}
                strokeAlignment={props.strokeAlignment}
            >
                {props.text}
            </PaintedText>
        </div>
    );
};
