// playground-vue/src/App/Pages/PaintedTextPage/Examples/Typed.vue
<script setup lang="ts">
import { shallowRef, useId } from "vue";

import { Button, MediaQueryMonitorVueUtils, PaintedText, Typewriter } from "@thewaver/ss-components-vue";
import type { TypewriterController } from "@thewaver/ss-components-vue";
import { MEASURE_BOX_PADDING } from "@thewaver/ss-playground/App/PageComponents/MeasureBox/MeasureBox.css";
import * as styles from "@thewaver/ss-playground/App/Pages/PaintedTextPage/PaintedTextPage.css";
import { CONTROL_GLYPHS } from "@thewaver/ss-playground/App/StyledComponents/ControlButtonContent/ControlButtonContent.const";
import type { Size2d } from "@thewaver/ss-utils";

import PageMeasureBox from "../../../PageComponents/MeasureBox/MeasureBox.vue";
import PageControlButtonContent from "../../../StyledComponents/ControlButtonContent/ControlButtonContent.vue";
import { computeSampleDefs } from "../PaintedTextPage.const";
import type { PaintedTextBoxedExampleProps } from "../PaintedTextPage.types";

type Props = PaintedTextBoxedExampleProps & {
    computeAnimationName: (character: string, index: number, count: number) => string;
};

const props = defineProps<Props>();

const id = useId();

const controller = shallowRef<TypewriterController>();

const isBlinkStopped = shallowRef(false);

const prefersReducedMotion = MediaQueryMonitorVueUtils.useReducedMotion();

const setController = (next: TypewriterController) => {
    controller.value = next;
};

const toggleBlink = () => {
    isBlinkStopped.value = !isBlinkStopped.value;
};

const restart = () => {
    controller.value?.restartAnimation();
};

const computeHeadingFillDefs = (size: Size2d, element: HTMLElement | undefined) =>
    computeSampleDefs(props, "fill", id, size, element);

const computeHeadingStrokeDefs = (size: Size2d, element: HTMLElement | undefined) =>
    computeSampleDefs(props, "stroke", id, size, element);

const computeBodyFillDefs = (size: Size2d, element: HTMLElement | undefined) =>
    computeSampleDefs(props, "fill", `${id}-body`, size, element);

const computeBodyStrokeDefs = (size: Size2d, element: HTMLElement | undefined) =>
    computeSampleDefs(props, "stroke", `${id}-body`, size, element);
</script>

<template>
    <div :class="styles.stack">
        <PageMeasureBox :width="width" :padding="MEASURE_BOX_PADDING">
            <div :class="styles.fill">
                <Typewriter
                    :compute-animation-name="computeAnimationName"
                    :animation-delay-ms="40"
                    :animation-duration-ms="400"
                    @mount="setController"
                >
                    <template #default>
                        <div :class="styles.typedHeading">
                            <PaintedText
                                :compute-fill-defs="computeHeadingFillDefs"
                                :compute-stroke-defs="computeHeadingStrokeDefs"
                                :stroke-width="strokeWidth"
                                :stroke-alignment="strokeAlignment"
                            >
                                Typed and painted
                            </PaintedText>
                        </div>

                        <div :class="styles.paragraph">
                            <PaintedText
                                :compute-fill-defs="computeBodyFillDefs"
                                :compute-stroke-defs="computeBodyStrokeDefs"
                                :stroke-width="strokeWidth"
                                :stroke-alignment="strokeAlignment"
                            >
                                The heading types first, then this line carries on from where it ended.
                            </PaintedText>
                        </div>
                    </template>

                    <template #renderCaret>
                        <span
                            :class="[styles.caret, !isBlinkStopped && !prefersReducedMotion && styles.caretBlinking]"
                            aria-hidden="true"
                        />
                    </template>
                </Typewriter>
            </div>
        </PageMeasureBox>

        <div :class="styles.buttonRow">
            <Button id="typeAgain" ariaLabel="Type it again" @click="restart">
                <template #renderContent="flags">
                    <PageControlButtonContent :flags="flags" :glyph="CONTROL_GLYPHS.replay" />
                </template>
            </Button>

            <Button id="toggleBlink" @click="toggleBlink">
                <template #renderContent="flags">
                    <PageControlButtonContent :flags="flags">
                        {{ isBlinkStopped ? "Start blinking" : "Stop blinking" }}
                    </PageControlButtonContent>
                </template>
            </Button>
        </div>
    </div>
</template>

// playground-react/src/App/Pages/PaintedTextPage/Examples/Typed.tsx
import { useId, useState } from "react";

import { Button, MediaQueryMonitorReactUtils, PaintedText, Typewriter } from "@thewaver/ss-components-react";
import type { TypewriterController } from "@thewaver/ss-components-react";
import { MEASURE_BOX_PADDING } from "@thewaver/ss-playground/App/PageComponents/MeasureBox/MeasureBox.css";
import * as styles from "@thewaver/ss-playground/App/Pages/PaintedTextPage/PaintedTextPage.css";
import { CONTROL_GLYPHS } from "@thewaver/ss-playground/App/StyledComponents/ControlButtonContent/ControlButtonContent.const";

import { PageMeasureBox } from "../../../PageComponents/MeasureBox/MeasureBox";
import { PageControlButtonContent } from "../../../StyledComponents/ControlButtonContent/ControlButtonContent";
import { computeSampleDefs } from "../PaintedTextPage.const";
import type { PaintedTextBoxedExampleProps } from "../PaintedTextPage.types";

type Props = PaintedTextBoxedExampleProps & {
    computeAnimationName: (character: string, index: number, count: number) => string;
};

export const TypedExample = (props: Props) => {
    const id = useId();

    const [controller, setController] = useState<TypewriterController>();

    const [isBlinkStopped, setIsBlinkStopped] = useState(false);

    const prefersReducedMotion = MediaQueryMonitorReactUtils.useReducedMotion();

    return (
        <div className={styles.stack}>
            <PageMeasureBox width={props.width} padding={MEASURE_BOX_PADDING}>
                <div className={styles.fill}>
                    <Typewriter
                        computeAnimationName={props.computeAnimationName}
                        animationDelayMs={40}
                        animationDurationMs={400}
                        renderCaret={() => (
                            <span
                                className={[
                                    styles.caret,
                                    !isBlinkStopped && !prefersReducedMotion && styles.caretBlinking,
                                ]
                                    .filter(Boolean)
                                    .join(" ")}
                                aria-hidden="true"
                            />
                        )}
                        onMount={setController}
                    >
                        <div className={styles.typedHeading}>
                            <PaintedText
                                computeFillDefs={(size, element) => computeSampleDefs(props, "fill", id, size, element)}
                                computeStrokeDefs={(size, element) =>
                                    computeSampleDefs(props, "stroke", id, size, element)
                                }
                                strokeWidth={props.strokeWidth}
                                strokeAlignment={props.strokeAlignment}
                            >
                                Typed and painted
                            </PaintedText>
                        </div>

                        <div className={styles.paragraph}>
                            <PaintedText
                                computeFillDefs={(size, element) =>
                                    computeSampleDefs(props, "fill", `${id}-body`, size, element)
                                }
                                computeStrokeDefs={(size, element) =>
                                    computeSampleDefs(props, "stroke", `${id}-body`, size, element)
                                }
                                strokeWidth={props.strokeWidth}
                                strokeAlignment={props.strokeAlignment}
                            >
                                The heading types first, then this line carries on from where it ended.
                            </PaintedText>
                        </div>
                    </Typewriter>
                </div>
            </PageMeasureBox>

            <div className={styles.buttonRow}>
                <Button
                    id={"typeAgain"}
                    ariaLabel={"Type it again"}
                    renderContent={(flags) => <PageControlButtonContent flags={flags} glyph={CONTROL_GLYPHS.replay} />}
                    onClick={() => {
                        controller?.restartAnimation();
                    }}
                />

                <Button
                    id={"toggleBlink"}
                    renderContent={(flags) => (
                        <PageControlButtonContent flags={flags}>
                            {isBlinkStopped ? "Start blinking" : "Stop blinking"}
                        </PageControlButtonContent>
                    )}
                    onClick={() => {
                        setIsBlinkStopped((isStopped) => !isStopped);
                    }}
                />
            </div>
        </div>
    );
};
