// playground-svelte/src/App/Pages/TreePage/Examples/LinkComponent.svelte
<script lang="ts">
    import { Tree } from "@thewaver/ss-components-svelte";

    import { renderPageHighlightFloater } from "../../../StyledComponents/GlideFloater/GlideFloater.const.svelte";
    import PageTreeNodeContent from "../../../StyledComponents/TreeNodeContent/PageTreeNodeContent.svelte";
    import { DOCS } from "../TreePage.const.svelte";
    import type { TreeExampleProps } from "../TreePage.types";
    import PageTreeLink from "./PageTreeLink.svelte";

    type Props = TreeExampleProps;

    let { value = $bindable(), expanded = $bindable() }: Props = $props();
</script>

<Tree
    renderHighlightFloater={renderPageHighlightFloater}
    nodes={DOCS}
    bind:value
    bind:expanded
    ariaLabel={"Routed documentation"}
    linkComponent={PageTreeLink}
>
    {#snippet renderNode(node, renderProps)}
        <PageTreeNodeContent isGliding {renderProps}>{node.value}</PageTreeNodeContent>
    {/snippet}
</Tree>

// playground-solid/src/App/Pages/TreePage/Examples/LinkComponent.tsx
import { Tree } from "@thewaver/ss-components-solid";
import type { TreeLinkProps } from "@thewaver/ss-components-solid";

import { renderPageHighlightFloater } from "../../../StyledComponents/GlideFloater/GlideFloater";
import { PageTreeNodeContent } from "../../../StyledComponents/TreeNodeContent/TreeNodeContent";
import { DOCS } from "../TreePage.const";
import type { TreeExampleProps } from "../TreePage.types";

const PageTreeLink = (props: TreeLinkProps) => <a {...props} data-link-component />;

type Props = TreeExampleProps;

export const LinkComponentExample = (props: Props) => (
    <Tree
        renderHighlightFloater={renderPageHighlightFloater}
        nodes={() => DOCS}
        value={props.value}
        expanded={props.expanded}
        ariaLabel={"Routed documentation"}
        linkComponent={PageTreeLink}
        renderNode={(getNode, getRenderProps) => (
            <PageTreeNodeContent isGliding renderProps={getRenderProps}>
                {getNode().value}
            </PageTreeNodeContent>
        )}
    />
);
