// components/src/Primitives/Spotlight/Spotlight.tsx
import { Show, createEffect, createMemo, createSignal, onCleanup, onMount } from "solid-js";
import type { JSX } from "solid-js";
import { Portal } from "solid-js/web";

import { Rect } from "@thewaver/ss-utils";

import { AnchorUtils } from "../../Abstracts/Anchor/Anchor.utils";
import { CutoutUtils } from "../../Abstracts/Cutout/Cutout.utils";
import { ElementFaderUtils } from "../../Abstracts/ElementFader/ElementFader.utils";
import { ElementObserverUtils } from "../../Abstracts/ElementObserver/ElementObserver.utils";
import { ElevationUtils } from "../../Abstracts/Elevation/Elevation.utils";
import { FocusManagerUtils } from "../../Abstracts/FocusManager/FocusManager.utils";
import { LiveAnnouncerUtils } from "../../Abstracts/LiveAnnouncer/LiveAnnouncer.utils";
import { useViewportContext } from "../../Abstracts/Viewport/Viewport.context";
import { access } from "../../Utils/propUtils";
import { SPOTLIGHT_DEFAULTS } from "./Spotlight.const";
import type { SpotlightProps } from "./Spotlight.types";
import { SpotlightUtils } from "./Spotlight.utils";

import * as styles from "./Spotlight.css";

const MODIFIER_KEYS = new Set(["Shift", "Control", "Alt", "Meta", "CapsLock", "NumLock", "ScrollLock", "AltGraph"]);

export const Spotlight = (props: SpotlightProps) => {
    const viewportContext = useViewportContext();

    const [getElementRect, setElementRect] = createSignal<Rect | undefined>(undefined, {
        equals: Rect.isSame,
    });
    const [getPortalRef, setPortalRef] = createSignal<HTMLElement>();
    const [getPopupRef, setPopupRef] = createSignal<HTMLElement>();

    const getTransitionDurationMs = createMemo(
        () => access(props.transitionDurationMs) ?? SPOTLIGHT_DEFAULTS.transitionDurationMs,
    );

    const getPadding = createMemo(() => access(props.padding) ?? SPOTLIGHT_DEFAULTS.padding);

    const { getIsVisible, getTransitionTarget } = ElementFaderUtils.createFader(() => props.visibilitySignal[0](), {
        getTransitionDurationMs,
        getRef: getPortalRef,
        onShow: props.onShow,
        onHide: props.onHide,
    });

    const getHasPopup = createMemo(() => access(props.mode) === "guide" && props.renderPopup !== undefined);

    ElementObserverUtils.createViewportRectObserver(() => access(props.elementRef), getIsVisible, {
        setElementRect,
        getPadding,
    });

    ElevationUtils.createElevation(
        () => access(props.elementRef),
        getIsVisible,
        () => styles.SPOTLIGHT_Z_INDEX,
    );

    createEffect(() => {
        const element = access(props.elementRef);

        if (!getIsVisible() || !element) return;

        element.scrollIntoView({ block: "nearest", inline: "nearest" });
    });

    const { getPlacement, getPosition, setContentRef } = AnchorUtils.createPortalPosition(
        () => access(props.elementRef),
        () => getIsVisible() && getHasPopup(),
        {
            getPlacement: () => access(props.popupPlacement) ?? SPOTLIGHT_DEFAULTS.popupPlacement,
            getOffset: () => access(props.popupOffset) ?? SPOTLIGHT_DEFAULTS.popupOffset,
            getAnchorRect: getElementRect,
        },
    );

    const getMaskStyle = createMemo<JSX.CSSProperties>(() => {
        const rect = getElementRect();

        return rect ? CutoutUtils.getMaskStyle([rect]) : {};
    });

    const getClipPath = createMemo(() => {
        const rect = getElementRect();

        return rect ? SpotlightUtils.getHoleClipPath(rect) : undefined;
    });

    const dismiss = () => {
        props.visibilitySignal[1](false);
    };

    const handleKeyDown = (e: KeyboardEvent) => {
        if (!getIsVisible()) return;

        if (e.key === "Escape") {
            dismiss();

            return;
        }

        if (access(props.mode) !== "hint") return;
        if (MODIFIER_KEYS.has(e.key)) return;

        dismiss();
    };

    createEffect(() => {
        onCleanup(() => {
            document.removeEventListener("keydown", handleKeyDown);
        });

        if (!getIsVisible()) return;

        document.addEventListener("keydown", handleKeyDown);
    });

    createEffect(() => {
        const element = access(props.elementRef);

        if (!getIsVisible() || access(props.mode) !== "prompt" || !element) return;

        const onFocusIn = (e: FocusEvent) => {
            const target = e.target as Node | null;

            if (target && (element === target || element.contains(target))) return;

            element.focus({ preventScroll: true });
        };

        element.focus({ preventScroll: true });
        document.addEventListener("focusin", onFocusIn);

        onCleanup(() => {
            document.removeEventListener("focusin", onFocusIn);
        });
    });

    createEffect(() => {
        const portal = getPortalRef();

        if (!getIsVisible() || access(props.mode) !== "guide" || !portal) return;

        onCleanup(FocusManagerUtils.sealAround(portal));
    });

    onMount(() => {
        if (props.announcement === undefined) return;

        LiveAnnouncerUtils.reserve("polite");
    });

    createEffect<string | undefined>((previous) => {
        const announcement = access(props.announcement);

        if (!getIsVisible()) return previous;
        if (previous !== undefined && announcement !== undefined && announcement !== previous) {
            LiveAnnouncerUtils.announce(announcement);
        }

        return announcement;
    });

    const [getHasPlaced, setHasPlaced] = createSignal(false);

    createEffect(() => {
        if (!getIsVisible() || !getHasPopup()) {
            setHasPlaced(false);

            return;
        }

        if (getPosition()) setHasPlaced(true);
    });

    FocusManagerUtils.autoFocus(getPopupRef, getHasPlaced);

    return (
        <Show when={getIsVisible() && getElementRect()}>
            <Portal ref={setPortalRef} mount={viewportContext.getPortalRef()}>
                <div class={styles.spotlightOverlay}>
                    {props.renderOverlay(getTransitionTarget, getTransitionDurationMs, getMaskStyle)}
                </div>

                <div
                    class={styles.spotlightBlocker}
                    style={{ "clip-path": getClipPath() }}
                    onClick={() => access(props.mode) === "hint" && dismiss()}
                />

                <Show when={props.renderHighlight && getElementRect()}>
                    {(getRect) => (
                        <div
                            class={styles.spotlightDecoration}
                            style={{
                                top: `${getRect().y}px`,
                                left: `${getRect().x}px`,
                                width: `${getRect().width}px`,
                                height: `${getRect().height}px`,
                            }}
                        >
                            {props.renderHighlight?.(getTransitionTarget, getTransitionDurationMs)}
                        </div>
                    )}
                </Show>

                <Show when={getHasPopup()}>
                    <div
                        ref={(element) => {
                            setPopupRef(element);
                            setContentRef(element);
                        }}
                        class={styles.spotlightPopup}
                        style={{
                            visibility: getPosition() ? "visible" : "hidden",
                            transform: `translate(${getPosition()?.x ?? 0}px, ${getPosition()?.y ?? 0}px)`,
                        }}
                        tabIndex={-1}
                        role="dialog"
                        aria-modal="true"
                        aria-label={access(props.ariaLabel)}
                        onKeyDown={(e) => FocusManagerUtils.focusTrapKeyDown(e, getPopupRef())}
                    >
                        {props.renderPopup?.(getTransitionTarget, getTransitionDurationMs, getPlacement)}
                    </div>
                </Show>
            </Portal>
        </Show>
    );
};

// components-svelte/src/Primitives/Spotlight/Spotlight.svelte
<script lang="ts">
    import { untrack } from "svelte";
    import { on } from "svelte/events";

    import {
        CutoutUtils,
        FocusManagerUtils,
        LiveAnnouncerUtils,
        SPOTLIGHT_DEFAULTS,
        SpotlightUtils,
        SpotlightStyles as styles,
    } from "@thewaver/ss-components";
    import { Rect } from "@thewaver/ss-utils";

    import { AnchorSvelteUtils } from "../../Abstracts/Anchor/AnchorSvelte.utils.svelte.js";
    import { ElementFaderSvelteUtils } from "../../Abstracts/ElementFader/ElementFaderSvelte.utils.svelte.js";
    import { ElementObserverSvelteUtils } from "../../Abstracts/ElementObserver/ElementObserverSvelte.utils.svelte.js";
    import { ElevationSvelteUtils } from "../../Abstracts/Elevation/ElevationSvelte.utils.svelte.js";
    import { FocusManagerSvelteUtils } from "../../Abstracts/FocusManager/FocusManagerSvelte.utils.svelte.js";
    import { getViewportContext } from "../../Abstracts/Viewport/Viewport.context.js";
    import { attachPortal } from "../../Utils/portalUtils.js";
    import { toStyle } from "../../Utils/styleUtils.js";
    import type { SpotlightProps } from "./Spotlight.types.js";

    let { visibility = $bindable(), ...props }: SpotlightProps = $props();

    const viewportContext = getViewportContext();

    let rect = $state.raw<Rect>();
    let portal = $state<HTMLDivElement>();
    let popup = $state<HTMLDivElement>();

    const transitionDurationMs = $derived(props.transitionDurationMs ?? SPOTLIGHT_DEFAULTS.transitionDurationMs);
    const padding = $derived(props.padding ?? SPOTLIGHT_DEFAULTS.padding);
    const hasPopup = $derived(props.mode === "guide" && props.renderPopup !== undefined);

    const fader = ElementFaderSvelteUtils.createFader(() => visibility, {
        getTransitionDurationMs: () => transitionDurationMs,
        getRef: () => portal ?? undefined,
        onShow: () => props.onShow?.(),
        onHide: () => props.onHide?.(),
    });

    ElementObserverSvelteUtils.createViewportRectObserver(() => props.elementRef, fader.getIsVisible, {
        setElementRect: (next) => {
            if (!rect || !Rect.isSame(rect, next)) rect = next;
        },
        getPadding: () => padding,
    });

    ElevationSvelteUtils.createElevation(
        () => props.elementRef,
        fader.getIsVisible,
        () => styles.SPOTLIGHT_Z_INDEX,
    );

    $effect(() => {
        const element = props.elementRef;

        if (!fader.getIsVisible() || !element) return;

        untrack(() => element.scrollIntoView({ block: "nearest", inline: "nearest" }));
    });

    const position = AnchorSvelteUtils.createPortalPosition(
        () => props.elementRef,
        () => fader.getIsVisible() && hasPopup,
        {
            getPlacement: () => props.popupPlacement ?? SPOTLIGHT_DEFAULTS.popupPlacement,
            getOffset: () => props.popupOffset ?? SPOTLIGHT_DEFAULTS.popupOffset,
            getAnchorRect: () => rect,
        },
    );

    const maskStyle = $derived(rect ? toStyle(CutoutUtils.getMaskStyle([rect])) : "");

    const clipPath = $derived(rect ? SpotlightUtils.getHoleClipPath(rect) : undefined);

    const dismiss = () => {
        visibility = false;
    };

    $effect(() => {
        if (!fader.getIsVisible()) return;

        return untrack(() => SpotlightUtils.observeDismissKeys(() => props.mode, dismiss));
    });

    $effect(() => {
        const element = props.elementRef;

        if (!fader.getIsVisible() || props.mode !== "prompt" || !element) return;

        return untrack(() => SpotlightUtils.holdFocus(element));
    });

    $effect(() => {
        const element = portal;

        if (!fader.getIsVisible() || props.mode !== "guide" || !element) return;

        return untrack(() => FocusManagerUtils.sealAround(element));
    });

    $effect(() => {
        if (props.announcement === undefined) return;

        untrack(() => LiveAnnouncerUtils.reserve("polite"));
    });

    let announced: string | undefined;

    $effect(() => {
        const announcement = props.announcement;

        if (!fader.getIsVisible()) return;

        untrack(() => {
            if (SpotlightUtils.getIsAnnouncementDue(announced, announcement)) {
                LiveAnnouncerUtils.announce(announcement!);
            }
        });

        announced = announcement;
    });

    let hasPlaced = $state(false);

    $effect.pre(() => {
        if (!fader.getIsVisible() || !hasPopup) {
            hasPlaced = false;

            return;
        }

        if (position.getPosition()) hasPlaced = true;
    });

    FocusManagerSvelteUtils.autoFocus(
        () => popup ?? undefined,
        () => hasPlaced,
    );
</script>

{#if fader.getIsVisible() && rect}
    {@const shownRect = rect}
    <div bind:this={portal} {@attach attachPortal(viewportContext.getPortalRef() ?? document.body)}>
        <div class={styles.spotlightOverlay}>
            {@render props.renderOverlay(fader.getTransitionTarget(), transitionDurationMs, maskStyle)}
        </div>

        <div
            {@attach (element) =>
                on(element, "click", () => {
                    if (props.mode === "hint") dismiss();
                })}
            class={styles.spotlightBlocker}
            style:clip-path={clipPath}
        ></div>

        {#if props.renderHighlight}
            <div
                class={styles.spotlightDecoration}
                style:top={`${shownRect.y}px`}
                style:left={`${shownRect.x}px`}
                style:width={`${shownRect.width}px`}
                style:height={`${shownRect.height}px`}
            >
                {@render props.renderHighlight(fader.getTransitionTarget(), transitionDurationMs)}
            </div>
        {/if}

        {#if hasPopup}
            <div
                bind:this={popup}
                {@attach position.attachContent}
                class={styles.spotlightPopup}
                style:visibility={position.getPosition() ? "visible" : "hidden"}
                style:transform={`translate(${position.getPosition()?.x ?? 0}px, ${position.getPosition()?.y ?? 0}px)`}
                tabindex="-1"
                role="dialog"
                aria-modal="true"
                aria-label={props.ariaLabel}
                onkeydown={(e) =>
                    FocusManagerUtils.focusTrapKeyDown(
                        e as Parameters<typeof FocusManagerUtils.focusTrapKeyDown>[0],
                        popup ?? undefined,
                    )}
            >
                {@render props.renderPopup?.(
                    fader.getTransitionTarget(),
                    transitionDurationMs,
                    position.getPlacement(),
                )}
            </div>
        {/if}
    </div>
{/if}
