// playground-svelte/src/App/Pages/TextInputPage/Examples/Editable.svelte
<script lang="ts">
    import { untrack } from "svelte";
    import { on } from "svelte/events";

    import { Button, TextInput } from "@thewaver/ss-components-svelte";
    import {
        FIELD_GAP,
        FIELD_PADDING,
    } from "@thewaver/ss-playground/App/StyledComponents/TextFieldContent/TextFieldContent.css";

    import PageInlineEditContent from "../../../StyledComponents/InlineEditContent/InlineEditContent.svelte";
    import PageTextFieldContent, {
        computePageTextFieldTextStyle,
    } from "../../../StyledComponents/TextFieldContent/TextFieldContent.svelte";
    import type { TextInputEditableExampleProps } from "../TextInputPage.types";

    type Props = TextInputEditableExampleProps;

    let { value = $bindable(), editing = $bindable() }: Props = $props();

    let draft = $state("");

    let button = $state<HTMLElement>();
    let input = $state<HTMLElement>();
    let focusedFor = untrack(() => editing);

    const startEditing = () => {
        draft = value;
        editing = true;
    };

    const finishEditing = (isCommitting: boolean) => {
        if (!editing) return;

        if (isCommitting) value = draft;

        editing = false;
    };

    const handleKeyDown = (e: KeyboardEvent) => {
        if (e.key === "Enter") {
            e.preventDefault();
            finishEditing(true);
        }

        if (e.key === "Escape") {
            e.preventDefault();
            finishEditing(false);
        }
    };

    $effect(() => {
        const target = editing ? input : button;

        if (focusedFor === editing || !target) return;

        focusedFor = editing;

        target.focus();
    });
</script>

{#if !editing}
    <Button bind:ref={button} ariaLabel={`Edit name, ${value}`} onClick={startEditing}>
        {#snippet renderContent(flags)}
            <PageInlineEditContent {flags}>{value}</PageInlineEditContent>
        {/snippet}
    </Button>
{:else}
    <div {@attach (element) => on(element, "keydown", handleKeyDown)} onfocusout={() => finishEditing(true)}>
        <TextInput
            bind:ref={input}
            bind:value={draft}
            padding={FIELD_PADDING}
            gap={FIELD_GAP}
            ariaLabel={"Name"}
            computeTextStyle={computePageTextFieldTextStyle}
        >
            {#snippet renderContent(flags)}
                <PageTextFieldContent {flags} />
            {/snippet}
        </TextInput>
    </div>
{/if}

// playground-vue/src/App/Pages/TextInputPage/Examples/Editable.vue
<script setup lang="ts">
import { type ComponentPublicInstance, shallowRef, useModel, watch } from "vue";

import { Button, TextInput, toElement } from "@thewaver/ss-components-vue";
import {
    FIELD_GAP,
    FIELD_PADDING,
} from "@thewaver/ss-playground/App/StyledComponents/TextFieldContent/TextFieldContent.css";

import PageInlineEditContent from "../../../StyledComponents/InlineEditContent/InlineEditContent.vue";
import PageTextFieldContent, {
    computePageTextFieldTextStyle,
} from "../../../StyledComponents/TextFieldContent/TextFieldContent.vue";
import type { TextInputEditableExampleProps } from "../TextInputPage.types";

type Props = TextInputEditableExampleProps;

const props = defineProps<Props>();

const value = useModel(props, "value");
const editing = useModel(props, "editing");

const draft = shallowRef("");
const buttonRef = shallowRef<HTMLElement>();
const inputRef = shallowRef<HTMLElement>();

let isEditingNow = editing.value;

const setButtonRef = (target: Element | ComponentPublicInstance | null) => {
    buttonRef.value = toElement(target);
};

const setInputRef = (target: Element | ComponentPublicInstance | null) => {
    inputRef.value = toElement(target);
};

const startEditing = () => {
    draft.value = value.value;
    isEditingNow = true;
    editing.value = true;
};

const finishEditing = (isCommitting: boolean) => {
    if (!isEditingNow) return;

    isEditingNow = false;

    if (isCommitting) value.value = draft.value;

    editing.value = false;
};

const handleKeyDown = (e: KeyboardEvent) => {
    if (e.key === "Enter") {
        e.preventDefault();
        finishEditing(true);
    }

    if (e.key === "Escape") {
        e.preventDefault();
        finishEditing(false);
    }
};

watch(
    editing,
    (isEditing) => {
        isEditingNow = isEditing;

        (isEditing ? inputRef : buttonRef).value?.focus();
    },
    { flush: "post" },
);
</script>

<template>
    <Button v-if="!editing" :ref="setButtonRef" :ariaLabel="`Edit name, ${value}`" @click="startEditing">
        <template #renderContent="flags">
            <PageInlineEditContent :flags="flags">{{ value }}</PageInlineEditContent>
        </template>
    </Button>

    <div v-else @keydown="handleKeyDown" @focusout="finishEditing(true)">
        <TextInput
            :ref="setInputRef"
            v-model:value="draft"
            :padding="FIELD_PADDING"
            :gap="FIELD_GAP"
            ariaLabel="Name"
            :compute-text-style="computePageTextFieldTextStyle"
        >
            <template #renderContent="flags">
                <PageTextFieldContent :flags="flags" />
            </template>
        </TextInput>
    </div>
</template>
