// playground/src/App/Pages/CornersPage/Examples/Control.tsx
import { createSignal } from "solid-js";

import { Button, Corners, access } from "@thewaver/ss-components";

import { PageButtonContent } from "../../../StyledComponents/ButtonContent/ButtonContent";
import type { CornersExampleProps } from "../CornersPage.types";

import * as styles from "../CornersPage.css";

type Props = CornersExampleProps;

const TRANSPARENT = "transparent";

export const ControlExample = (props: Props) => {
    const [getIsArmed, setIsArmed] = createSignal(false);

    return (
        <div class={styles.controlRow}>
            <Button
                isPressed={getIsArmed}
                renderContent={(getFlags) => (
                    <PageButtonContent flags={getFlags}>{getIsArmed() ? "Armed" : "Arm"}</PageButtonContent>
                )}
                renderDecoration={(getFlags) => (
                    <Corners
                        color={() => (getFlags().isPressed ? access(props.color) : TRANSPARENT)}
                        cornerLength={props.cornerLength}
                        strokeThickness={props.strokeThickness}
                        transitionDurationMs={props.transitionDurationMs}
                        visibleCorners={props.visibleCorners}
                    />
                )}
                onClick={() => {
                    setIsArmed((previous) => !previous);
                }}
            />
        </div>
    );
};

// playground-react/src/App/Pages/CornersPage/Examples/Control.tsx
import { useState } from "react";

import { Button, Corners } from "@thewaver/ss-components-react";
import * as styles from "@thewaver/ss-playground/App/Pages/CornersPage/CornersPage.css";

import { PageButtonContent } from "../../../StyledComponents/ButtonContent/ButtonContent";
import type { CornersExampleProps } from "../CornersPage.types";

type Props = CornersExampleProps;

const TRANSPARENT = "transparent";

export const ControlExample = (props: Props) => {
    const [isArmed, setIsArmed] = useState(false);

    return (
        <div className={styles.controlRow}>
            <Button
                isPressed={isArmed}
                renderContent={(flags) => (
                    <PageButtonContent flags={flags}>{isArmed ? "Armed" : "Arm"}</PageButtonContent>
                )}
                renderDecoration={(flags) => (
                    <Corners
                        color={flags.isPressed ? props.color : TRANSPARENT}
                        cornerLength={props.cornerLength}
                        strokeThickness={props.strokeThickness}
                        transitionDurationMs={props.transitionDurationMs}
                        visibleCorners={props.visibleCorners}
                    />
                )}
                onClick={() => {
                    setIsArmed((previous) => !previous);
                }}
            />
        </div>
    );
};
