// playground-react/src/App/StyledComponents/MosaicContent/MosaicContent.tsx
import type { PropsWithChildren } from "react";

import * as styles from "@thewaver/ss-playground/App/StyledComponents/MosaicContent/MosaicContent.css";

import { useLayerClass } from "../Layer/Layer.context";
import type { PageMosaicLinkProps, PageMosaicTileProps } from "./MosaicContent.types";

export const PageMosaicTile = (props: PropsWithChildren<PageMosaicTileProps>) => {
    const layerClass = useLayerClass();

    return (
        <div
            className={[styles.mosaicTile, layerClass].join(" ")}
            style={{ width: `${props.width}px`, height: `${props.height}px` }}
        >
            <div className={styles.mosaicTileName}>{props.children}</div>

            <div className={styles.mosaicTileReading}>
                {`reads ${props.state.readingIndex + 1} of ${props.state.itemCount}`}
            </div>
        </div>
    );
};

export const PageMosaicLink = (props: PropsWithChildren<PageMosaicLinkProps>) => {
    const layerClass = useLayerClass();

    return (
        <a className={[styles.mosaicLink, layerClass].join(" ")} href={props.href}>
            {props.children}

            <span className={styles.mosaicCaption}>{props.caption}</span>
        </a>
    );
};

// playground/src/App/StyledComponents/MosaicContent/MosaicContent.tsx
import type { ParentProps } from "solid-js";

import { access } from "@thewaver/ss-components";

import { useLayerClass } from "../Layer/Layer.context";
import type { PageMosaicLinkProps, PageMosaicTileProps } from "./MosaicContent.types";

import * as styles from "./MosaicContent.css";

export const PageMosaicTile = (props: ParentProps<PageMosaicTileProps>) => {
    const getLayerClass = useLayerClass();

    return (
        <div
            class={[styles.mosaicTile, getLayerClass()].join(" ")}
            style={{ width: `${access(props.width)}px`, height: `${access(props.height)}px` }}
        >
            <div class={styles.mosaicTileName}>{props.children}</div>

            <div class={styles.mosaicTileReading}>
                {`reads ${access(props.state).readingIndex + 1} of ${access(props.state).itemCount}`}
            </div>
        </div>
    );
};

export const PageMosaicLink = (props: ParentProps<PageMosaicLinkProps>) => {
    const getLayerClass = useLayerClass();

    return (
        <a class={[styles.mosaicLink, getLayerClass()].join(" ")} href={access(props.href)}>
            {props.children}

            <span class={styles.mosaicCaption}>{access(props.caption)}</span>
        </a>
    );
};
