// playground-react/src/App/Pages/HoverCardPage/Examples/Profile.tsx
import { useId, useState } from "react";

import { Button, HoverCard } from "@thewaver/ss-components-react";
import * as styles from "@thewaver/ss-playground/App/Pages/HoverCardPage/HoverCardPage.css";
import knightProfile from "@thewaver/ss-playground/App/knight_profile.webp";

import { PageButtonContent } from "../../../StyledComponents/ButtonContent/ButtonContent";
import { PageHoverCardContent } from "../../../StyledComponents/HoverCardContent/HoverCardContent";
import type { HoverCardExampleProps } from "../HoverCardPage.types";

type Props = HoverCardExampleProps;

export const ProfileExample = (props: Props) => {
    const nameId = useId();

    const [anchorRef, setAnchorRef] = useState<HTMLElement>();

    const [isFollowing, setIsFollowing] = props.following;

    return (
        <div className={styles.sentence}>
            {"Posted by "}

            <button ref={(element) => setAnchorRef(element ?? undefined)} type={"button"} className={styles.handle}>
                @sir.aldric
            </button>

            {" to the masons' guild, two hours ago."}

            <HoverCard
                anchorRef={anchorRef}
                ariaLabelledBy={nameId}
                visibility={props.visibility}
                offset={props.offset}
                transitionDurationMs={props.transitionDurationMs}
                focusShowDelayMs={props.focusShowDelayMs}
                hoverShowDelayMs={props.hoverShowDelayMs}
                skipDelayWindowMs={props.skipDelayWindowMs}
                renderContent={(visibilityTarget, transitionDurationMs) => (
                    <PageHoverCardContent
                        visibilityTarget={visibilityTarget}
                        transitionDurationMs={transitionDurationMs}
                    >
                        <div className={styles.profileHeader}>
                            <img src={knightProfile} alt={""} className={styles.avatar} />

                            <div>
                                <div id={nameId} className={styles.profileName}>
                                    Sir Aldric of the East Gate
                                </div>

                                <div className={styles.profileHandle}>@sir.aldric</div>
                            </div>
                        </div>

                        <div className={styles.profileBio}>
                            Keeps the east gate and the accounts of the masons who rebuilt it. Writes about lime mortar,
                            horses and the price of oats.
                        </div>

                        <div className={styles.profileActions}>
                            <Button
                                renderContent={(flags) => (
                                    <PageButtonContent flags={flags}>
                                        {isFollowing ? "Unfollow" : "Follow"}
                                    </PageButtonContent>
                                )}
                                onClick={() => {
                                    setIsFollowing(!isFollowing);
                                }}
                            />

                            <a href={"#sir-aldric"}>View profile</a>
                        </div>
                    </PageHoverCardContent>
                )}
            />
        </div>
    );
};

// playground-solid/src/App/Pages/HoverCardPage/Examples/Profile.tsx
import { createSignal, createUniqueId } from "solid-js";

import { Button, HoverCard } from "@thewaver/ss-components-solid";
import * as styles from "@thewaver/ss-playground/App/Pages/HoverCardPage/HoverCardPage.css";
import knightProfile from "@thewaver/ss-playground/App/knight_profile.webp";

import { PageButtonContent } from "../../../StyledComponents/ButtonContent/ButtonContent";
import { PageHoverCardContent } from "../../../StyledComponents/HoverCardContent/HoverCardContent";
import type { HoverCardExampleProps } from "../HoverCardPage.types";

type Props = HoverCardExampleProps;

export const ProfileExample = (props: Props) => {
    const nameId = createUniqueId();

    const [getAnchorRef, setAnchorRef] = createSignal<HTMLElement>();

    const [getIsFollowing, setIsFollowing] = props.following;

    return (
        <div class={styles.sentence}>
            {"Posted by "}

            <button ref={setAnchorRef} type={"button"} class={styles.handle}>
                @sir.aldric
            </button>

            {" to the masons' guild, two hours ago."}

            <HoverCard
                anchorRef={getAnchorRef}
                ariaLabelledBy={() => nameId}
                visibility={props.visibility}
                offset={props.offset}
                transitionDurationMs={props.transitionDurationMs}
                focusShowDelayMs={props.focusShowDelayMs}
                hoverShowDelayMs={props.hoverShowDelayMs}
                skipDelayWindowMs={props.skipDelayWindowMs}
                renderContent={(getVisibilityTarget, getTransitionDurationMs) => (
                    <PageHoverCardContent
                        visibilityTarget={getVisibilityTarget}
                        transitionDurationMs={getTransitionDurationMs}
                    >
                        <div class={styles.profileHeader}>
                            <img src={knightProfile} alt={""} class={styles.avatar} />

                            <div>
                                <div id={nameId} class={styles.profileName}>
                                    Sir Aldric of the East Gate
                                </div>

                                <div class={styles.profileHandle}>@sir.aldric</div>
                            </div>
                        </div>

                        <div class={styles.profileBio}>
                            Keeps the east gate and the accounts of the masons who rebuilt it. Writes about lime mortar,
                            horses and the price of oats.
                        </div>

                        <div class={styles.profileActions}>
                            <Button
                                renderContent={(getFlags) => (
                                    <PageButtonContent flags={getFlags}>
                                        {getIsFollowing() ? "Unfollow" : "Follow"}
                                    </PageButtonContent>
                                )}
                                onClick={() => {
                                    setIsFollowing((isFollowing) => !isFollowing);
                                }}
                            />

                            <a href={"#sir-aldric"}>View profile</a>
                        </div>
                    </PageHoverCardContent>
                )}
            />
        </div>
    );
};
