// playground-svelte/src/App/Pages/TreePage/Examples/Lazy.svelte
<script lang="ts">
    import { Tree } from "@thewaver/ss-components-svelte";
    import type { TreeNode } from "@thewaver/ss-components-svelte";

    import { renderPageHighlightFloater } from "../../../StyledComponents/GlideFloater/GlideFloater.const.svelte";
    import PageTreeNodeContent from "../../../StyledComponents/TreeNodeContent/PageTreeNodeContent.svelte";
    import PageTreeNodePending from "../../../StyledComponents/TreeNodeContent/PageTreeNodePending.svelte";
    import { REMOTE_CHILDREN, REMOTE_LOAD_DELAY_MS, REMOTE_ROOT } from "../TreePage.const.svelte";
    import type { TreeExampleProps } from "../TreePage.types";

    type Props = TreeExampleProps;

    const fillBranch = (nodes: TreeNode<string>[], value: string): TreeNode<string>[] =>
        nodes.map((node) => {
            if (node.value === value)
                return { ...node, children: REMOTE_CHILDREN[value] ?? [], hasMoreChildren: false };

            if (!node.children) return node;

            return { ...node, children: fillBranch(node.children, value) };
        });

    let { value = $bindable(), expanded = $bindable() }: Props = $props();

    let nodes = $state.raw<TreeNode<string>[]>(REMOTE_ROOT);

    const loaded = new Set<string>();

    $effect(() => {
        const timers = expanded
            .filter((value) => !loaded.has(value))
            .map((value) =>
                setTimeout(() => {
                    loaded.add(value);
                    nodes = fillBranch(nodes, value);
                }, REMOTE_LOAD_DELAY_MS),
            );

        return () => timers.forEach((timer) => clearTimeout(timer));
    });
</script>

<Tree
    renderHighlightFloater={renderPageHighlightFloater}
    {nodes}
    bind:value
    bind:expanded
    ariaLabel={"Remote repository"}
>
    {#snippet renderNode(node, renderProps)}
        <PageTreeNodeContent isGliding {renderProps}>{node.value}</PageTreeNodeContent>
    {/snippet}

    {#snippet renderPendingChildren(_node, depth)}
        <PageTreeNodePending {depth}>Fetching…</PageTreeNodePending>
    {/snippet}
</Tree>

// playground-react/src/App/Pages/TreePage/Examples/Lazy.tsx
import { useEffect, useRef, useState } from "react";

import { Tree } from "@thewaver/ss-components-react";
import type { TreeNode } from "@thewaver/ss-components-react";

import { renderPageHighlightFloater } from "../../../StyledComponents/GlideFloater/GlideFloater";
import { PageTreeNodeContent, PageTreeNodePending } from "../../../StyledComponents/TreeNodeContent/TreeNodeContent";
import { REMOTE_CHILDREN, REMOTE_LOAD_DELAY_MS, REMOTE_ROOT } from "../TreePage.const";
import type { TreeExampleProps } from "../TreePage.types";

type Props = TreeExampleProps;

const fillBranch = (nodes: TreeNode<string>[], value: string): TreeNode<string>[] =>
    nodes.map((node) => {
        if (node.value === value) return { ...node, children: REMOTE_CHILDREN[value] ?? [], hasMoreChildren: false };

        if (!node.children) return node;

        return { ...node, children: fillBranch(node.children, value) };
    });

export const LazyExample = (props: Props) => {
    const [nodes, setNodes] = useState<TreeNode<string>[]>(REMOTE_ROOT);

    const loadedRef = useRef(new Set<string>());

    const expanded = props.expanded[0];

    useEffect(() => {
        const timers = expanded
            .filter((value) => !loadedRef.current.has(value))
            .map((value) =>
                setTimeout(() => {
                    loadedRef.current.add(value);
                    setNodes((prev) => fillBranch(prev, value));
                }, REMOTE_LOAD_DELAY_MS),
            );

        return () => timers.forEach((timer) => clearTimeout(timer));
    }, [expanded]);

    return (
        <Tree
            renderHighlightFloater={renderPageHighlightFloater}
            nodes={nodes}
            value={props.value}
            expanded={props.expanded}
            ariaLabel={"Remote repository"}
            renderNode={(node, renderProps) => (
                <PageTreeNodeContent isGliding renderProps={renderProps}>
                    {node.value}
                </PageTreeNodeContent>
            )}
            renderPendingChildren={(_node, depth) => <PageTreeNodePending depth={depth}>Fetching…</PageTreeNodePending>}
        />
    );
};
