// playground-react/src/App/StyledComponents/DrawerPanel/DrawerPanel.tsx
import type { PropsWithChildren } from "react";

import * as styles from "@thewaver/ss-playground-core/App/StyledComponents/DrawerPanel/DrawerPanel.css";

import { PageLayer } from "../../PageComponents/Layer/Layer";
import type { DrawerPanelProps } from "./DrawerPanel.types";

export const PageDrawerPanel = (props: PropsWithChildren<DrawerPanelProps>) => {
    return (
        <div
            className={[
                styles.drawerPanel,
                styles.drawerSizeVariants[props.edge],
                props.visibilityTarget === 1 ? styles.drawerSlideOn : styles.drawerSlideOffVariants[props.edge],
            ].join(" ")}
            style={{ transition: `transform ${props.transitionDurationMs}ms` }}
        >
            <PageLayer level={1}>{props.children}</PageLayer>
        </div>
    );
};

// playground-solid/src/App/StyledComponents/DrawerPanel/DrawerPanel.tsx
import type { ParentProps } from "solid-js";

import { access } from "@thewaver/ss-components-solid";
import * as styles from "@thewaver/ss-playground-core/App/StyledComponents/DrawerPanel/DrawerPanel.css";

import { PageLayer } from "../../PageComponents/Layer/Layer";
import type { DrawerPanelProps } from "./DrawerPanel.types";

export const PageDrawerPanel = (props: ParentProps<DrawerPanelProps>) => {
    return (
        <div
            class={[
                styles.drawerPanel,
                styles.drawerSizeVariants[access(props.edge)],
                access(props.visibilityTarget) === 1
                    ? styles.drawerSlideOn
                    : styles.drawerSlideOffVariants[access(props.edge)],
            ].join(" ")}
            style={{ transition: `transform ${access(props.transitionDurationMs)}ms` }}
        >
            <PageLayer level={1}>{props.children}</PageLayer>
        </div>
    );
};
