// playground-svelte/src/App/PageComponents/Field/PageTextField.svelte
<script lang="ts">
    import type { InteractionFlags, TextFieldFlags } from "@thewaver/ss-components-svelte";
    import { TextInput } from "@thewaver/ss-components-svelte";
    import {
        FIELD_GAP,
        FIELD_PADDING,
    } from "@thewaver/ss-playground/App/StyledComponents/TextFieldContent/TextFieldContent.css";

    import PageTextFieldContent, {
        computePageTextFieldTextStyle,
    } from "../../StyledComponents/TextFieldContent/TextFieldContent.svelte";
    import PageTextFieldPlaceholder from "../../StyledComponents/TextFieldPlaceholder/TextFieldPlaceholder.svelte";
    import { useFieldReset } from "./Field.context";
    import type { PageTextFieldProps } from "./Field.types";

    let props: PageTextFieldProps = $props();

    useFieldReset(
        () => props.value,
        (value) => props.onInput(value),
    );
</script>

<TextInput
    bind:value={() => props.value, props.onInput}
    isDisabled={props.isDisabled}
    ariaLabel={props.ariaLabel}
    padding={FIELD_PADDING}
    gap={FIELD_GAP}
    computeTextStyle={computePageTextFieldTextStyle}
    renderPlaceholder={props.placeholder === undefined ? undefined : renderPlaceholder}
>
    {#snippet renderContent(flags)}
        <PageTextFieldContent {flags} width={props.width} />
    {/snippet}
</TextInput>

{#snippet renderPlaceholder(flags: InteractionFlags<TextFieldFlags>)}
    <PageTextFieldPlaceholder {flags}>{props.placeholder}</PageTextFieldPlaceholder>
{/snippet}

// playground-vue/src/App/PageComponents/Field/PageTextField.vue
<script setup lang="ts">
import { TextInput } from "@thewaver/ss-components-vue";
import {
    FIELD_GAP,
    FIELD_PADDING,
} from "@thewaver/ss-playground/App/StyledComponents/TextFieldContent/TextFieldContent.css";

import PageTextFieldContent, {
    computePageTextFieldTextStyle,
} from "../../StyledComponents/TextFieldContent/TextFieldContent.vue";
import PageTextFieldPlaceholder from "../../StyledComponents/TextFieldPlaceholder/TextFieldPlaceholder.vue";
import { useFieldReset } from "./Field.context";
import type { PageTextFieldProps } from "./Field.types";

const props = defineProps<PageTextFieldProps>();

useFieldReset(props.value, (value) => props.onInput(value));
</script>

<template>
    <TextInput
        :value="value"
        :is-disabled="isDisabled"
        :ariaLabel="ariaLabel"
        :padding="FIELD_PADDING"
        :gap="FIELD_GAP"
        :compute-text-style="computePageTextFieldTextStyle"
        @update:value="props.onInput"
    >
        <template #renderContent="flags">
            <PageTextFieldContent :flags="flags" :width="width" />
        </template>

        <template v-if="placeholder !== undefined" #renderPlaceholder="{ flags }">
            <PageTextFieldPlaceholder :flags="flags">{{ placeholder }}</PageTextFieldPlaceholder>
        </template>
    </TextInput>
</template>
