// playground-solid/src/App/Pages/ToastsPage/ToastsPage.tsx
import { createRoot, createSignal, createUniqueId } from "solid-js";

import {
    Button,
    TOASTS_ALIGNMENTS,
    TOASTS_DEFAULTS,
    TOASTS_DIRS,
    TOASTS_OVERFLOWS,
    Toasts,
} from "@thewaver/ss-components-solid";
import type { Toast, ToastsAlignment, ToastsDir, ToastsOverflow } from "@thewaver/ss-components-solid";
import * as styles from "@thewaver/ss-playground/App/Pages/ToastsPage/ToastsPage.css";

import { ToastKnobs } from "../../Knobs/Toasts.const";
import { PageNumberField, PageSelectField } from "../../PageComponents/Field/Field";
import { PageProp } from "../../PageComponents/Prop/Prop";
import { PagePropsPanel } from "../../PageComponents/PropsPanel/PropsPanel";
import { PageButtonContent } from "../../StyledComponents/ButtonContent/ButtonContent";
import { PageToastContent } from "../../StyledComponents/ToastContent/ToastContent";
import type {
    ToastAnimation,
    ToastDefs,
    ToastKind,
    ToastStacking,
} from "../../StyledComponents/ToastContent/ToastContent.types";

const NO_LIMIT = 0;
const STICKY = 0;

const BURST_SIZE = 5;

const MESSAGES: Record<ToastKind, string> = {
    info: "Your export is being prepared.",
    success: "Settings saved.",
    error: "Upload failed — the file was larger than 25 MB.",
};

const toastQueue = createRoot(() => createSignal<Toast<ToastDefs>[]>([]));
const toastBoundaries = createRoot(() => createSignal({ shown: 0, hidden: 0 }));

const raiseToast = (kind: ToastKind, durationMs: number) => {
    toastQueue[1]((prev) => [
        ...prev,
        {
            id: createUniqueId(),
            value: { kind, message: MESSAGES[kind] },
            durationMs: durationMs === STICKY ? undefined : durationMs,
            ariaLive: kind === "error" ? "assertive" : "polite",
            onShow: () => toastBoundaries[1]((prev) => ({ ...prev, shown: prev.shown + 1 })),
            onHide: () => toastBoundaries[1]((prev) => ({ ...prev, hidden: prev.hidden + 1 })),
        },
    ]);
};

export const ToastsPage = () => {
    const [getAlignment, setAlignment] = createSignal<ToastsAlignment>(TOASTS_DEFAULTS.alignment);
    const [getDir, setDir] = createSignal<ToastsDir>(TOASTS_DEFAULTS.dir);
    const [getOverflow, setOverflow] = createSignal<ToastsOverflow>(TOASTS_DEFAULTS.overflow);
    const [getAnimation, setAnimation] = createSignal<ToastAnimation>(ToastKnobs.STARTING_ANIMATION);
    const [getStacking, setStacking] = createSignal<ToastStacking>(ToastKnobs.STARTING_STACKING);
    const [getLimit, setLimit] = createSignal(ToastKnobs.STARTING_LIMIT);
    const [getDurationMs, setDurationMs] = createSignal(ToastKnobs.STARTING_DURATION_MS);
    const [getGap, setGap] = createSignal(TOASTS_DEFAULTS.gap);
    const [getMargin, setMargin] = createSignal(ToastKnobs.STARTING_MARGIN);
    const [getTransitionDurationMs, setTransitionDurationMs] = createSignal(TOASTS_DEFAULTS.transitionDurationMs);

    const [getToasts, setToasts] = toastQueue;
    const [getBoundaries] = toastBoundaries;

    return (
        <div class={styles.root}>
            <PagePropsPanel scope={"global"}>
                <PageProp
                    key={"alignment"}
                    label={"Alignment"}
                    hint={"Which corner or edge of the screen the toasts gather at."}
                >
                    <PageSelectField
                        value={getAlignment}
                        values={() => TOASTS_ALIGNMENTS}
                        ariaLabel={"Alignment"}
                        onChange={(alignment) => setAlignment(() => alignment)}
                    />
                </PageProp>

                <PageProp
                    key={"dir"}
                    label={"Dir"}
                    hint={
                        "Which way the stack grows from there, and so whether a new toast joins at the top or the bottom."
                    }
                >
                    <PageSelectField
                        value={getDir}
                        values={() => TOASTS_DIRS}
                        ariaLabel={"Dir"}
                        onChange={(dir) => setDir(() => dir)}
                    />
                </PageProp>

                <PageProp
                    key={"limit"}
                    label={"Limit"}
                    hint={"How many toasts may be on screen at once. Choose none and they all show."}
                >
                    <PageSelectField
                        value={getLimit}
                        values={() => ToastKnobs.LIMITS}
                        ariaLabel={"Limit"}
                        computeLabel={(limit) => (limit === NO_LIMIT ? "none" : `${limit}`)}
                        onChange={setLimit}
                    />
                </PageProp>

                <PageProp
                    key={"overflow"}
                    label={"Overflow"}
                    hint={
                        "What happens when the limit is reached: the oldest toast is dismissed, or the newest waits its turn."
                    }
                >
                    <PageSelectField
                        value={getOverflow}
                        values={() => TOASTS_OVERFLOWS}
                        ariaLabel={"Overflow"}
                        onChange={(overflow) => setOverflow(() => overflow)}
                    />
                </PageProp>

                <PageProp
                    key={"durationMs"}
                    label={"Duration"}
                    hint={"How long a toast stays before it dismisses itself. Sticky ones wait to be closed."}
                >
                    <PageSelectField
                        value={getDurationMs}
                        values={() => ToastKnobs.DURATIONS_MS}
                        ariaLabel={"Duration"}
                        computeLabel={(durationMs) => (durationMs === STICKY ? "sticky" : `${durationMs}ms`)}
                        onChange={setDurationMs}
                    />
                </PageProp>

                <PageProp key={"animation"} label={"Animation"} hint={"How a toast arrives and leaves."}>
                    <PageSelectField
                        value={getAnimation}
                        values={() => ToastKnobs.ANIMATIONS}
                        ariaLabel={"Animation"}
                        onChange={(animation) => setAnimation(() => animation)}
                    />
                </PageProp>

                <PageProp
                    key={"stacking"}
                    label={"Stacking"}
                    hint={
                        "Whether the toasts sit in a row of their own, or pile up on each other with only the top one fully shown."
                    }
                >
                    <PageSelectField
                        value={getStacking}
                        values={() => ToastKnobs.STACKINGS}
                        ariaLabel={"Stacking"}
                        onChange={(stacking) => setStacking(() => stacking)}
                    />
                </PageProp>

                <PageProp key={"gap"} label={"Gap (px)"} hint={"The space between one toast and the next."}>
                    <PageNumberField
                        value={getGap}
                        min={() => ToastKnobs.MIN_GAP}
                        max={() => ToastKnobs.MAX_GAP}
                        ariaLabel={"Gap in pixels"}
                        onInput={setGap}
                    />
                </PageProp>

                <PageProp
                    key={"margin"}
                    label={"Margin (px)"}
                    hint={"How far the stack is held off the edge of the screen."}
                >
                    <PageNumberField
                        value={getMargin}
                        min={() => ToastKnobs.MIN_MARGIN}
                        max={() => ToastKnobs.MAX_MARGIN}
                        ariaLabel={"Margin in pixels"}
                        onInput={setMargin}
                    />
                </PageProp>

                <PageProp
                    key={"transitionDurationMs"}
                    label={"Transition duration (ms)"}
                    hint={"How long a toast takes to arrive, to leave, and to slide when the stack shifts."}
                >
                    <PageNumberField
                        value={getTransitionDurationMs}
                        min={() => ToastKnobs.MIN_TRANSITION_DURATION_MS}
                        max={() => ToastKnobs.MAX_TRANSITION_DURATION_MS}
                        step={() => ToastKnobs.TRANSITION_DURATION_STEP_MS}
                        ariaLabel={"Transition duration"}
                        onInput={setTransitionDurationMs}
                    />
                </PageProp>
            </PagePropsPanel>

            <div class={styles.raiseRow}>
                <Button
                    id={"raiseInfo"}
                    renderContent={(getFlags) => <PageButtonContent flags={getFlags}>Info</PageButtonContent>}
                    onClick={() => raiseToast("info", getDurationMs())}
                />
                <Button
                    id={"raiseSuccess"}
                    renderContent={(getFlags) => <PageButtonContent flags={getFlags}>Success</PageButtonContent>}
                    onClick={() => raiseToast("success", getDurationMs())}
                />
                <Button
                    id={"raiseError"}
                    renderContent={(getFlags) => <PageButtonContent flags={getFlags}>Error</PageButtonContent>}
                    onClick={() => raiseToast("error", getDurationMs())}
                />
                <Button
                    id={"raiseBurst"}
                    renderContent={(getFlags) => (
                        <PageButtonContent flags={getFlags}>Raise {BURST_SIZE}</PageButtonContent>
                    )}
                    onClick={() => {
                        for (let index = 0; index < BURST_SIZE; index += 1) raiseToast("info", getDurationMs());
                    }}
                />
                <Button
                    id={"clearToasts"}
                    renderContent={(getFlags) => <PageButtonContent flags={getFlags}>Clear</PageButtonContent>}
                    onClick={() => {
                        setToasts([]);
                    }}
                />
            </div>

            <div class={styles.note} data-readout>
                queued: {getToasts().length}, shown: {getBoundaries().shown}, hidden: {getBoundaries().hidden} — the
                queue lives at module scope, so raising a notification does not need the raiser to still be mounted.
                Hover the stack to hold every countdown, or press F8 to put the keyboard in it. A toast against the left
                or right edge, or centered along the top or bottom, can be swiped off that edge; Close is the route for
                anyone who cannot drag.
            </div>

            <Toasts
                toasts={toastQueue}
                ariaLabel={"Notifications"}
                computeAnnouncement={(toast) => toast.value.message}
                alignment={getAlignment}
                dir={getDir}
                limit={() => (getLimit() === NO_LIMIT ? undefined : getLimit())}
                overflow={getOverflow}
                gap={getGap}
                margins={() => ({
                    marginTop: getMargin(),
                    marginRight: getMargin(),
                    marginBottom: getMargin(),
                    marginLeft: getMargin(),
                })}
                transitionDurationMs={getTransitionDurationMs}
                renderToast={(getToast, getVisibilityTarget, getToastTransitionDurationMs, getState) => (
                    <PageToastContent
                        toast={getToast}
                        state={getState}
                        animation={getAnimation}
                        stacking={getStacking}
                        dir={getDir}
                        gap={getGap}
                        visibilityTarget={getVisibilityTarget}
                        transitionDurationMs={getToastTransitionDurationMs}
                        onDismiss={() => setToasts((prev) => prev.filter((toast) => toast.id !== getToast().id))}
                    />
                )}
            />
        </div>
    );
};

// playground-react/src/App/Pages/ToastsPage/ToastsPage.tsx
import { useState } from "react";

import {
    Button,
    TOASTS_ALIGNMENTS,
    TOASTS_DEFAULTS,
    TOASTS_DIRS,
    TOASTS_OVERFLOWS,
    Toasts,
    useStore,
} from "@thewaver/ss-components-react";
import type { Toast, ToastsAlignment, ToastsDir, ToastsOverflow } from "@thewaver/ss-components-react";
import * as styles from "@thewaver/ss-playground/App/Pages/ToastsPage/ToastsPage.css";
import { StoreUtils } from "@thewaver/ss-utils";

import { ToastKnobs } from "../../Knobs/Toasts.const";
import { PageNumberField, PageSelectField } from "../../PageComponents/Field/Field";
import { PageProp } from "../../PageComponents/Prop/Prop";
import { PagePropsPanel } from "../../PageComponents/PropsPanel/PropsPanel";
import { PageButtonContent } from "../../StyledComponents/ButtonContent/ButtonContent";
import { PageToastContent } from "../../StyledComponents/ToastContent/ToastContent";
import type {
    ToastAnimation,
    ToastDefs,
    ToastKind,
    ToastStacking,
} from "../../StyledComponents/ToastContent/ToastContent.types";

const NO_LIMIT = 0;
const STICKY = 0;

const BURST_SIZE = 5;

const MESSAGES: Record<ToastKind, string> = {
    info: "Your export is being prepared.",
    success: "Settings saved.",
    error: "Upload failed — the file was larger than 25 MB.",
};

const TOAST_ID_PREFIX = "toast";

const toastQueue = StoreUtils.create<Toast<ToastDefs>[]>([]);
const toastBoundaries = StoreUtils.create({ shown: 0, hidden: 0 });

let toastCount = 0;

const raiseToast = (kind: ToastKind, durationMs: number) => {
    toastCount += 1;

    const id = `${TOAST_ID_PREFIX}${toastCount}`;

    toastQueue.update((prev) => [
        ...prev,
        {
            id,
            value: { kind, message: MESSAGES[kind] },
            durationMs: durationMs === STICKY ? undefined : durationMs,
            ariaLive: kind === "error" ? "assertive" : "polite",
            onShow: () => toastBoundaries.update((prev) => ({ ...prev, shown: prev.shown + 1 })),
            onHide: () => toastBoundaries.update((prev) => ({ ...prev, hidden: prev.hidden + 1 })),
        },
    ]);
};

export const ToastsPage = () => {
    const [alignment, setAlignment] = useState<ToastsAlignment>(TOASTS_DEFAULTS.alignment);
    const [dir, setDir] = useState<ToastsDir>(TOASTS_DEFAULTS.dir);
    const [overflow, setOverflow] = useState<ToastsOverflow>(TOASTS_DEFAULTS.overflow);
    const [animation, setAnimation] = useState<ToastAnimation>(ToastKnobs.STARTING_ANIMATION);
    const [stacking, setStacking] = useState<ToastStacking>(ToastKnobs.STARTING_STACKING);
    const [limit, setLimit] = useState(ToastKnobs.STARTING_LIMIT);
    const [durationMs, setDurationMs] = useState(ToastKnobs.STARTING_DURATION_MS);
    const [gap, setGap] = useState(TOASTS_DEFAULTS.gap);
    const [margin, setMargin] = useState(ToastKnobs.STARTING_MARGIN);
    const [transitionDurationMs, setTransitionDurationMs] = useState(TOASTS_DEFAULTS.transitionDurationMs);

    const toasts = useStore(toastQueue);
    const boundaries = useStore(toastBoundaries);

    const setToasts = (next: Toast<ToastDefs>[]) => {
        toastQueue.set(next);
    };

    return (
        <div className={styles.root}>
            <PagePropsPanel scope={"global"}>
                <PageProp
                    itemKey={"alignment"}
                    label={"Alignment"}
                    hint={"Which corner or edge of the screen the toasts gather at."}
                >
                    <PageSelectField
                        value={alignment}
                        values={TOASTS_ALIGNMENTS}
                        ariaLabel={"Alignment"}
                        onChange={setAlignment}
                    />
                </PageProp>

                <PageProp
                    itemKey={"dir"}
                    label={"Dir"}
                    hint={
                        "Which way the stack grows from there, and so whether a new toast joins at the top or the bottom."
                    }
                >
                    <PageSelectField value={dir} values={TOASTS_DIRS} ariaLabel={"Dir"} onChange={setDir} />
                </PageProp>

                <PageProp
                    itemKey={"limit"}
                    label={"Limit"}
                    hint={"How many toasts may be on screen at once. Choose none and they all show."}
                >
                    <PageSelectField
                        value={limit}
                        values={ToastKnobs.LIMITS}
                        ariaLabel={"Limit"}
                        computeLabel={(limit) => (limit === NO_LIMIT ? "none" : `${limit}`)}
                        onChange={setLimit}
                    />
                </PageProp>

                <PageProp
                    itemKey={"overflow"}
                    label={"Overflow"}
                    hint={
                        "What happens when the limit is reached: the oldest toast is dismissed, or the newest waits its turn."
                    }
                >
                    <PageSelectField
                        value={overflow}
                        values={TOASTS_OVERFLOWS}
                        ariaLabel={"Overflow"}
                        onChange={setOverflow}
                    />
                </PageProp>

                <PageProp
                    itemKey={"durationMs"}
                    label={"Duration"}
                    hint={"How long a toast stays before it dismisses itself. Sticky ones wait to be closed."}
                >
                    <PageSelectField
                        value={durationMs}
                        values={ToastKnobs.DURATIONS_MS}
                        ariaLabel={"Duration"}
                        computeLabel={(durationMs) => (durationMs === STICKY ? "sticky" : `${durationMs}ms`)}
                        onChange={setDurationMs}
                    />
                </PageProp>

                <PageProp itemKey={"animation"} label={"Animation"} hint={"How a toast arrives and leaves."}>
                    <PageSelectField
                        value={animation}
                        values={ToastKnobs.ANIMATIONS}
                        ariaLabel={"Animation"}
                        onChange={setAnimation}
                    />
                </PageProp>

                <PageProp
                    itemKey={"stacking"}
                    label={"Stacking"}
                    hint={
                        "Whether the toasts sit in a row of their own, or pile up on each other with only the top one fully shown."
                    }
                >
                    <PageSelectField
                        value={stacking}
                        values={ToastKnobs.STACKINGS}
                        ariaLabel={"Stacking"}
                        onChange={setStacking}
                    />
                </PageProp>

                <PageProp itemKey={"gap"} label={"Gap (px)"} hint={"The space between one toast and the next."}>
                    <PageNumberField
                        value={gap}
                        min={ToastKnobs.MIN_GAP}
                        max={ToastKnobs.MAX_GAP}
                        ariaLabel={"Gap in pixels"}
                        onInput={setGap}
                    />
                </PageProp>

                <PageProp
                    itemKey={"margin"}
                    label={"Margin (px)"}
                    hint={"How far the stack is held off the edge of the screen."}
                >
                    <PageNumberField
                        value={margin}
                        min={ToastKnobs.MIN_MARGIN}
                        max={ToastKnobs.MAX_MARGIN}
                        ariaLabel={"Margin in pixels"}
                        onInput={setMargin}
                    />
                </PageProp>

                <PageProp
                    itemKey={"transitionDurationMs"}
                    label={"Transition duration (ms)"}
                    hint={"How long a toast takes to arrive, to leave, and to slide when the stack shifts."}
                >
                    <PageNumberField
                        value={transitionDurationMs}
                        min={ToastKnobs.MIN_TRANSITION_DURATION_MS}
                        max={ToastKnobs.MAX_TRANSITION_DURATION_MS}
                        step={ToastKnobs.TRANSITION_DURATION_STEP_MS}
                        ariaLabel={"Transition duration"}
                        onInput={setTransitionDurationMs}
                    />
                </PageProp>
            </PagePropsPanel>

            <div className={styles.raiseRow}>
                <Button
                    id={"raiseInfo"}
                    renderContent={(flags) => <PageButtonContent flags={flags}>Info</PageButtonContent>}
                    onClick={() => raiseToast("info", durationMs)}
                />
                <Button
                    id={"raiseSuccess"}
                    renderContent={(flags) => <PageButtonContent flags={flags}>Success</PageButtonContent>}
                    onClick={() => raiseToast("success", durationMs)}
                />
                <Button
                    id={"raiseError"}
                    renderContent={(flags) => <PageButtonContent flags={flags}>Error</PageButtonContent>}
                    onClick={() => raiseToast("error", durationMs)}
                />
                <Button
                    id={"raiseBurst"}
                    renderContent={(flags) => <PageButtonContent flags={flags}>Raise {BURST_SIZE}</PageButtonContent>}
                    onClick={() => {
                        for (let index = 0; index < BURST_SIZE; index += 1) raiseToast("info", durationMs);
                    }}
                />
                <Button
                    id={"clearToasts"}
                    renderContent={(flags) => <PageButtonContent flags={flags}>Clear</PageButtonContent>}
                    onClick={() => {
                        setToasts([]);
                    }}
                />
            </div>

            <div className={styles.note} data-readout="">
                queued: {toasts.length}, shown: {boundaries.shown}, hidden: {boundaries.hidden} — the queue lives at
                module scope, so raising a notification does not need the raiser to still be mounted. Hover the stack to
                hold every countdown, or press F8 to put the keyboard in it. A toast against the left or right edge, or
                centered along the top or bottom, can be swiped off that edge; Close is the route for anyone who cannot
                drag.
            </div>

            <Toasts
                toasts={[toasts, setToasts]}
                ariaLabel={"Notifications"}
                computeAnnouncement={(toast) => toast.value.message}
                alignment={alignment}
                dir={dir}
                limit={limit === NO_LIMIT ? undefined : limit}
                overflow={overflow}
                gap={gap}
                margins={{
                    marginTop: margin,
                    marginRight: margin,
                    marginBottom: margin,
                    marginLeft: margin,
                }}
                transitionDurationMs={transitionDurationMs}
                renderToast={(toast, visibilityTarget, toastTransitionDurationMs, state) => (
                    <PageToastContent
                        toast={toast}
                        state={state}
                        animation={animation}
                        stacking={stacking}
                        dir={dir}
                        gap={gap}
                        visibilityTarget={visibilityTarget}
                        transitionDurationMs={toastTransitionDurationMs}
                        onDismiss={() => toastQueue.update((prev) => prev.filter((entry) => entry.id !== toast.id))}
                    />
                )}
            />
        </div>
    );
};
