// components/src/Essentials/Preview/Preview.tsx
import { Show, createEffect, createMemo, createSignal, createUniqueId, on, onCleanup } from "solid-js";

import { ElementFaderUtils } from "../../Abstracts/ElementFader/ElementFader.utils";
import { ElementObserverUtils } from "../../Abstracts/ElementObserver/ElementObserver.utils";
import { InteractionWrapper } from "../../Primitives/InteractionWrapper/InteractionWrapper";
import { access, accessSignal } from "../../Utils/propUtils";
import { PREVIEW_DEFAULTS } from "./Preview.const";
import type { PreviewFlags, PreviewProps, PreviewTriggerProps } from "./Preview.types";

import * as styles from "./Preview.css";

const PreviewTrigger = (props: PreviewTriggerProps) => {
    const getIsDisabled = () => access(props.flags).isDisabled ?? false;

    return (
        <button
            id={access(props.id)}
            ref={(element) => props.ref?.(element)}
            type="button"
            class={styles.previewTrigger}
            aria-expanded={access(props.isExpanded)}
            aria-controls={access(props.contentId)}
            aria-disabled={getIsDisabled() || undefined}
            onClick={() => {
                if (getIsDisabled()) return;

                props.onToggle();
            }}
        >
            {props.renderTrigger(() => access(props.flags))}
        </button>
    );
};

export const Preview = (props: PreviewProps) => {
    const expandedSignal = accessSignal(() => props.expandedSignal);

    const contentId = createUniqueId();

    const [getRootRef, setRootRef] = createSignal<HTMLElement>();
    const [getTriggerRef, setTriggerRef] = createSignal<HTMLElement>();
    const [getContentRef, setContentRef] = createSignal<HTMLElement>();
    const [getIsAwaitingScroll, setIsAwaitingScroll] = createSignal(false);

    const getIsExpanded = () => expandedSignal[0]();

    const getTransitionDurationMs = createMemo(
        () => access(props.transitionDurationMs) ?? PREVIEW_DEFAULTS.transitionDurationMs,
    );

    const getSizing = createMemo(() => access(props.sizing) ?? PREVIEW_DEFAULTS.sizing);

    const getContentHeight = ElementObserverUtils.createBorderBoxHeightObserver(getContentRef);

    const getHasMeasured = createMemo(() => getContentHeight() > 0);

    const getIsOverflowing = createMemo(() => getHasMeasured() && getContentHeight() > access(props.collapsedHeight));

    const { getTransitionTarget, getHasTransitionFinished } = ElementFaderUtils.createFader(getIsExpanded, {
        getTransitionDurationMs,
        getRef: getRootRef,
    });

    createEffect(on(getIsExpanded, (isExpanded) => setIsAwaitingScroll(!isExpanded), { defer: true }));

    createEffect(() => {
        if (!getIsAwaitingScroll() || !getHasTransitionFinished()) return;

        setIsAwaitingScroll(false);

        const root = getRootRef();
        const trigger = getTriggerRef();

        if (access(props.isScrolledIntoViewOnCollapse) !== true || !root || !trigger) return;

        const scrollIntoView = () => {
            root.scrollIntoView({ block: "nearest" });
            trigger.scrollIntoView({ block: "nearest" });
        };

        scrollIntoView();

        const frameId = requestAnimationFrame(scrollIntoView);

        onCleanup(() => {
            cancelAnimationFrame(frameId);
        });
    });

    const getHeight = createMemo(() => {
        if (!getHasMeasured()) return access(props.collapsedHeight);

        return getTransitionTarget() === 1 || !getIsOverflowing() ? getContentHeight() : access(props.collapsedHeight);
    });

    const getOverlayTarget = createMemo((): 0 | 1 => (getTransitionTarget() === 1 ? 0 : 1));

    return (
        <div ref={setRootRef} class={[styles.previewRoot, styles.previewSizingVariants[getSizing()]].join(" ")}>
            <div class={styles.previewFrame}>
                <div
                    id={contentId}
                    class={styles.previewContent}
                    style={{
                        "height": `${getHeight()}px`,
                        "transition-property": "height",
                        "transition-duration": `${getTransitionDurationMs()}ms`,
                    }}
                >
                    <div ref={setContentRef}>{props.renderContent()}</div>
                </div>

                <Show when={props.renderOverlay && getIsOverflowing()}>
                    <div class={styles.previewOverlay}>
                        {props.renderOverlay?.(getOverlayTarget, getTransitionDurationMs)}
                    </div>
                </Show>
            </div>

            <Show when={getIsOverflowing()}>
                <InteractionWrapper
                    {...props}
                    sizing={"fit-content"}
                    extraFlags={(): PreviewFlags => ({ isExpanded: getIsExpanded() })}
                    renderControl={(setElementRef, getFlags) => (
                        <PreviewTrigger
                            ref={(element) => {
                                setElementRef(element);
                                setTriggerRef(element);
                                props.ref?.(element);
                            }}
                            id={props.id}
                            contentId={() => contentId}
                            flags={getFlags}
                            isExpanded={getIsExpanded}
                            renderTrigger={props.renderTrigger}
                            onToggle={() => expandedSignal[1]((prev) => !prev)}
                        />
                    )}
                />
            </Show>
        </div>
    );
};

// components-svelte/src/Essentials/Preview/Preview.svelte
<script lang="ts">
    import {
        CollapsibleUtils,
        PREVIEW_DEFAULTS,
        type PreviewFlags,
        PreviewUtils,
        PreviewStyles as styles,
    } from "@thewaver/ss-components";

    import { ElementFaderSvelteUtils } from "../../Abstracts/ElementFader/ElementFaderSvelte.utils.svelte.js";
    import { ElementObserverSvelteUtils } from "../../Abstracts/ElementObserver/ElementObserverSvelte.utils.svelte.js";
    import InteractionWrapper from "../../Primitives/InteractionWrapper/InteractionWrapper.svelte";
    import { watchChange } from "../../Utils/effectUtils.svelte.js";
    import type { PreviewProps } from "./Preview.types.js";
    import PreviewTrigger from "./PreviewTrigger.svelte";

    let { expanded = $bindable(false), ref = $bindable(), ...props }: PreviewProps = $props();

    const contentId = $props.id();

    let root = $state<HTMLDivElement>();
    let content = $state<HTMLDivElement>();

    const transitionDurationMs = $derived(props.transitionDurationMs ?? PREVIEW_DEFAULTS.transitionDurationMs);
    const sizing = $derived(props.sizing ?? PREVIEW_DEFAULTS.sizing);

    const getContentHeight = ElementObserverSvelteUtils.createBorderBoxHeightObserver(() => content ?? undefined);

    const isOverflowing = $derived(PreviewUtils.computeIsOverflowing(getContentHeight(), props.collapsedHeight));

    const fader = ElementFaderSvelteUtils.createFader(() => expanded, {
        getTransitionDurationMs: () => transitionDurationMs,
        getRef: () => root ?? undefined,
    });

    let isAwaitingScroll = false;

    watchChange(
        () => expanded,
        (isExpanded) => {
            isAwaitingScroll = !isExpanded;
        },
    );

    $effect(() => {
        expanded;

        if (!isAwaitingScroll || !fader.getHasTransitionFinished()) return;

        isAwaitingScroll = false;

        const rootElement = root;
        const trigger = ref;

        if (props.isScrolledIntoViewOnCollapse !== true || !rootElement || !trigger) return;

        return CollapsibleUtils.scrollIntoView(rootElement, trigger);
    });

    const height = $derived(
        PreviewUtils.computeHeight(getContentHeight(), props.collapsedHeight, fader.getTransitionTarget()),
    );

    const extraFlags: PreviewFlags = $derived({ isExpanded: expanded });
</script>

<div bind:this={root} class={[styles.previewRoot, styles.previewSizingVariants[sizing]]}>
    <div class={styles.previewFrame}>
        <div
            id={contentId}
            class={styles.previewContent}
            style:height={`${height}px`}
            style:transition-property="height"
            style:transition-duration={`${transitionDurationMs}ms`}
        >
            <div bind:this={content}>{@render props.renderContent()}</div>
        </div>

        {#if props.renderOverlay && isOverflowing}
            <div class={styles.previewOverlay}>
                {@render props.renderOverlay(
                    PreviewUtils.computeOverlayTarget(fader.getTransitionTarget()),
                    transitionDurationMs,
                )}
            </div>
        {/if}
    </div>

    {#if isOverflowing}
        <InteractionWrapper {...props} bind:ref sizing="fit-content" {extraFlags}>
            {#snippet renderControl(attachElement, flags)}
                <PreviewTrigger
                    {attachElement}
                    id={props.id}
                    {contentId}
                    {flags}
                    isExpanded={expanded}
                    renderTrigger={props.renderTrigger}
                    onToggle={() => {
                        expanded = !expanded;
                    }}
                />
            {/snippet}
        </InteractionWrapper>
    {/if}
</div>
