// components-vue/src/Primitives/PlacementBox/PlacementBox.tsx
import { type SlotsType, computed, defineComponent, shallowRef } from "vue";

import { PLACEMENT_BOX_DEFAULTS, PlacementBoxStyles, PlacementBoxUtils, PlacementUtils } from "@thewaver/ss-components";

import { MediaQueryMonitorVueUtils } from "../../Abstracts/MediaQueryMonitor/MediaQueryMonitorVue.utils";
import { PointerTrackerVueUtils } from "../../Abstracts/PointerTracker/PointerTrackerVue.utils";
import { declareProps } from "../../Utils/propUtils";
import type { SlotsContext } from "../../Utils/typeUtils";
import { providePlacementBoxContext } from "./PlacementBox.context";
import type { PlacementBoxProps, PlacementBoxSlots } from "./PlacementBox.types";

export const PlacementBox = defineComponent(
    (props: PlacementBoxProps, { slots }: SlotsContext<PlacementBoxSlots>) => {
        const boxRef = shallowRef<HTMLDivElement>();

        const getHasEffect = () => props.computeEffect !== undefined;
        const getTransitionDurationMs = () => props.transitionDurationMs ?? PLACEMENT_BOX_DEFAULTS.transitionDurationMs;

        const { reading, isPointerPresent } = PointerTrackerVueUtils.usePointerReading(
            boxRef,
            () => !getHasEffect(),
            () => props.pointSource,
        );

        const prefersReducedMotion = MediaQueryMonitorVueUtils.useReducedMotion(
            () => !PlacementBoxUtils.getIsMotionQueryNeeded(getHasEffect(), getTransitionDurationMs()),
        );

        const pointerPoint = computed(() =>
            PlacementBoxUtils.computePointerPoint(
                props.layout,
                reading.value.boxRatio,
                isPointerPresent.value,
                getHasEffect(),
            ),
        );

        const arrangement = computed(() => PlacementBoxUtils.computeArrangement(props.layout, getHasEffect()));

        const overreach = computed(() => PlacementBoxUtils.computeOverreach(props.layout, pointerPoint.value));

        const effectiveDurationMs = computed(() =>
            PlacementBoxUtils.computeTransitionDurationMs(getTransitionDurationMs(), prefersReducedMotion.value),
        );

        providePlacementBoxContext({
            getPointerPoint: () => pointerPoint.value,
            getArrangement: () => arrangement.value,
            getOverreach: () => overreach.value,
            getPrefersReducedMotion: () => prefersReducedMotion.value,
            getComputeEffect: () => props.computeEffect,
            getTransitionDurationMs: () => effectiveDurationMs.value,
        });

        return () => (
            <div ref={boxRef} class={PlacementBoxStyles.placementBox} role="presentation">
                <div
                    class={PlacementBoxStyles.placementSpacer}
                    style={{ height: PlacementUtils.toContainerWidth(props.layout.heightRatio) }}
                    aria-hidden="true"
                />

                {slots.default?.()}
            </div>
        );
    },
    {
        name: "PlacementBox",
        slots: Object as SlotsType<PlacementBoxSlots>,
        props: declareProps<PlacementBoxProps>({
            layout: null,
            transitionDurationMs: null,
            pointSource: null,
            computeEffect: null,
        }),
    },
);

// components-react/src/Primitives/PlacementBox/PlacementBox.tsx
import { useCallback, useMemo, useRef } from "react";

import {
    PLACEMENT_BOX_DEFAULTS,
    type PlacementBoxContextType,
    PlacementBoxStyles,
    PlacementBoxUtils,
    PlacementUtils,
} from "@thewaver/ss-components";

import { MediaQueryMonitorReactUtils } from "../../Abstracts/MediaQueryMonitor/MediaQueryMonitorReact.utils";
import { PointerTrackerReactUtils } from "../../Abstracts/PointerTracker/PointerTrackerReact.utils";
import { useLatest } from "../../Utils/refUtils";
import { PlacementBoxContextProvider } from "./PlacementBox.context";
import type { PlacementBoxProps } from "./PlacementBox.types";

export const PlacementBox = (props: PlacementBoxProps) => {
    const boxRef = useRef<HTMLDivElement | null>(null);
    const latestRef = useLatest(props.ref);

    const layout = props.layout;
    const computeEffect = props.computeEffect;
    const hasEffect = computeEffect !== undefined;
    const transitionDurationMs = props.transitionDurationMs ?? PLACEMENT_BOX_DEFAULTS.transitionDurationMs;

    const { reading, isPointerPresent } = PointerTrackerReactUtils.usePointerReading(
        boxRef,
        !hasEffect,
        props.pointSource,
    );

    const prefersReducedMotion = MediaQueryMonitorReactUtils.useReducedMotion(
        !PlacementBoxUtils.getIsMotionQueryNeeded(hasEffect, transitionDurationMs),
    );

    const pointerPoint = useMemo(
        () => PlacementBoxUtils.computePointerPoint(layout, reading.boxRatio, isPointerPresent, hasEffect),
        [layout, reading.boxRatio, isPointerPresent, hasEffect],
    );

    const arrangement = useMemo(() => PlacementBoxUtils.computeArrangement(layout, hasEffect), [layout, hasEffect]);

    const overreach = PlacementBoxUtils.computeOverreach(layout, pointerPoint);

    const effectiveDurationMs = PlacementBoxUtils.computeTransitionDurationMs(
        transitionDurationMs,
        prefersReducedMotion,
    );

    const context = useMemo<PlacementBoxContextType>(
        () => ({
            getPointerPoint: () => pointerPoint,
            getArrangement: () => arrangement,
            getOverreach: () => overreach,
            getPrefersReducedMotion: () => prefersReducedMotion,
            getComputeEffect: () => computeEffect,
            getTransitionDurationMs: () => effectiveDurationMs,
        }),
        [pointerPoint, arrangement, overreach, prefersReducedMotion, computeEffect, effectiveDurationMs],
    );

    const setBoxRef = useCallback(
        (element: HTMLDivElement | null) => {
            boxRef.current = element;
            latestRef.current?.(element);
        },
        [latestRef],
    );

    return (
        <PlacementBoxContextProvider value={context}>
            <div ref={setBoxRef} className={PlacementBoxStyles.placementBox} role="presentation">
                <div
                    className={PlacementBoxStyles.placementSpacer}
                    style={{ height: PlacementUtils.toContainerWidth(layout.heightRatio) }}
                    aria-hidden="true"
                />

                {props.children}
            </div>
        </PlacementBoxContextProvider>
    );
};
