// playground-react/src/App/PageComponents/PropsPanel/PropsPanel.tsx
import type { PropsWithChildren } from "react";
import { useMemo, useState } from "react";

import { Button } from "@thewaver/ss-components-react";
import * as styles from "@thewaver/ss-playground-core/App/PageComponents/PropsPanel/PropsPanel.css";

import { PageButtonContent } from "../../StyledComponents/ButtonContent/ButtonContent";
import type { FieldResetRegistry } from "../Field/Field.context";
import { FieldResetProvider } from "../Field/Field.context";
import { PageProp } from "../Prop/Prop";
import { PropsPanelContextProvider } from "./PropsPanel.context";
import type { PagePropsPanelProps } from "./PropsPanel.types";

const NOTHING_TO_RESET = 0;
const SAMPLE_SELECTOR_ALONE = 1;

export const PagePropsGroups = (props: PropsWithChildren) => <div className={styles.propsGroups}>{props.children}</div>;

export const PagePropsPanel = (props: PropsWithChildren<PagePropsPanelProps>) => {
    const [resets, setResets] = useState<(() => void)[]>([]);

    const [resetRegistry] = useState<FieldResetRegistry>(() => ({
        register: (reset) => {
            setResets((list) => [...list, reset]);

            return () => setResets((list) => list.filter((entry) => entry !== reset));
        },
    }));

    const scopeContext = useMemo(() => ({ scope: props.scope }), [props.scope]);

    const isSampleScope = props.scope === "sample";

    const leastToReset = isSampleScope ? SAMPLE_SELECTOR_ALONE : NOTHING_TO_RESET;

    const resettable = isSampleScope ? resets.slice(SAMPLE_SELECTOR_ALONE) : resets;

    return (
        <div className={styles.propsPanelScopeVariants[props.scope]} data-panel={props.scope}>
            <FieldResetProvider value={resetRegistry}>
                <PropsPanelContextProvider value={scopeContext}>
                    {props.children}

                    {resets.length > leastToReset && (
                        <PageProp
                            itemKey={"resetPanel"}
                            label={"These controls"}
                            hint={"Puts every control in this panel back to the value it started at."}
                        >
                            <Button
                                renderContent={(flags) => <PageButtonContent flags={flags}>Reset</PageButtonContent>}
                                onClick={() => {
                                    resettable.forEach((reset) => reset());
                                }}
                            />
                        </PageProp>
                    )}
                </PropsPanelContextProvider>
            </FieldResetProvider>
        </div>
    );
};

export const PagePropsDivider = () => <div className={styles.propsPanelDivider} role={"separator"} />;

// playground-solid/src/App/PageComponents/PropsPanel/PropsPanel.tsx
import type { ParentProps } from "solid-js";
import { Show, createSignal } from "solid-js";

import { Button, access } from "@thewaver/ss-components-solid";
import * as styles from "@thewaver/ss-playground-core/App/PageComponents/PropsPanel/PropsPanel.css";

import { PageButtonContent } from "../../StyledComponents/ButtonContent/ButtonContent";
import { FieldResetProvider } from "../Field/Field.context";
import { PageProp } from "../Prop/Prop";
import { PropsPanelContextProvider } from "./PropsPanel.context";
import type { PagePropsPanelProps } from "./PropsPanel.types";

const NOTHING_TO_RESET = 0;
const SAMPLE_SELECTOR_ALONE = 1;

export const PagePropsGroups = (props: ParentProps) => <div class={styles.propsGroups}>{props.children}</div>;

export const PagePropsPanel = (props: ParentProps<PagePropsPanelProps>) => {
    const [getResets, setResets] = createSignal<(() => void)[]>([]);

    const getIsSampleScope = () => access(props.scope) === "sample";

    const getLeastToReset = () => (getIsSampleScope() ? SAMPLE_SELECTOR_ALONE : NOTHING_TO_RESET);

    const getResettable = () => (getIsSampleScope() ? getResets().slice(SAMPLE_SELECTOR_ALONE) : getResets());

    const register = (reset: () => void) => {
        setResets((list) => [...list, reset]);

        return () => setResets((list) => list.filter((entry) => entry !== reset));
    };

    return (
        <div class={styles.propsPanelScopeVariants[access(props.scope)]} data-panel={access(props.scope)}>
            <FieldResetProvider value={{ register }}>
                <PropsPanelContextProvider value={{ scope: props.scope }}>
                    {props.children}

                    <Show when={getResets().length > getLeastToReset()}>
                        <PageProp
                            key={"resetPanel"}
                            label={"These controls"}
                            hint={"Puts every control in this panel back to the value it started at."}
                        >
                            <Button
                                renderContent={(getFlags) => (
                                    <PageButtonContent flags={getFlags}>Reset</PageButtonContent>
                                )}
                                onClick={() => {
                                    getResettable().forEach((reset) => reset());
                                }}
                            />
                        </PageProp>
                    </Show>
                </PropsPanelContextProvider>
            </FieldResetProvider>
        </div>
    );
};

export const PagePropsDivider = () => <div class={styles.propsPanelDivider} role={"separator"} />;
