// playground-svelte/src/App/Pages/RangePage/Examples/DisabledPair.svelte
<script lang="ts">
    import { Range } from "@thewaver/ss-components-svelte";
    import { RANGE_THUMB_SIZE } from "@thewaver/ss-playground/App/StyledComponents/RangeContent/RangeContent.css";

    import PageRangeContent from "../../../StyledComponents/RangeContent/RangeContent.svelte";
    import type { RangePairExampleProps } from "../RangePage.types";

    type Props = RangePairExampleProps;

    let { range = $bindable() }: Props = $props();
</script>

<Range
    bind:range
    ariaLabel={"Locked band"}
    thumbLabels={["Locked floor", "Locked ceiling"]}
    isDisabled={true}
    thumbSize={RANGE_THUMB_SIZE}
>
    {#snippet renderContent(renderProps)}
        <PageRangeContent {renderProps} />
    {/snippet}
</Range>

// playground-react/src/App/Pages/RangePage/Examples/DisabledPair.tsx
import { Range } from "@thewaver/ss-components-react";
import { RANGE_THUMB_SIZE } from "@thewaver/ss-playground/App/StyledComponents/RangeContent/RangeContent.css";

import { PageRangeContent } from "../../../StyledComponents/RangeContent/RangeContent";
import type { RangePairExampleProps } from "../RangePage.types";

type Props = RangePairExampleProps;

export const DisabledPairExample = (props: Props) => (
    <Range
        range={props.range}
        ariaLabel={"Locked band"}
        thumbLabels={["Locked floor", "Locked ceiling"]}
        isDisabled={true}
        thumbSize={RANGE_THUMB_SIZE}
        renderContent={(renderProps) => <PageRangeContent renderProps={renderProps} />}
    />
);
