// components-svelte/src/Exotics/Shape/Shape.svelte
<script lang="ts">
    import { ShapeLayerUtils, ShapeStyles as styles } from "@thewaver/ss-components";
    import { Size2d } from "@thewaver/ss-utils";

    import Markup from "../../Utils/Markup.svelte";
    import type { ShapeProps } from "./Shape.types.js";

    const INITIAL_SIZE: Size2d = { width: 0, height: 0 };

    let props: ShapeProps = $props();

    let root = $state<HTMLDivElement>();
    let rootSize = $state.raw(INITIAL_SIZE);

    $effect(() => {
        const element = root;

        if (!element) return;

        const observer = new ResizeObserver(() => {
            const next = { width: element.offsetWidth, height: element.offsetHeight };

            if (!Size2d.isSame(rootSize, next)) rootSize = next;
        });

        observer.observe(element);

        return () => observer.disconnect();
    });

    const fillDefs = $derived(props.computeFillDefs?.(rootSize, root ?? undefined));
    const strokeDefs = $derived(props.computeStrokeDefs?.(rootSize, root ?? undefined));

    const paths = $derived(
        ShapeLayerUtils.computeLayerPaths(
            props.computePoints(rootSize),
            strokeDefs,
            props.strokeGeom,
            props.joinRadii,
            props.lameExponents,
        ),
    );

    const viewBox = $derived(`0 0 ${rootSize.width} ${rootSize.height}`);
</script>

<div
    bind:this={root}
    class={styles.shapeRoot}
    style:shape-outside={ShapeLayerUtils.computeShapeOutside(paths[0].outerContour)}
>
    {#if fillDefs}
        <svg
            class={styles.shapeFillSVG}
            width={rootSize.width}
            height={rootSize.height}
            {viewBox}
            overflow="visible"
        >
            <defs>
                {#each fillDefs as def, index (index)}
                    <Markup markup={def.gradientOrPattern?.renderDefsElement()} />
                    <Markup markup={def.filter?.renderDefsElement()} />
                    <Markup markup={def.clipPath?.renderDefsElement()} />
                {/each}
            </defs>

            {#each fillDefs as def, index (index)}
                {@const paint = ShapeLayerUtils.computePaint(def)}
                <path
                    d={paths[0].outerPath}
                    fill={paint.fill}
                    fill-opacity={paint.fillOpacity}
                    filter={paint.filter}
                    clip-path={paint.clipPath}
                    style:mix-blend-mode={paint.mixBlendMode}
                />
            {/each}
        </svg>
    {/if}

    {@render props.renderChildren(rootSize, paths[0].outerPath, paths[0].outerPoints)}

    {#if strokeDefs}
        <svg
            class={styles.shapeStrokeSVG}
            width={rootSize.width}
            height={rootSize.height}
            {viewBox}
            overflow="visible"
        >
            <defs>
                {#each strokeDefs as def, index (index)}
                    <Markup markup={def.gradientOrPattern?.renderDefsElement()} />
                    <Markup markup={def.filter?.renderDefsElement()} />
                    <Markup markup={def.clipPath?.renderDefsElement()} />
                {/each}
            </defs>

            {#each strokeDefs as def, index (index)}
                {@const paint = ShapeLayerUtils.computePaint(def)}
                <path
                    d={`${paths[index].outerPath} ${paths[index].innerPath}`}
                    fill-rule="evenodd"
                    fill={paint.fill}
                    fill-opacity={paint.fillOpacity}
                    filter={paint.filter}
                    clip-path={paint.clipPath}
                    style:mix-blend-mode={paint.mixBlendMode}
                />
            {/each}
        </svg>
    {/if}
</div>

// components-solid/src/Exotics/Shape/Shape.tsx
import { For, createMemo, createSignal, onCleanup, onMount } from "solid-js";

import { ShapeLayerUtils, ShapeStyles as styles } from "@thewaver/ss-components";
import { Size2d } from "@thewaver/ss-utils";

import type { SVGDefs } from "../../Generators/SVGDefs/SVGDefsSolid.types";
import { access } from "../../Utils/propUtils";
import type { ShapeProps } from "./ShapeSolid.types";

const renderPath = (def: SVGDefs, getD: () => string, fillRule?: "evenodd") => {
    const paint = ShapeLayerUtils.computePaint(def);

    return (
        <path
            d={getD()}
            fill-rule={fillRule}
            fill={paint.fill}
            fill-opacity={paint.fillOpacity}
            filter={paint.filter}
            clip-path={paint.clipPath}
            style={paint.mixBlendMode ? { "mix-blend-mode": paint.mixBlendMode } : undefined}
        />
    );
};

export const Shape = (props: ShapeProps) => {
    const [getRootRef, setRootRef] = createSignal<HTMLElement>();
    const [getRootSize, setRootSize] = createSignal<Size2d>({ width: 0, height: 0 }, { equals: Size2d.isSame });

    const getFillDefs = createMemo(() => {
        return props.computeFillDefs?.(getRootSize, getRootRef);
    });

    const getStrokeDefs = createMemo(() => {
        return props.computeStrokeDefs?.(getRootSize, getRootRef);
    });

    const getPaths = createMemo(() =>
        ShapeLayerUtils.computeLayerPaths(
            props.computePoints(getRootSize()),
            getStrokeDefs(),
            access(props.strokeGeom),
            access(props.joinRadii),
            access(props.lameExponents),
        ),
    );

    const getShapeOutside = createMemo(() => ShapeLayerUtils.computeShapeOutside(getPaths()[0].outerContour));

    onMount(() => {
        let rootResizeObserver: ResizeObserver | undefined;

        onCleanup(() => {
            rootResizeObserver?.disconnect();
        });

        const rootRef = getRootRef();

        if (!rootRef) return;

        rootResizeObserver = new ResizeObserver(() => {
            setRootSize({ width: rootRef.offsetWidth, height: rootRef.offsetHeight });
        });
        rootResizeObserver.observe(rootRef);
    });

    return (
        <div ref={setRootRef} class={styles.shapeRoot} style={{ "shape-outside": getShapeOutside() }}>
            {getFillDefs() && (
                <svg
                    class={styles.shapeFillSVG}
                    width={getRootSize().width}
                    height={getRootSize().height}
                    viewBox={`0 0 ${getRootSize().width} ${getRootSize().height}`}
                    overflow="visible"
                >
                    <defs>
                        <For each={getFillDefs()}>
                            {(def) => (
                                <>
                                    {def.gradientOrPattern?.renderDefsElement()}
                                    {def.filter?.renderDefsElement()}
                                    {def.clipPath?.renderDefsElement()}
                                </>
                            )}
                        </For>
                    </defs>

                    <For each={getFillDefs()}>{(def) => renderPath(def, () => getPaths()[0].outerPath)}</For>
                </svg>
            )}

            {props.renderChildren(
                getRootSize,
                () => getPaths()[0].outerPath,
                () => getPaths()[0].outerPoints,
            )}

            {getStrokeDefs() && (
                <svg
                    class={styles.shapeStrokeSVG}
                    width={getRootSize().width}
                    height={getRootSize().height}
                    viewBox={`0 0 ${getRootSize().width} ${getRootSize().height}`}
                    overflow="visible"
                >
                    <defs>
                        <For each={getStrokeDefs()}>
                            {(def) => (
                                <>
                                    {def.gradientOrPattern?.renderDefsElement()}
                                    {def.filter?.renderDefsElement()}
                                    {def.clipPath?.renderDefsElement()}
                                </>
                            )}
                        </For>
                    </defs>

                    <For each={getStrokeDefs()}>
                        {(def, getIndex) =>
                            renderPath(
                                def,
                                () => `${getPaths()[getIndex()].outerPath} ${getPaths()[getIndex()].innerPath}`,
                                "evenodd",
                            )
                        }
                    </For>
                </svg>
            )}
        </div>
    );
};
