// playground-react/src/App/Pages/PreviewPage/Examples/Scrolled.tsx
import * as styles from "@thewaver/ss-playground/App/Pages/PreviewPage/PreviewPage.css";

import type { PreviewExampleProps } from "../PreviewPage.types";
import { TextExample } from "./Text";

const AFTERWARDS = [
    "The rest of the page carries on below, which is the whole of the problem.",
    "Open the preview, read to the end of it, and close it again: everything under it jumps up by the height that just disappeared, and the control you pressed goes with it.",
    "With the scroll asked for, the box comes back to where you were standing.",
];

type Props = PreviewExampleProps;

export const ScrolledExample = (props: Props) => {
    return (
        <div className={styles.scrollBox} data-scroll-box="">
            <TextExample
                expanded={props.expanded}
                collapsedHeight={props.collapsedHeight}
                isScrolledIntoViewOnCollapse={true}
                paragraphs={props.paragraphs}
            />

            <div className={styles.afterwards}>
                {AFTERWARDS.map((paragraph) => (
                    <div key={paragraph}>{paragraph}</div>
                ))}
            </div>
        </div>
    );
};

// playground-solid/src/App/Pages/PreviewPage/Examples/Scrolled.tsx
import { For } from "solid-js";

import * as styles from "@thewaver/ss-playground/App/Pages/PreviewPage/PreviewPage.css";

import type { PreviewExampleProps } from "../PreviewPage.types";
import { TextExample } from "./Text";

const AFTERWARDS = [
    "The rest of the page carries on below, which is the whole of the problem.",
    "Open the preview, read to the end of it, and close it again: everything under it jumps up by the height that just disappeared, and the control you pressed goes with it.",
    "With the scroll asked for, the box comes back to where you were standing.",
];

type Props = PreviewExampleProps;

export const ScrolledExample = (props: Props) => {
    return (
        <div class={styles.scrollBox} data-scroll-box>
            <TextExample
                expanded={props.expanded}
                collapsedHeight={props.collapsedHeight}
                isScrolledIntoViewOnCollapse={true}
                paragraphs={props.paragraphs}
            />

            <div class={styles.afterwards}>
                <For each={AFTERWARDS}>{(paragraph) => <div>{paragraph}</div>}</For>
            </div>
        </div>
    );
};
