// playground-react/src/App/Pages/PreviewPage/Examples/Text.tsx
import { Preview } from "@thewaver/ss-components-react";
import * as styles from "@thewaver/ss-playground/App/Pages/PreviewPage/PreviewPage.css";

import { PageButtonContent } from "../../../StyledComponents/ButtonContent/ButtonContent";
import type { PreviewExampleProps } from "../PreviewPage.types";

type Props = PreviewExampleProps;

export const TextExample = (props: Props) => {
    return (
        <div className={styles.panel}>
            <Preview
                expanded={props.expanded}
                collapsedHeight={props.collapsedHeight}
                isScrolledIntoViewOnCollapse={props.isScrolledIntoViewOnCollapse}
                renderContent={() => (
                    <div className={styles.paragraphs}>
                        {props.paragraphs.map((paragraph) => (
                            <div key={paragraph}>{paragraph}</div>
                        ))}
                    </div>
                )}
                renderOverlay={(visibilityTarget, transitionDurationMs) => (
                    <div
                        className={styles.fade}
                        style={{
                            opacity: visibilityTarget,
                            transition: `opacity ${transitionDurationMs}ms`,
                        }}
                    />
                )}
                renderTrigger={(flags) => (
                    <PageButtonContent flags={flags}>{flags.isExpanded ? "Show less" : "Read more"}</PageButtonContent>
                )}
            />
        </div>
    );
};

// playground-solid/src/App/Pages/PreviewPage/Examples/Text.tsx
import { For } from "solid-js";

import { Preview, access } from "@thewaver/ss-components-solid";
import * as styles from "@thewaver/ss-playground/App/Pages/PreviewPage/PreviewPage.css";

import { PageButtonContent } from "../../../StyledComponents/ButtonContent/ButtonContent";
import type { PreviewExampleProps } from "../PreviewPage.types";

type Props = PreviewExampleProps;

export const TextExample = (props: Props) => {
    return (
        <div class={styles.panel}>
            <Preview
                expanded={props.expanded}
                collapsedHeight={props.collapsedHeight}
                isScrolledIntoViewOnCollapse={props.isScrolledIntoViewOnCollapse}
                renderContent={() => (
                    <div class={styles.paragraphs}>
                        <For each={access(props.paragraphs)}>{(paragraph) => <div>{paragraph}</div>}</For>
                    </div>
                )}
                renderOverlay={(getVisibilityTarget, getTransitionDurationMs) => (
                    <div
                        class={styles.fade}
                        style={{
                            opacity: getVisibilityTarget(),
                            transition: `opacity ${getTransitionDurationMs()}ms`,
                        }}
                    />
                )}
                renderTrigger={(getFlags) => (
                    <PageButtonContent flags={getFlags}>
                        {getFlags().isExpanded ? "Show less" : "Read more"}
                    </PageButtonContent>
                )}
            />
        </div>
    );
};
