// components-svelte/src/Exotics/Trail/Trail.svelte
<script lang="ts">
    import { untrack } from "svelte";

    import { TRAIL_DEFAULTS, TrailUtils, TrailStyles as styles } from "@thewaver/ss-components";
    import { MathUtils } from "@thewaver/ss-utils";

    import { InteractionTrackerSvelteUtils } from "../../Abstracts/InteractionTracker/InteractionTrackerSvelte.utils.svelte.js";
    import type { TrailController, TrailProps } from "./Trail.types.js";

    const NO_LENGTH = 0;
    const NO_PROGRESS = 0;
    const NO_OFFSET = 0;

    let { progress = $bindable(NO_PROGRESS), playback = $bindable(true), ...props }: TrailProps = $props();

    let path = $state<SVGPathElement>();
    let pathLength = $state(NO_LENGTH);

    const getIsPageHidden = InteractionTrackerSvelteUtils.trackPageHidden();

    const durationMs = $derived(props.durationMs ?? TRAIL_DEFAULTS.durationMs);
    const isLooping = $derived(props.isLooping ?? false);
    const isTurning = $derived(props.isTurning ?? false);
    const isDisabled = $derived(props.isDisabled ?? false);
    const followerOffsets = $derived(props.followerOffsets ?? TRAIL_DEFAULTS.followerOffsets);
    const runExtent = $derived(TrailUtils.getRunExtent(followerOffsets, isLooping));

    const isRunning = $derived(playback && !isDisabled && !getIsPageHidden() && pathLength > NO_LENGTH);

    $effect(() => {
        const element = path;

        void props.path;

        pathLength = element ? element.getTotalLength() : NO_LENGTH;
    });

    const computePlace = (offset: number) =>
        TrailUtils.computePlace(
            path ?? undefined,
            pathLength,
            TrailUtils.getTravelerProgress(progress, offset, runExtent, isLooping),
        );

    const places = $derived(followerOffsets.map(computePlace));
    const place = $derived(computePlace(NO_OFFSET));

    const controller: TrailController = {
        getPlace: () => place,
        getIsPlaying: () => playback,
        seek: (target: number) => {
            const next = MathUtils.clamp01(target);

            if (next === progress) return false;

            progress = next;

            return true;
        },
    };

    $effect(() => {
        untrack(() => props.onMount?.(controller));
    });

    $effect(() => {
        if (!isRunning) return;

        return untrack(() =>
            TrailUtils.run({
                getProgress: () => progress,
                setProgress: (value) => {
                    progress = value;
                },
                getRunDurationMs: () => durationMs * runExtent,
                getIsLooping: () => isLooping,
                onLap: () => props.onLap?.(),
                onEnd: () => {
                    playback = false;
                },
            }),
        );
    });
</script>

<div class={styles.trailRoot} style:width={`${props.size.width}px`} style:height={`${props.size.height}px`}>
    <svg class={styles.trailTrack} viewBox={`0 0 ${props.size.width} ${props.size.height}`} aria-hidden="true">
        <path bind:this={path} class={styles.trailPath} d={props.path} />

        {@render props.renderTrack?.(props.path)}
    </svg>

    {#each places as travelerPlace, index (index)}
        <div class={styles.trailTraveler} style:transform={TrailUtils.getTravelerTransform(travelerPlace, isTurning)}>
            {@render props.renderTraveler(travelerPlace, index)}
        </div>
    {/each}
</div>

// components-react/src/Exotics/Trail/Trail.tsx
import { useEffect, useLayoutEffect, useRef, useState } from "react";

import { TRAIL_DEFAULTS, type TrailPlace, TrailStyles, TrailUtils } from "@thewaver/ss-components";
import { MathUtils, StoreUtils } from "@thewaver/ss-utils";

import { InteractionTrackerReactUtils } from "../../Abstracts/InteractionTracker/InteractionTrackerReact.utils";
import { SignalMirrorReactUtils } from "../../Abstracts/SignalMirror/SignalMirrorReact.utils";
import { useLatest } from "../../Utils/refUtils";
import type { TrailController, TrailProps } from "./Trail.types";

const NO_LENGTH = 0;
const NO_PROGRESS = 0;
const NO_OFFSET = 0;

type TrailSnapshot = {
    place: TrailPlace;
    isPlaying: boolean;
};

const getIsSameSnapshot = (a: TrailSnapshot, b: TrailSnapshot) =>
    a.isPlaying === b.isPlaying &&
    a.place.progress === b.place.progress &&
    a.place.angle === b.place.angle &&
    a.place.point.x === b.place.point.x &&
    a.place.point.y === b.place.point.y;

export const Trail = (props: TrailProps) => {
    const [progress, setProgressState] = SignalMirrorReactUtils.useOptionalState(props.progress, NO_PROGRESS);
    const [isPlaying, setIsPlaying] = SignalMirrorReactUtils.useOptionalState(props.playback, true);

    const pathRef = useRef<SVGPathElement | null>(null);
    const [pathLength, setPathLength] = useState(NO_LENGTH);

    const isPageHidden = InteractionTrackerReactUtils.usePageHidden();

    const durationMs = props.durationMs ?? TRAIL_DEFAULTS.durationMs;
    const isLooping = props.isLooping ?? false;
    const isTurning = props.isTurning ?? false;
    const isDisabled = props.isDisabled ?? false;
    const followerOffsets = props.followerOffsets ?? TRAIL_DEFAULTS.followerOffsets;
    const runExtent = TrailUtils.getRunExtent(followerOffsets, isLooping);

    const isRunning = isPlaying && !isDisabled && !isPageHidden && pathLength > NO_LENGTH;

    const progressRef = useLatest(progress);

    const setProgress = (value: number) => {
        progressRef.current = value;
        setProgressState(value);
    };

    const latest = useLatest({ props, durationMs, runExtent, isLooping, setProgress, setIsPlaying });

    useLayoutEffect(() => {
        setPathLength(pathRef.current ? pathRef.current.getTotalLength() : NO_LENGTH);
    }, [props.path]);

    const computePlace = (offset: number) =>
        TrailUtils.computePlace(
            pathRef.current ?? undefined,
            pathLength,
            TrailUtils.getTravelerProgress(progress, offset, runExtent, isLooping),
        );

    const places = followerOffsets.map(computePlace);
    const snapshot: TrailSnapshot = { place: computePlace(NO_OFFSET), isPlaying };

    const [controllerStore] = useState(() => StoreUtils.create(snapshot, { isEqual: getIsSameSnapshot }));

    useLayoutEffect(() => {
        controllerStore.set(snapshot);
    });

    const [controller] = useState<TrailController>(() => ({
        getPlace: () => controllerStore.get().place,
        getIsPlaying: () => controllerStore.get().isPlaying,
        seek: (target: number) => {
            const next = MathUtils.clamp01(target);

            if (next === progressRef.current) return false;

            latest.current.setProgress(next);

            return true;
        },
        subscribe: controllerStore.subscribe,
    }));

    useEffect(() => {
        latest.current.props.onMount?.(controller);
    }, [controller]);

    useEffect(() => {
        if (!isRunning) return;

        return TrailUtils.run({
            getProgress: () => progressRef.current,
            setProgress: (value) => latest.current.setProgress(value),
            getRunDurationMs: () => latest.current.durationMs * latest.current.runExtent,
            getIsLooping: () => latest.current.isLooping,
            onLap: () => latest.current.props.onLap?.(),
            onEnd: () => latest.current.setIsPlaying(false),
        });
    }, [isRunning]);

    return (
        <div
            className={TrailStyles.trailRoot}
            style={{ width: `${props.size.width}px`, height: `${props.size.height}px` }}
        >
            <svg
                className={TrailStyles.trailTrack}
                viewBox={`0 0 ${props.size.width} ${props.size.height}`}
                aria-hidden="true"
            >
                <path ref={pathRef} className={TrailStyles.trailPath} d={props.path} />

                {props.renderTrack?.(props.path)}
            </svg>

            {places.map((place, index) => (
                <div
                    key={index}
                    className={TrailStyles.trailTraveler}
                    style={{ transform: TrailUtils.getTravelerTransform(place, isTurning) }}
                >
                    {props.renderTraveler(place, index)}
                </div>
            ))}
        </div>
    );
};
