// playground-react/src/App/StyledComponents/LabelCaption/LabelCaption.tsx
import type { PropsWithChildren } from "react";

import * as styles from "@thewaver/ss-playground-core/App/StyledComponents/LabelCaption/LabelCaption.css";

import type { PageLabelCaptionProps } from "./LabelCaption.types";

export const PageLabelCaption = (props: PropsWithChildren<PageLabelCaptionProps>) => {
    return (
        <div className={styles.labelCaption} id={props.id}>
            {props.children}
        </div>
    );
};

// playground-solid/src/App/StyledComponents/LabelCaption/LabelCaption.tsx
import type { ParentProps } from "solid-js";

import { access } from "@thewaver/ss-components-solid";
import * as styles from "@thewaver/ss-playground-core/App/StyledComponents/LabelCaption/LabelCaption.css";

import type { PageLabelCaptionProps } from "./LabelCaption.types";

export const PageLabelCaption = (props: ParentProps<PageLabelCaptionProps>) => {
    return (
        <div class={styles.labelCaption} id={access(props.id)}>
            {props.children}
        </div>
    );
};
