// playground-solid/src/App/StyledComponents/SelectGroupContent/SelectGroupContent.tsx
import type { ParentProps } from "solid-js";
import { Show } from "solid-js";

import { access } from "@thewaver/ss-components-solid";
import type { SelectGroupFlags } from "@thewaver/ss-components-solid";
import * as styles from "@thewaver/ss-playground-core/App/StyledComponents/SelectGroupContent/SelectGroupContent.css";

import { useLayerClass } from "../Layer/Layer.context";
import type { SelectGroupContentProps } from "./SelectGroupContent.types";

const CHECKED_MARK = "✓";
const MIXED_MARK = "–";

export const PageSelectGroupContent = (props: ParentProps<SelectGroupContentProps>) => {
    const getLayerClass = useLayerClass();

    const getFlags = () => (props.flags === undefined ? undefined : access(props.flags));

    return (
        <div
            class={[styles.selectGroupContent, getLayerClass()].join(" ")}
            data-checked-state={getFlags() === undefined ? undefined : String(getFlags()!.checkedState)}
            aria-hidden="true"
        >
            <Show when={getFlags()}>
                {(getGroupFlags: () => SelectGroupFlags) => (
                    <div
                        class={styles.selectGroupMark}
                        classList={{
                            [styles.isChecked]: getGroupFlags().checkedState === true,
                            [styles.isMixed]: getGroupFlags().checkedState === "mixed",
                        }}
                    >
                        {getGroupFlags().checkedState === "mixed" ? MIXED_MARK : CHECKED_MARK}
                    </div>
                )}
            </Show>

            {props.children}
        </div>
    );
};

// playground-react/src/App/StyledComponents/SelectGroupContent/SelectGroupContent.tsx
import type { PropsWithChildren } from "react";

import * as styles from "@thewaver/ss-playground-core/App/StyledComponents/SelectGroupContent/SelectGroupContent.css";

import { useLayerClass } from "../Layer/Layer.context";
import type { SelectGroupContentProps } from "./SelectGroupContent.types";

const CHECKED_MARK = "✓";
const MIXED_MARK = "–";

export const PageSelectGroupContent = (props: PropsWithChildren<SelectGroupContentProps>) => {
    const layerClass = useLayerClass();

    const flags = props.flags;

    return (
        <div
            className={[styles.selectGroupContent, layerClass].join(" ")}
            data-checked-state={flags === undefined ? undefined : String(flags.checkedState)}
            aria-hidden="true"
        >
            {flags && (
                <div
                    className={[
                        styles.selectGroupMark,
                        flags.checkedState === true && styles.isChecked,
                        flags.checkedState === "mixed" && styles.isMixed,
                    ]
                        .filter(Boolean)
                        .join(" ")}
                >
                    {flags.checkedState === "mixed" ? MIXED_MARK : CHECKED_MARK}
                </div>
            )}

            {props.children}
        </div>
    );
};
