// playground-solid/src/App/Pages/ListboxPage/Examples/Glide.tsx
import { Listbox } from "@thewaver/ss-components-solid";

import { PageGlideFloater, PageGlideLabel } from "../../../StyledComponents/GlideFloater/GlideFloater";
import { PageListboxSurface } from "../../../StyledComponents/ListboxSurface/ListboxSurface";
import { COUNTRIES_WITH_REACHABLE } from "../../SelectPage/SelectPage.const";
import type { ListboxExampleProps } from "../ListboxPage.types";

type Props = ListboxExampleProps;

export const GlideExample = (props: Props) => (
    <PageListboxSurface>
        <Listbox
            value={props.value}
            options={() => COUNTRIES_WITH_REACHABLE}
            ariaLabel={"Shipping country, gliding"}
            renderOption={(getOption, getFlags) => (
                <PageGlideLabel
                    isSelected={() => getFlags().isSelected}
                    isDisabled={() => getFlags().isDisabled ?? false}
                >
                    {getOption().value}
                </PageGlideLabel>
            )}
            renderSelectionFloater={(getVisibilityTarget, getTransitionDurationMs) => (
                <PageGlideFloater
                    kind={"selection"}
                    visibilityTarget={getVisibilityTarget}
                    transitionDurationMs={getTransitionDurationMs}
                />
            )}
            renderHighlightFloater={(getVisibilityTarget, getTransitionDurationMs) => (
                <PageGlideFloater
                    kind={"highlight"}
                    visibilityTarget={getVisibilityTarget}
                    transitionDurationMs={getTransitionDurationMs}
                />
            )}
        />
    </PageListboxSurface>
);

// playground-svelte/src/App/Pages/ListboxPage/Examples/Glide.svelte
<script lang="ts">
    import { Listbox } from "@thewaver/ss-components-svelte";

    import PageGlideFloater from "../../../StyledComponents/GlideFloater/PageGlideFloater.svelte";
    import PageGlideLabel from "../../../StyledComponents/GlideFloater/PageGlideLabel.svelte";
    import PageListboxSurface from "../../../StyledComponents/ListboxSurface/ListboxSurface.svelte";
    import { COUNTRIES_WITH_REACHABLE } from "../../SelectPage/SelectPage.const.svelte";
    import type { ListboxExampleProps } from "../ListboxPage.types";

    type Props = ListboxExampleProps;

    let { value = $bindable() }: Props = $props();
</script>

<PageListboxSurface>
    <Listbox bind:value options={COUNTRIES_WITH_REACHABLE} ariaLabel={"Shipping country, gliding"}>
        {#snippet renderOption(option, flags)}
            <PageGlideLabel isSelected={flags.isSelected} isDisabled={flags.isDisabled ?? false}>
                {option.value}
            </PageGlideLabel>
        {/snippet}

        {#snippet renderSelectionFloater(visibilityTarget, transitionDurationMs)}
            <PageGlideFloater kind={"selection"} {visibilityTarget} {transitionDurationMs} />
        {/snippet}

        {#snippet renderHighlightFloater(visibilityTarget, transitionDurationMs)}
            <PageGlideFloater kind={"highlight"} {visibilityTarget} {transitionDurationMs} />
        {/snippet}
    </Listbox>
</PageListboxSurface>
