// playground-svelte/src/App/Pages/TypewriterPage/Examples/Phrases.svelte
<script lang="ts">
    import { Button, MediaQueryMonitorSvelteUtils, Typewriter } from "@thewaver/ss-components-svelte";
    import type { TypewriterMode } from "@thewaver/ss-components-svelte";
    import { MEASURE_BOX_PADDING } from "@thewaver/ss-playground/App/PageComponents/MeasureBox/MeasureBox.css";
    import * as styles from "@thewaver/ss-playground/App/Pages/TypewriterPage/TypewriterPage.css";
    import { CONTROL_GLYPHS } from "@thewaver/ss-playground/App/StyledComponents/ControlButtonContent/ControlButtonContent.const";

    import PageMeasureBox from "../../../PageComponents/MeasureBox/MeasureBox.svelte";
    import PageControlButtonContent from "../../../StyledComponents/ControlButtonContent/ControlButtonContent.svelte";
    import type { TypewriterPhrasesExampleProps } from "../TypewriterPage.types";

    const LEAD = "We build";
    const PHRASES = ["websites", "apps", "games"];
    const FIRST_PHRASE = 0;
    const HOLD_MS = 1600;
    const CHARACTER_DELAY_MS = 80;
    const CHARACTER_DURATION_MS = 200;
    const NO_MOTION_MS = 0;

    type Props = TypewriterPhrasesExampleProps;

    let props: Props = $props();

    let phraseIndex = $state(FIRST_PHRASE);
    let mode = $state<TypewriterMode>("type");
    let isPaused = $state(false);

    const getPrefersReducedMotion = MediaQueryMonitorSvelteUtils.createReducedMotion();

    let holdTimeout: ReturnType<typeof setTimeout> | undefined;
    let isStepWaiting = false;

    $effect(() => () => clearTimeout(holdTimeout));

    const step = () => {
        isStepWaiting = false;

        if (mode === "type") {
            mode = "erase";

            return;
        }

        phraseIndex = (phraseIndex + 1) % PHRASES.length;
        mode = "type";
    };

    const requestStep = () => {
        if (isPaused) {
            isStepWaiting = true;

            return;
        }

        step();
    };

    const handleAnimationEnd = () => {
        clearTimeout(holdTimeout);

        if (mode === "erase") {
            requestStep();

            return;
        }

        holdTimeout = setTimeout(requestStep, HOLD_MS);
    };

    const togglePause = () => {
        isPaused = !isPaused;

        if (!isPaused && isStepWaiting) step();
    };
</script>

<div class={styles.phraseStack}>
    <PageMeasureBox width={props.width} padding={MEASURE_BOX_PADDING}>
        <div class={styles.phraseLine}>
            <span>{LEAD}</span>

            <div class={styles.phraseSlot}>
                <Typewriter
                    {mode}
                    computeAnimationName={props.computeAnimationName}
                    animationDelayMs={getPrefersReducedMotion() ? NO_MOTION_MS : CHARACTER_DELAY_MS}
                    animationDurationMs={getPrefersReducedMotion() ? NO_MOTION_MS : CHARACTER_DURATION_MS}
                    computeCharacterWeights={props.computeCharacterWeights}
                    onAnimationEnd={handleAnimationEnd}
                >
                    {PHRASES[phraseIndex]}

                    {#snippet renderCaret()}
                        <span
                            class={[
                                styles.phraseCaret,
                                !isPaused && !getPrefersReducedMotion() && styles.phraseCaretBlinking,
                            ]}
                            aria-hidden="true"
                        ></span>
                    {/snippet}
                </Typewriter>
            </div>
        </div>
    </PageMeasureBox>

    <Button
        id={"pausePhrases"}
        ariaLabel={isPaused ? "Resume" : "Pause"}
        onClick={() => {
            togglePause();
        }}
    >
        {#snippet renderContent(flags)}
            <PageControlButtonContent {flags} glyph={isPaused ? CONTROL_GLYPHS.play : CONTROL_GLYPHS.pause} />
        {/snippet}
    </Button>
</div>

// playground-vue/src/App/Pages/TypewriterPage/Examples/Phrases.vue
<script setup lang="ts">
import { onBeforeUnmount, shallowRef } from "vue";

import { Button, MediaQueryMonitorVueUtils, Typewriter } from "@thewaver/ss-components-vue";
import type { TypewriterMode } from "@thewaver/ss-components-vue";
import { MEASURE_BOX_PADDING } from "@thewaver/ss-playground/App/PageComponents/MeasureBox/MeasureBox.css";
import * as styles from "@thewaver/ss-playground/App/Pages/TypewriterPage/TypewriterPage.css";
import { CONTROL_GLYPHS } from "@thewaver/ss-playground/App/StyledComponents/ControlButtonContent/ControlButtonContent.const";

import PageMeasureBox from "../../../PageComponents/MeasureBox/MeasureBox.vue";
import PageControlButtonContent from "../../../StyledComponents/ControlButtonContent/ControlButtonContent.vue";
import type { TypewriterPhrasesExampleProps } from "../TypewriterPage.types";

const LEAD = "We build";
const PHRASES = ["websites", "apps", "games"];
const FIRST_PHRASE = 0;
const HOLD_MS = 1600;
const CHARACTER_DELAY_MS = 80;
const CHARACTER_DURATION_MS = 200;
const NO_MOTION_MS = 0;

type Props = TypewriterPhrasesExampleProps;

defineProps<Props>();

const phraseIndex = shallowRef(FIRST_PHRASE);
const mode = shallowRef<TypewriterMode>("type");
const isPaused = shallowRef(false);

const prefersReducedMotion = MediaQueryMonitorVueUtils.useReducedMotion();

let holdTimeout: ReturnType<typeof setTimeout> | undefined;
let isStepWaiting = false;

onBeforeUnmount(() => clearTimeout(holdTimeout));

const step = () => {
    isStepWaiting = false;

    if (mode.value === "type") {
        mode.value = "erase";

        return;
    }

    phraseIndex.value = (phraseIndex.value + 1) % PHRASES.length;
    mode.value = "type";
};

const requestStep = () => {
    if (isPaused.value) {
        isStepWaiting = true;

        return;
    }

    step();
};

const handleAnimationEnd = () => {
    clearTimeout(holdTimeout);

    if (mode.value === "erase") {
        requestStep();

        return;
    }

    holdTimeout = setTimeout(requestStep, HOLD_MS);
};

const togglePause = () => {
    isPaused.value = !isPaused.value;

    if (!isPaused.value && isStepWaiting) step();
};
</script>

<template>
    <div :class="styles.phraseStack">
        <PageMeasureBox :width="width" :padding="MEASURE_BOX_PADDING">
            <div :class="styles.phraseLine">
                <span>{{ LEAD }}</span>

                <div :class="styles.phraseSlot">
                    <Typewriter
                        :mode="mode"
                        :compute-animation-name="computeAnimationName"
                        :animation-delay-ms="prefersReducedMotion ? NO_MOTION_MS : CHARACTER_DELAY_MS"
                        :animation-duration-ms="prefersReducedMotion ? NO_MOTION_MS : CHARACTER_DURATION_MS"
                        :compute-character-weights="computeCharacterWeights"
                        @animation-end="handleAnimationEnd"
                    >
                        <template #default>{{ PHRASES[phraseIndex] }}</template>

                        <template #renderCaret>
                            <span
                                :class="[
                                    styles.phraseCaret,
                                    !isPaused && !prefersReducedMotion && styles.phraseCaretBlinking,
                                ]"
                                aria-hidden="true"
                            />
                        </template>
                    </Typewriter>
                </div>
            </div>
        </PageMeasureBox>

        <Button id="pausePhrases" :ariaLabel="isPaused ? 'Resume' : 'Pause'" @click="togglePause">
            <template #renderContent="flags">
                <PageControlButtonContent
                    :flags="flags"
                    :glyph="isPaused ? CONTROL_GLYPHS.play : CONTROL_GLYPHS.pause"
                />
            </template>
        </Button>
    </div>
</template>
