// playground-vue/src/App/Pages/ListboxPage/Examples/Grouped.vue
<script setup lang="ts">
import { useModel } from "vue";

import { MultiListbox } from "@thewaver/ss-components-vue";

import PageListboxSurface from "../../../StyledComponents/ListboxSurface/ListboxSurface.vue";
import PageSelectGroupContent from "../../../StyledComponents/SelectGroupContent/SelectGroupContent.vue";
import PageSelectOptionContent from "../../../StyledComponents/SelectOptionContent/SelectOptionContent.vue";
import { GROUPED_COUNTRIES } from "../../SelectPage/SelectPage.const";
import type { MultiListboxExampleProps } from "../ListboxPage.types";

type Props = MultiListboxExampleProps;

const props = defineProps<Props>();

const values = useModel(props, "values");
</script>

<template>
    <PageListboxSurface>
        <MultiListbox v-model:values="values" :options="GROUPED_COUNTRIES" ariaLabel="Countries to ship to">
            <template #renderGroup="{ group, flags }">
                <PageSelectGroupContent :flags="flags">{{ group.label }}</PageSelectGroupContent>
            </template>

            <template #renderOption="{ option, flags }">
                <PageSelectOptionContent :flags="flags">{{ option.value }}</PageSelectOptionContent>
            </template>
        </MultiListbox>
    </PageListboxSurface>
</template>

// playground-react/src/App/Pages/ListboxPage/Examples/Grouped.tsx
import { MultiListbox } from "@thewaver/ss-components-react";

import { PageListboxSurface } from "../../../StyledComponents/ListboxSurface/ListboxSurface";
import { PageSelectGroupContent } from "../../../StyledComponents/SelectGroupContent/SelectGroupContent";
import { PageSelectOptionContent } from "../../../StyledComponents/SelectOptionContent/SelectOptionContent";
import { GROUPED_COUNTRIES } from "../../SelectPage/SelectPage.const";
import type { MultiListboxExampleProps } from "../ListboxPage.types";

type Props = MultiListboxExampleProps;

export const GroupedExample = (props: Props) => (
    <PageListboxSurface>
        <MultiListbox
            values={props.values}
            options={GROUPED_COUNTRIES}
            ariaLabel={"Countries to ship to"}
            renderGroup={(group, flags) => <PageSelectGroupContent flags={flags}>{group.label}</PageSelectGroupContent>}
            renderOption={(option, flags) => (
                <PageSelectOptionContent flags={flags}>{option.value}</PageSelectOptionContent>
            )}
        />
    </PageListboxSurface>
);
