// playground-vue/src/App/Pages/DiePage/Examples/Tabletop.vue
<script setup lang="ts">
import { computed, shallowRef, useModel } from "vue";

import { Button, Die } from "@thewaver/ss-components-vue";
import type { DieController } from "@thewaver/ss-components-vue";
import * as styles from "@thewaver/ss-playground/App/Pages/DiePage/DiePage.css";

import PageButtonContent from "../../../StyledComponents/ButtonContent/ButtonContent.vue";
import PageDieFace from "../../../StyledComponents/DieContent/DieContent.vue";
import type { DieExampleProps } from "../DiePage.types";

const FIRST_NUMBER = 1;

type Props = DieExampleProps;

const props = defineProps<Props>();

const face = useModel(props, "face");

const controller = shallowRef<DieController>();

const isRolling = computed(() => controller.value?.getIsRolling() ?? true);

const computeFaceLabel = (index: number) => `${index + FIRST_NUMBER}`;

const computeRollTarget = () => Math.floor(Math.random() * props.shape.faces.length);

const roll = () => {
    controller.value?.roll();
};
</script>

<template>
    <div :class="styles.stage">
        <Die
            v-model:face="face"
            :shape="shape"
            :size="size"
            :roll-duration-ms="rollDurationMs"
            :tumble-count="tumbleCount"
            ariaLabel="A die"
            :compute-face-label="computeFaceLabel"
            :compute-roll-target="computeRollTarget"
            @mount="(next: DieController) => (controller = next)"
        >
            <template #renderFace="{ index, state }">
                <PageDieFace :state="state" :label="`${index + FIRST_NUMBER}`" />
            </template>
        </Die>

        <Button id="dieRoll" :is-disabled="isRolling" @click="roll">
            <template #renderContent="flags">
                <PageButtonContent :flags="flags">Roll</PageButtonContent>
            </template>
        </Button>
    </div>
</template>

// playground-svelte/src/App/Pages/DiePage/Examples/Tabletop.svelte
<script lang="ts">
    import { Button, Die } from "@thewaver/ss-components-svelte";
    import type { DieController } from "@thewaver/ss-components-svelte";
    import * as styles from "@thewaver/ss-playground/App/Pages/DiePage/DiePage.css";

    import PageButtonContent from "../../../StyledComponents/ButtonContent/ButtonContent.svelte";
    import PageDieFace from "../../../StyledComponents/DieContent/DieContent.svelte";
    import type { DieExampleProps } from "../DiePage.types";

    const FIRST_NUMBER = 1;

    type Props = DieExampleProps;

    let { face = $bindable(), ...props }: Props = $props();

    let controller = $state.raw<DieController>();

    const isRolling = $derived(controller?.getIsRolling() ?? true);
</script>

<div class={styles.stage}>
    <Die
        shape={props.shape}
        size={props.size}
        rollDurationMs={props.rollDurationMs}
        tumbleCount={props.tumbleCount}
        bind:face
        ariaLabel={"A die"}
        computeFaceLabel={(index) => `${index + FIRST_NUMBER}`}
        computeRollTarget={() => Math.floor(Math.random() * props.shape.faces.length)}
        onMount={(next) => {
            controller = next;
        }}
    >
        {#snippet renderFace(index, state)}
            <PageDieFace {state} label={`${index + FIRST_NUMBER}`} />
        {/snippet}
    </Die>

    <Button
        id={"dieRoll"}
        isDisabled={isRolling}
        onClick={() => {
            controller?.roll();
        }}
    >
        {#snippet renderContent(flags)}
            <PageButtonContent {flags}>Roll</PageButtonContent>
        {/snippet}
    </Button>
</div>
