// components-solid/src/Essentials/Input/MultiSelect/MultiSelect.tsx
import { createMemo } from "solid-js";

import { SelectUtils, SelectionUtils } from "@thewaver/ss-components";

import { access, accessSignal } from "../../../Utils/propUtils";
import { SelectComposite } from "../Select/Select";
import type { MultiSelectProps } from "./MultiSelectSolid.types";

export const MultiSelect = <T,>(props: MultiSelectProps<T>) => {
    const valuesSignal = accessSignal(() => props.values);

    const getSelectedOptions = createMemo(() => {
        const selectedValues = valuesSignal[0]();

        return SelectUtils.getFlatOptions(access(props.options)).filter((option) =>
            selectedValues.includes(option.value),
        );
    });

    return (
        <SelectComposite
            {...props}
            isMultiple={true}
            selectedOptions={getSelectedOptions}
            computeIsSelected={(value) => valuesSignal[0]().includes(value)}
            renderContent={props.renderContent}
            onPick={(value) => {
                const nextValues = SelectionUtils.getToggled(valuesSignal[0](), value);

                valuesSignal[1](() => nextValues);

                void props.onSelectionChange?.(nextValues);
            }}
            onClear={() => {
                if (valuesSignal[0]().length < 1) return;

                valuesSignal[1](() => []);

                void props.onSelectionChange?.([]);
            }}
        />
    );
};

// components-react/src/Essentials/Input/MultiSelect/MultiSelect.tsx
import { useMemo } from "react";

import { SelectUtils, SelectionUtils } from "@thewaver/ss-components";

import { SelectComposite } from "../Select/Select";
import type { MultiSelectProps } from "./MultiSelect.types";

export const MultiSelect = <T,>(props: MultiSelectProps<T>) => {
    const [values, setValues] = props.values;

    const selectedOptions = useMemo(
        () => SelectUtils.getFlatOptions(props.options).filter((option) => values.includes(option.value)),
        [props.options, values],
    );

    return (
        <SelectComposite
            {...props}
            isMultiple={true}
            selectedOptions={selectedOptions}
            computeIsSelected={(value) => values.includes(value)}
            renderContent={props.renderContent}
            onPick={(value) => {
                const nextValues = SelectionUtils.getToggled(values, value);

                setValues(nextValues);

                props.onSelectionChange?.(nextValues);
            }}
            onClear={() => {
                if (values.length < 1) return;

                setValues([]);

                props.onSelectionChange?.([]);
            }}
        />
    );
};
