// playground/src/App/StyledComponents/AccordionContent/AccordionContent.tsx
import type { ParentProps } from "solid-js";

import { access } from "@thewaver/ss-components";

import { useLayerClass } from "../Layer/Layer.context";
import type { AccordionHeaderProps, AccordionPanelProps } from "./AccordionContent.types";

import * as styles from "./AccordionContent.css";

export const PageAccordionHeader = (props: ParentProps<AccordionHeaderProps>) => {
    const getLayerClass = useLayerClass();

    return (
        <div
            class={styles.accordionHeader}
            classList={{
                [getLayerClass()]: true,
                [styles.isExpanded]: access(props.flags).isExpanded,
                [styles.isHovered]: access(props.flags).isHovered,
                [styles.isDisabled]: access(props.flags).isDisabled,
            }}
        >
            <div>{props.children}</div>

            <div class={styles.accordionMarker} aria-hidden="true">
                ▶
            </div>
        </div>
    );
};

export const PageAccordionPanel = (props: ParentProps<AccordionPanelProps>) => {
    const getLayerClass = useLayerClass();

    return (
        <div
            class={[styles.accordionPanel, getLayerClass()].join(" ")}
            style={{
                opacity: access(props.visibilityTarget),
                transition: `opacity ${access(props.transitionDurationMs)}ms`,
            }}
        >
            {props.children}
        </div>
    );
};

// playground-react/src/App/StyledComponents/AccordionContent/AccordionContent.tsx
import type { PropsWithChildren } from "react";

import * as styles from "@thewaver/ss-playground/App/StyledComponents/AccordionContent/AccordionContent.css";

import { useLayerClass } from "../Layer/Layer.context";
import type { AccordionHeaderProps, AccordionPanelProps } from "./AccordionContent.types";

export const PageAccordionHeader = (props: PropsWithChildren<AccordionHeaderProps>) => {
    const layerClass = useLayerClass();

    return (
        <div
            className={[
                styles.accordionHeader,
                layerClass,
                props.flags.isExpanded && styles.isExpanded,
                props.flags.isHovered && styles.isHovered,
                props.flags.isDisabled && styles.isDisabled,
            ]
                .filter(Boolean)
                .join(" ")}
        >
            <div>{props.children}</div>

            <div className={styles.accordionMarker} aria-hidden="true">
                ▶
            </div>
        </div>
    );
};

export const PageAccordionPanel = (props: PropsWithChildren<AccordionPanelProps>) => {
    const layerClass = useLayerClass();

    return (
        <div
            className={[styles.accordionPanel, layerClass].join(" ")}
            style={{
                opacity: props.visibilityTarget,
                transition: `opacity ${props.transitionDurationMs}ms`,
            }}
        >
            {props.children}
        </div>
    );
};
