// playground-solid/src/App/StyledComponents/PopoverSurface/PopoverSurface.tsx
import type { ParentProps } from "solid-js";

import { access } from "@thewaver/ss-components-solid";
import * as styles from "@thewaver/ss-playground-core/App/StyledComponents/PopoverSurface/PopoverSurface.css";

import { useLayerClass } from "../Layer/Layer.context";
import type { PopoverSurfaceProps } from "./PopoverSurface.types";

export const PagePopoverSurface = (props: ParentProps<PopoverSurfaceProps>) => {
    const getLayerClass = useLayerClass();

    return (
        <div
            class={styles.popoverSurface}
            classList={{
                [getLayerClass()]: true,
                [styles.isVisible]: access(props.visibilityTarget) === 1,
                [styles.isFlipped]: access(props.placement).y === "top-out",
            }}
            style={{
                transition: `opacity ${access(props.transitionDurationMs)}ms, transform ${access(props.transitionDurationMs)}ms`,
            }}
        >
            {props.children}
        </div>
    );
};

// playground-react/src/App/StyledComponents/PopoverSurface/PopoverSurface.tsx
import type { PropsWithChildren } from "react";

import * as styles from "@thewaver/ss-playground-core/App/StyledComponents/PopoverSurface/PopoverSurface.css";

import { useLayerClass } from "../Layer/Layer.context";
import type { PopoverSurfaceProps } from "./PopoverSurface.types";

export const PagePopoverSurface = (props: PropsWithChildren<PopoverSurfaceProps>) => {
    const layerClass = useLayerClass();

    return (
        <div
            className={[
                styles.popoverSurface,
                layerClass,
                props.visibilityTarget === 1 && styles.isVisible,
                props.placement.y === "top-out" && styles.isFlipped,
            ]
                .filter(Boolean)
                .join(" ")}
            style={{
                transition: `opacity ${props.transitionDurationMs}ms, transform ${props.transitionDurationMs}ms`,
            }}
        >
            {props.children}
        </div>
    );
};
