// playground-react/src/App/StyledComponents/TimelineContent/TimelineContent.tsx
import * as styles from "@thewaver/ss-playground/App/StyledComponents/TimelineContent/TimelineContent.css";

import { useLayerClass } from "../Layer/Layer.context";
import type {
    PageTimelineBlockProps,
    PageTimelineFrameProps,
    PageTimelineLanesProps,
    PageTimelineMarkerProps,
    PageTimelineTickProps,
} from "./TimelineContent.types";

export const PageTimelineFrame = (props: PageTimelineFrameProps) => {
    const layerClass = useLayerClass();

    return <div className={[styles.timelineFrame, layerClass].join(" ")}>{props.children}</div>;
};

export const PageTimelineRow = (props: PageTimelineFrameProps) => {
    const layerClass = useLayerClass();

    return <div className={[styles.timelineRow, layerClass].join(" ")}>{props.children}</div>;
};

export const PageTimelineTrack = (props: PageTimelineFrameProps) => {
    const layerClass = useLayerClass();

    return <div className={[styles.timelineTrack, layerClass].join(" ")}>{props.children}</div>;
};

export const PageTimelineControls = (props: PageTimelineFrameProps) => {
    const layerClass = useLayerClass();

    return <div className={[styles.timelineControls, layerClass].join(" ")}>{props.children}</div>;
};

export const PageTimelineLanes = (props: PageTimelineLanesProps) => {
    const layerClass = useLayerClass();

    return (
        <div className={[styles.timelineLanes, layerClass].join(" ")}>
            {props.names.map((name, index) => (
                <div
                    key={index}
                    className={styles.timelineLaneName}
                    style={{
                        height: `${props.laneSize}px`,
                        marginTop: index === 0 ? undefined : `${props.laneGap}px`,
                    }}
                >
                    {name}
                </div>
            ))}
        </div>
    );
};

export const PageTimelineTick = (props: PageTimelineTickProps) => {
    const layerClass = useLayerClass();

    return (
        <>
            <div
                className={[styles.timelineRule, layerClass, props.tick.isMajor && styles.isMajor]
                    .filter(Boolean)
                    .join(" ")}
            />

            <div className={[styles.timelineTickLabel, layerClass].join(" ")}>{props.label}</div>
        </>
    );
};

export const PageTimelineMarker = (props: PageTimelineMarkerProps) => {
    const layerClass = useLayerClass();

    return props.marker.isInView ? (
        <div className={[`${styles.timelineMarker} ${styles.timelineMarkerTones[props.tone]}`, layerClass].join(" ")} />
    ) : null;
};

export const PageTimelineBlock = (props: PageTimelineBlockProps) => {
    const layerClass = useLayerClass();

    const flags = props.flags;

    return (
        <div
            className={[
                `${styles.timelineBlock} ${styles.timelineBlockTones[props.tone]}`,
                layerClass,
                flags.isHovered && styles.isHovered,
                flags.isFocusVisible && styles.isFocusVisible,
                flags.isDisabled && styles.isDisabled,
                flags.heldEdge === "start" && styles.isHeldStart,
                flags.heldEdge === "end" && styles.isHeldEnd,
            ]
                .filter(Boolean)
                .join(" ")}
        >
            <span className={styles.timelineBlockName}>{props.name}</span>
            <span className={styles.timelineBlockNote}>{props.note}</span>
        </div>
    );
};

// playground/src/App/StyledComponents/TimelineContent/TimelineContent.tsx
import { For, Show } from "solid-js";

import { access } from "@thewaver/ss-components";

import { useLayerClass } from "../Layer/Layer.context";
import type {
    PageTimelineBlockProps,
    PageTimelineFrameProps,
    PageTimelineLanesProps,
    PageTimelineMarkerProps,
    PageTimelineTickProps,
} from "./TimelineContent.types";

import * as styles from "./TimelineContent.css";

export const PageTimelineFrame = (props: PageTimelineFrameProps) => {
    const getLayerClass = useLayerClass();

    return <div class={[styles.timelineFrame, getLayerClass()].join(" ")}>{props.children}</div>;
};

export const PageTimelineRow = (props: PageTimelineFrameProps) => {
    const getLayerClass = useLayerClass();

    return <div class={[styles.timelineRow, getLayerClass()].join(" ")}>{props.children}</div>;
};

export const PageTimelineTrack = (props: PageTimelineFrameProps) => {
    const getLayerClass = useLayerClass();

    return <div class={[styles.timelineTrack, getLayerClass()].join(" ")}>{props.children}</div>;
};

export const PageTimelineControls = (props: PageTimelineFrameProps) => {
    const getLayerClass = useLayerClass();

    return <div class={[styles.timelineControls, getLayerClass()].join(" ")}>{props.children}</div>;
};

export const PageTimelineLanes = (props: PageTimelineLanesProps) => {
    const getLayerClass = useLayerClass();

    return (
        <div class={[styles.timelineLanes, getLayerClass()].join(" ")}>
            <For each={access(props.names)}>
                {(name, index) => (
                    <div
                        class={styles.timelineLaneName}
                        style={{
                            "height": `${access(props.laneSize)}px`,
                            "margin-top": index() === 0 ? undefined : `${access(props.laneGap)}px`,
                        }}
                    >
                        {name}
                    </div>
                )}
            </For>
        </div>
    );
};

export const PageTimelineTick = (props: PageTimelineTickProps) => {
    const getLayerClass = useLayerClass();

    return (
        <>
            <div
                class={styles.timelineRule}
                classList={{ [getLayerClass()]: true, [styles.isMajor]: access(props.tick).isMajor }}
            />

            <div class={[styles.timelineTickLabel, getLayerClass()].join(" ")}>{access(props.label)}</div>
        </>
    );
};

export const PageTimelineMarker = (props: PageTimelineMarkerProps) => {
    const getLayerClass = useLayerClass();

    return (
        <Show when={access(props.marker).isInView}>
            <div
                class={`${styles.timelineMarker} ${styles.timelineMarkerTones[access(props.tone)]}`}
                classList={{ [getLayerClass()]: true }}
            />
        </Show>
    );
};

export const PageTimelineBlock = (props: PageTimelineBlockProps) => {
    const getLayerClass = useLayerClass();

    const getFlags = () => access(props.flags);

    return (
        <div
            class={`${styles.timelineBlock} ${styles.timelineBlockTones[access(props.tone)]}`}
            classList={{
                [getLayerClass()]: true,
                [styles.isHovered]: getFlags().isHovered,
                [styles.isFocusVisible]: getFlags().isFocusVisible,
                [styles.isDisabled]: getFlags().isDisabled,
                [styles.isHeldStart]: getFlags().heldEdge === "start",
                [styles.isHeldEnd]: getFlags().heldEdge === "end",
            }}
        >
            <span class={styles.timelineBlockName}>{access(props.name)}</span>
            <span class={styles.timelineBlockNote}>{access(props.note)}</span>
        </div>
    );
};
