// playground-solid/src/App/Pages/SortableGridPage/Examples/Inventory.tsx
import type { Accessor, Signal } from "solid-js";
import { Show, createEffect, createSignal, onCleanup } from "solid-js";

import { Button, SortableGrid, access } from "@thewaver/ss-components-solid";
import type {
    InteractionFlags,
    MaybeAccessor,
    SortableGridController,
    SortableGridGeometry,
    SortableGridItem,
    SortableGridItemFlags,
    SortableGridSpot,
} from "@thewaver/ss-components-solid";
import { SORTABLE_GRID_ANNOUNCEMENTS } from "@thewaver/ss-playground/App/PageComponents/Announcements/Announcements.const";
import * as styles from "@thewaver/ss-playground/App/Pages/SortableGridPage/SortableGridPage.css";
import type { Gear } from "@thewaver/ss-playground/App/Pages/SortableGridPage/SortableGridPage.types";
import { CONTROL_GLYPHS } from "@thewaver/ss-playground/App/StyledComponents/ControlButtonContent/ControlButtonContent.const";

import { PageControlButtonContent } from "../../../StyledComponents/ControlButtonContent/ControlButtonContent";
import {
    PageSortableGridCell,
    PageSortableGridItemContent,
    PageSortableGridLanding,
    PageSortableGridSurface,
} from "../../../StyledComponents/SortableGridContent/SortableGridContent";
import type { SortableGridPaint } from "../../../StyledComponents/SortableGridContent/SortableGridContent.types";
import {
    CELL_SIZE,
    GRID_GAP,
    PACK_COLUMNS,
    PACK_ROWS,
    computeGearHue,
    computeGearKey,
    computeGearLabel,
} from "../SortableGridPage.const";

type Props = {
    groupId: string;
    items: Signal<SortableGridItem<Gear>[]>;
    ariaLabel: string;
    emptyText: string;
    columns?: number;
    rows?: number;
    paint?: SortableGridPaint;
    isDisabled?: MaybeAccessor<boolean>;
    isLocked?: MaybeAccessor<boolean>;
    isTurnable?: MaybeAccessor<boolean>;
    hasTurnButtons?: boolean;
    hasTidyButton?: boolean;
    isCompacting?: boolean;
    computeCanAccept?: (value: Gear, fromLabel: string) => boolean;
    computeIsSpotBlocked?: (spot: SortableGridSpot) => boolean;
};

const RESTING_FLAGS: InteractionFlags<SortableGridItemFlags> = { isCarried: false };

const TURN_KEY = "r";

export const InventoryExample = (props: Props) => {
    const [getController, setController] = createSignal<SortableGridController>();

    const turn = (step: number) => {
        if (step > 0) getController()?.turnCw();
        else getController()?.turnCcw();
    };

    const handleMount = (controller: SortableGridController) => {
        setController(controller);

        if (props.isCompacting) controller.compact();
    };

    const renderGear = (
        getItem: Accessor<SortableGridItem<Gear>>,
        getFlags: () => InteractionFlags<SortableGridItemFlags>,
        getGeometry: Accessor<SortableGridGeometry>,
    ) => (
        <PageSortableGridItemContent
            flags={getFlags}
            geometry={getGeometry}
            glyph={() => getItem().value.glyph}
            name={() => getItem().value.name}
            paint={() => props.paint ?? "contour"}
            hue={() => computeGearHue(getItem().value)}
        />
    );

    createEffect(() => {
        if (!(access(props.isTurnable) ?? false)) return;

        const handleKeyDown = (e: KeyboardEvent) => {
            if (!getController()?.getIsCarrying() || e.key.toLowerCase() !== TURN_KEY) return;

            e.preventDefault();
            turn(e.shiftKey ? -1 : 1);
        };

        const handleWheel = (e: WheelEvent) => {
            if (!getController()?.getIsCarrying()) return;

            e.preventDefault();
            turn(e.deltaY > 0 ? 1 : -1);
        };

        window.addEventListener("keydown", handleKeyDown);
        window.addEventListener("wheel", handleWheel, { passive: false });

        onCleanup(() => {
            window.removeEventListener("keydown", handleKeyDown);
            window.removeEventListener("wheel", handleWheel);
        });
    });

    return (
        <div class={styles.sortableGridStack}>
            <Show when={props.hasTurnButtons}>
                <div class={styles.sortableGridTurnControls}>
                    <Button
                        ariaLabel={"Turn counterclockwise"}
                        isDisabled={() => !getController()?.getIsCarrying()}
                        onClick={() => turn(-1)}
                        renderContent={(getFlags) => (
                            <PageControlButtonContent flags={getFlags} glyph={CONTROL_GLYPHS.turnLeft} />
                        )}
                    />

                    <Button
                        ariaLabel={"Turn clockwise"}
                        isDisabled={() => !getController()?.getIsCarrying()}
                        onClick={() => turn(1)}
                        renderContent={(getFlags) => (
                            <PageControlButtonContent flags={getFlags} glyph={CONTROL_GLYPHS.turnRight} />
                        )}
                    />
                </div>
            </Show>

            <Show when={props.hasTidyButton}>
                <div class={styles.sortableGridTurnControls}>
                    <Button
                        ariaLabel={"Tidy up"}
                        onClick={() => {
                            getController()?.compact();
                        }}
                        renderContent={(getFlags) => (
                            <PageControlButtonContent flags={getFlags}>{"Tidy up"}</PageControlButtonContent>
                        )}
                    />
                </div>
            </Show>

            <SortableGrid
                groupId={props.groupId}
                ariaLabel={props.ariaLabel}
                announcements={SORTABLE_GRID_ANNOUNCEMENTS}
                columns={() => props.columns ?? PACK_COLUMNS}
                rows={() => props.rows ?? PACK_ROWS}
                cellSize={CELL_SIZE}
                gap={GRID_GAP}
                isDisabled={() => access(props.isDisabled) ?? false}
                isLocked={() => access(props.isLocked) ?? false}
                isTurnable={() => access(props.isTurnable) ?? false}
                items={props.items}
                computeItemKey={computeGearKey}
                computeItemLabel={computeGearLabel}
                computeCanAccept={props.computeCanAccept}
                computeIsSpotBlocked={props.computeIsSpotBlocked}
                renderItem={renderGear}
                renderCarried={(getItem, getGeometry) => renderGear(getItem, () => RESTING_FLAGS, getGeometry)}
                renderCell={(getSpot, getFlags) => (
                    <PageSortableGridCell spot={getSpot} isBlocked={() => getFlags().isBlocked} />
                )}
                renderLanding={(getIsAllowed, getGeometry) => (
                    <PageSortableGridLanding isAllowed={getIsAllowed} geometry={getGeometry} />
                )}
                renderDecoration={(getFlags) => (
                    <PageSortableGridSurface flags={getFlags} emptyText={props.emptyText} />
                )}
                onTransfer={() => {
                    if (props.isCompacting) getController()?.compact();
                }}
                onMount={handleMount}
            />
        </div>
    );
};

// playground-react/src/App/Pages/SortableGridPage/Examples/Inventory.tsx
import { useCallback, useEffect, useState, useSyncExternalStore } from "react";

import { Button, SortableGrid } from "@thewaver/ss-components-react";
import type {
    InteractionFlags,
    SortableGridController,
    SortableGridGeometry,
    SortableGridItem,
    SortableGridItemFlags,
    SortableGridSpot,
} from "@thewaver/ss-components-react";
import { SORTABLE_GRID_ANNOUNCEMENTS } from "@thewaver/ss-playground/App/PageComponents/Announcements/Announcements.const";
import * as styles from "@thewaver/ss-playground/App/Pages/SortableGridPage/SortableGridPage.css";
import type { Gear } from "@thewaver/ss-playground/App/Pages/SortableGridPage/SortableGridPage.types";
import { CONTROL_GLYPHS } from "@thewaver/ss-playground/App/StyledComponents/ControlButtonContent/ControlButtonContent.const";

import { PageControlButtonContent } from "../../../StyledComponents/ControlButtonContent/ControlButtonContent";
import {
    PageSortableGridCell,
    PageSortableGridItemContent,
    PageSortableGridLanding,
    PageSortableGridSurface,
} from "../../../StyledComponents/SortableGridContent/SortableGridContent";
import type { SortableGridPaint } from "../../../StyledComponents/SortableGridContent/SortableGridContent.types";
import {
    CELL_SIZE,
    GRID_GAP,
    PACK_COLUMNS,
    PACK_ROWS,
    computeGearHue,
    computeGearKey,
    computeGearLabel,
} from "../SortableGridPage.const";

type Props = {
    groupId: string;
    items: readonly [SortableGridItem<Gear>[], (items: SortableGridItem<Gear>[]) => void];
    ariaLabel: string;
    emptyText: string;
    columns?: number;
    rows?: number;
    paint?: SortableGridPaint;
    isDisabled?: boolean;
    isLocked?: boolean;
    isTurnable?: boolean;
    hasTurnButtons?: boolean;
    hasTidyButton?: boolean;
    isCompacting?: boolean;
    computeCanAccept?: (value: Gear, fromLabel: string) => boolean;
    computeIsSpotBlocked?: (spot: SortableGridSpot) => boolean;
};

const RESTING_FLAGS: InteractionFlags<SortableGridItemFlags> = { isCarried: false };

const TURN_KEY = "r";

const NO_SUBSCRIPTION = () => {};

export const InventoryExample = (props: Props) => {
    const [controller, setController] = useState<SortableGridController>();

    const subscribe = useCallback(
        (listener: () => void) => controller?.subscribe(listener) ?? NO_SUBSCRIPTION,
        [controller],
    );

    const isCarrying = useSyncExternalStore(subscribe, () => controller?.getIsCarrying() ?? false);

    const isTurnable = props.isTurnable ?? false;

    const turn = (step: number) => {
        if (step > 0) controller?.turnCw();
        else controller?.turnCcw();
    };

    const handleMount = (mounted: SortableGridController) => {
        setController(mounted);

        if (props.isCompacting) mounted.compact();
    };

    const renderGear = (
        item: SortableGridItem<Gear>,
        flags: InteractionFlags<SortableGridItemFlags>,
        geometry: SortableGridGeometry,
    ) => (
        <PageSortableGridItemContent
            flags={flags}
            geometry={geometry}
            glyph={item.value.glyph}
            name={item.value.name}
            paint={props.paint ?? "contour"}
            hue={computeGearHue(item.value)}
        />
    );

    useEffect(() => {
        if (!isTurnable) return;

        const turnBy = (step: number) => {
            if (step > 0) controller?.turnCw();
            else controller?.turnCcw();
        };

        const handleKeyDown = (e: KeyboardEvent) => {
            if (!controller?.getIsCarrying() || e.key.toLowerCase() !== TURN_KEY) return;

            e.preventDefault();
            turnBy(e.shiftKey ? -1 : 1);
        };

        const handleWheel = (e: WheelEvent) => {
            if (!controller?.getIsCarrying()) return;

            e.preventDefault();
            turnBy(e.deltaY > 0 ? 1 : -1);
        };

        window.addEventListener("keydown", handleKeyDown);
        window.addEventListener("wheel", handleWheel, { passive: false });

        return () => {
            window.removeEventListener("keydown", handleKeyDown);
            window.removeEventListener("wheel", handleWheel);
        };
    }, [isTurnable, controller]);

    return (
        <div className={styles.sortableGridStack}>
            {props.hasTurnButtons && (
                <div className={styles.sortableGridTurnControls}>
                    <Button
                        ariaLabel={"Turn counterclockwise"}
                        isDisabled={!isCarrying}
                        onClick={() => turn(-1)}
                        renderContent={(flags) => (
                            <PageControlButtonContent flags={flags} glyph={CONTROL_GLYPHS.turnLeft} />
                        )}
                    />

                    <Button
                        ariaLabel={"Turn clockwise"}
                        isDisabled={!isCarrying}
                        onClick={() => turn(1)}
                        renderContent={(flags) => (
                            <PageControlButtonContent flags={flags} glyph={CONTROL_GLYPHS.turnRight} />
                        )}
                    />
                </div>
            )}

            {props.hasTidyButton && (
                <div className={styles.sortableGridTurnControls}>
                    <Button
                        ariaLabel={"Tidy up"}
                        onClick={() => {
                            controller?.compact();
                        }}
                        renderContent={(flags) => (
                            <PageControlButtonContent flags={flags}>{"Tidy up"}</PageControlButtonContent>
                        )}
                    />
                </div>
            )}

            <SortableGrid
                groupId={props.groupId}
                ariaLabel={props.ariaLabel}
                announcements={SORTABLE_GRID_ANNOUNCEMENTS}
                columns={props.columns ?? PACK_COLUMNS}
                rows={props.rows ?? PACK_ROWS}
                cellSize={CELL_SIZE}
                gap={GRID_GAP}
                isDisabled={props.isDisabled ?? false}
                isLocked={props.isLocked ?? false}
                isTurnable={isTurnable}
                items={props.items}
                computeItemKey={computeGearKey}
                computeItemLabel={computeGearLabel}
                computeCanAccept={props.computeCanAccept}
                computeIsSpotBlocked={props.computeIsSpotBlocked}
                renderItem={renderGear}
                renderCarried={(item, geometry) => renderGear(item, RESTING_FLAGS, geometry)}
                renderCell={(spot, flags) => <PageSortableGridCell spot={spot} isBlocked={flags.isBlocked} />}
                renderLanding={(isAllowed, geometry) => (
                    <PageSortableGridLanding isAllowed={isAllowed} geometry={geometry} />
                )}
                renderDecoration={(flags) => <PageSortableGridSurface flags={flags} emptyText={props.emptyText} />}
                onTransfer={() => {
                    if (props.isCompacting) controller?.compact();
                }}
                onMount={handleMount}
            />
        </div>
    );
};
