// components-react/src/Essentials/Input/RangeCalendar/RangeCalendar.tsx
import { useState } from "react";

import { type DateValue, RangeCalendarUtils } from "@thewaver/ss-components";

import { CalendarComposite } from "../Calendar/Calendar";
import type { RangeCalendarProps } from "../Calendar/Calendar.types";

export const RangeCalendar = (props: RangeCalendarProps) => {
    const [range, setRange] = props.value;

    const [pendingStart, setPendingStart] = useState<DateValue>();
    const [lastPicked, setLastPicked] = useState<DateValue>();

    const pick = (day: DateValue) => {
        const next = RangeCalendarUtils.computePick(day, pendingStart);

        setLastPicked(day);
        setPendingStart(next.pendingStart);
        setRange(next.range);
    };

    return (
        <CalendarComposite
            {...props}
            computeIsSelected={(day) => RangeCalendarUtils.getIsSelected(day, pendingStart, range)}
            anchorDay={RangeCalendarUtils.computeAnchorDay(pendingStart, lastPicked, range)}
            computeRange={(highlighted) => RangeCalendarUtils.computePaintedRange(highlighted, pendingStart, range)}
            onPick={pick}
        />
    );
};

// components-svelte/src/Essentials/Input/RangeCalendar/RangeCalendar.svelte
<script lang="ts">
    import { type DateValue, RangeCalendarUtils } from "@thewaver/ss-components";

    import type { RangeCalendarProps } from "../Calendar/Calendar.types.js";
    import CalendarComposite from "../Calendar/CalendarComposite.svelte";

    let { value = $bindable(), month = $bindable(), ...props }: RangeCalendarProps = $props();

    let pendingStart = $state.raw<DateValue>();
    let lastPicked = $state.raw<DateValue>();

    const pick = (day: DateValue) => {
        const next = RangeCalendarUtils.computePick(day, pendingStart);

        lastPicked = day;
        pendingStart = next.pendingStart;
        value = next.range;
    };
</script>

<CalendarComposite
    {...props}
    bind:month
    computeIsSelected={(day) => RangeCalendarUtils.getIsSelected(day, pendingStart, value)}
    anchorDay={RangeCalendarUtils.computeAnchorDay(pendingStart, lastPicked, value)}
    computeRange={(highlighted) => RangeCalendarUtils.computePaintedRange(highlighted, pendingStart, value)}
    onPick={pick}
/>
