// playground-svelte/src/App/Pages/Accordions/AccordionPage/Examples/Sections.svelte
<script lang="ts">
    import { Accordion } from "@thewaver/ss-components-svelte";
    import type { AccordionItem } from "@thewaver/ss-components-svelte";

    import PageAccordionHeader from "../../../../StyledComponents/AccordionContent/PageAccordionHeader.svelte";
    import PageAccordionPanel from "../../../../StyledComponents/AccordionContent/PageAccordionPanel.svelte";
    import type { AccordionExampleProps } from "../../Accordions.types";

    const GAP = 5;

    const SECTION_BODIES: Record<string, string[]> = {
        Shipping: ["Orders leave the warehouse within two working days.", "Tracking arrives by email."],
        Returns: ["Thirty days, unopened, receipt or order number."],
        Warranty: ["Two years against manufacturing defects."],
        Unavailable: ["This section is disabled, so its header refuses to open it."],
    };

    const ITEMS: AccordionItem<string>[] = [
        { value: "Shipping" },
        { value: "Returns" },
        { value: "Warranty" },
        { value: "Unavailable", isDisabled: true },
    ];

    type Props = AccordionExampleProps & {
        isSingleExpand?: boolean;
        isExpandRequired?: boolean;
    };

    let { expanded = $bindable([]), ...props }: Props = $props();
</script>

<Accordion
    items={ITEMS}
    bind:expanded
    isSingleExpand={props.isSingleExpand}
    isExpandRequired={props.isExpandRequired}
    gap={GAP}
>
    {#snippet renderHeader(item, flags)}
        <PageAccordionHeader {flags}>{item.value}</PageAccordionHeader>
    {/snippet}

    {#snippet renderPanel(item, visibilityTarget, transitionDurationMs)}
        <PageAccordionPanel {visibilityTarget} {transitionDurationMs}>
            {#each SECTION_BODIES[item.value] as line (line)}
                <div>{line}</div>
            {/each}
        </PageAccordionPanel>
    {/snippet}
</Accordion>

// playground-solid/src/App/Pages/Accordions/AccordionPage/Examples/Sections.tsx
import { Accordion } from "@thewaver/ss-components-solid";
import type { AccordionItem, MaybeAccessor } from "@thewaver/ss-components-solid";

import {
    PageAccordionHeader,
    PageAccordionPanel,
} from "../../../../StyledComponents/AccordionContent/AccordionContent";
import type { AccordionExampleProps } from "../../Accordions.types";

const GAP = 5;

const SECTION_BODIES: Record<string, string[]> = {
    Shipping: ["Orders leave the warehouse within two working days.", "Tracking arrives by email."],
    Returns: ["Thirty days, unopened, receipt or order number."],
    Warranty: ["Two years against manufacturing defects."],
    Unavailable: ["This section is disabled, so its header refuses to open it."],
};

const ITEMS: AccordionItem<string>[] = [
    { value: "Shipping" },
    { value: "Returns" },
    { value: "Warranty" },
    { value: "Unavailable", isDisabled: true },
];

type Props = AccordionExampleProps & {
    isSingleExpand?: MaybeAccessor<boolean>;
    isExpandRequired?: MaybeAccessor<boolean>;
};

export const SectionsExample = (props: Props) => {
    return (
        <Accordion
            items={() => ITEMS}
            expanded={props.expanded}
            isSingleExpand={props.isSingleExpand}
            isExpandRequired={props.isExpandRequired}
            gap={() => GAP}
            renderHeader={(getItem, getFlags) => (
                <PageAccordionHeader flags={getFlags}>{getItem().value}</PageAccordionHeader>
            )}
            renderPanel={(getItem, getVisibilityTarget, getTransitionDurationMs) => (
                <PageAccordionPanel
                    visibilityTarget={getVisibilityTarget}
                    transitionDurationMs={getTransitionDurationMs}
                >
                    {SECTION_BODIES[getItem().value].map((line) => (
                        <div>{line}</div>
                    ))}
                </PageAccordionPanel>
            )}
        />
    );
};
