// components-solid/src/Essentials/Input/CheckboxGroup/CheckboxGroup.context.ts
import { createContext, useContext } from "solid-js";

import type { CheckboxGroupContextType } from "@thewaver/ss-components";

const CheckboxGroupContext = createContext<CheckboxGroupContextType>();

export const CheckboxGroupContextProvider = CheckboxGroupContext.Provider;

export const useCheckboxGroupContext = (): CheckboxGroupContextType | undefined => useContext(CheckboxGroupContext);

// components-react/src/Essentials/Input/CheckboxGroup/CheckboxGroup.context.ts
import { createContext, useContext } from "react";

import type { CheckboxGroupReactContextType } from "./CheckboxGroup.context.types";

const CheckboxGroupContext = createContext<CheckboxGroupReactContextType | undefined>(undefined);

export const CheckboxGroupContextProvider = CheckboxGroupContext.Provider;

export const useCheckboxGroupContext = (): CheckboxGroupReactContextType | undefined =>
    useContext(CheckboxGroupContext);
