// components-svelte/src/Essentials/Input/DateRangePicker/DateRangePicker.svelte
<script lang="ts">
    import { untrack } from "svelte";

    import {
        DATE_RANGE_PICKER_DEFAULTS,
        DateRangePickerUtils,
        type DateValue,
        type DateValueRange,
        DateValueUtils,
        type DismisserReason,
        DateRangePickerStyles as styles,
    } from "@thewaver/ss-components";

    import { SignalMirrorSvelteUtils } from "../../../Abstracts/SignalMirror/SignalMirrorSvelte.utils.svelte.js";
    import InteractionWrapper from "../../../Primitives/InteractionWrapper/InteractionWrapper.svelte";
    import Popover from "../../../Primitives/Popover/Popover.svelte";
    import PopupTrigger from "../../../Primitives/PopupTrigger/PopupTrigger.svelte";
    import type { ValuePair } from "../../../Utils/typeUtils.js";
    import DateInput from "../DateInput/DateInput.svelte";
    import RangeCalendar from "../RangeCalendar/RangeCalendar.svelte";
    import type { DateRangePickerProps } from "./DateRangePicker.types.js";

    const toMonth = (value: DateValue): DateValue => DateValueUtils.getStartOfMonth(value);

    let {
        value = $bindable(),
        visibility = $bindable(false),
        ref = $bindable(),
        ...props
    }: DateRangePickerProps = $props();

    const uid = $props.id();
    const popupId = `${uid}-popup`;
    const fallbackFieldId = `${uid}-field`;

    const endFieldId = $derived(`${props.id ?? fallbackFieldId}-end`);

    let root = $state<HTMLDivElement>();
    let month = $state.raw(untrack(() => toMonth(value?.start ?? DateValueUtils.fromDate(new Date()))));
    let isFocusReturned = false;

    const { first: start, second: end } = SignalMirrorSvelteUtils.createSplit<DateValueRange, DateValue, DateValue>(
        [
            () => value,
            (next) => {
                value = next;
            },
        ],
        DateRangePickerUtils.SPLIT_DEFS,
    );

    const isDisabled = $derived(props.isDisabled ?? false);

    const monthPair: ValuePair<DateValue> = [
        () => month,
        (next) => {
            month = next;
        },
    ];

    const open = () => {
        if (isDisabled) return;

        visibility = true;
    };

    const dismiss = () => {
        if (!visibility) return;

        isFocusReturned = true;
        visibility = false;
    };

    const handleDismiss = (reason: DismisserReason) => {
        if (reason === "escape") dismiss();
        else visibility = false;
    };

    $effect(() => {
        if (visibility && isDisabled) visibility = false;
    });

    $effect(() => {
        if (!visibility) return;

        untrack(() => {
            if (value?.start) month = toMonth(value.start);
        });
    });

    $effect(() => {
        if (visibility || !isFocusReturned) return;

        isFocusReturned = false;

        root?.querySelector<HTMLInputElement>(`#${CSS.escape(endFieldId)}`)?.focus();
    });
</script>

{#snippet renderCalendar()}
    <RangeCalendar
        bind:value
        bind:month
        minValue={props.minValue}
        maxValue={props.maxValue}
        isDisabled={props.isDisabled}
        locale={props.locale}
        weekStartsOn={props.weekStartsOn}
        ariaLabel={props.calendarLabel}
        computeIsDayDisabled={props.computeIsDayDisabled}
        renderDay={props.renderDay}
        renderWeekday={props.renderWeekday}
    />
{/snippet}

{#snippet trailing()}
    <InteractionWrapper {isDisabled} extraFlags={{ isOpen: visibility }}>
        {#snippet renderControl(attachElement, flags)}
            <PopupTrigger
                {attachElement}
                id={props.triggerId}
                {popupId}
                isOpen={visibility}
                ariaLabel={props.triggerAriaLabel}
                {flags}
                renderContent={props.renderTrigger}
                onToggle={() => (visibility ? dismiss() : open())}
            />
        {/snippet}
    </InteractionWrapper>
{/snippet}

{#snippet popupContent(visibilityTarget: 0 | 1, transitionDurationMs: number)}
    {@render props.renderPopup(renderCalendar, monthPair, visibilityTarget, transitionDurationMs)}
{/snippet}

<div bind:this={root} class={styles.dateRangePickerRoot}>
    <DateInput
        {...props}
        bind:value={start[0], start[1]}
        bind:ref
        id={props.id && `${props.id}-start`}
        name={props.name && `${props.name}-start`}
        ariaLabel={props.startLabel}
    />

    {@render props.renderSeparator?.()}

    <DateInput
        {...props}
        bind:value={end[0], end[1]}
        bind:ref
        id={endFieldId}
        name={props.name && `${props.name}-end`}
        ariaLabel={props.endLabel}
        renderTrailing={trailing}
    />

    <Popover
        id={popupId}
        role={"dialog"}
        ariaAttributes={{ "aria-label": props.calendarLabel }}
        isOpen={visibility}
        anchorRef={root}
        placement={props.placement ?? DATE_RANGE_PICKER_DEFAULTS.placement}
        offset={props.offset}
        transitionDurationMs={props.popupTransitionDurationMs}
        hasAutoFocus={true}
        onDismiss={handleDismiss}
        renderContent={popupContent}
    />
</div>

// components-react/src/Essentials/Input/DateRangePicker/DateRangePicker.tsx
import { useCallback, useEffect, useId, useLayoutEffect, useRef, useState } from "react";

import {
    DATE_RANGE_PICKER_DEFAULTS,
    DateRangePickerStyles,
    DateRangePickerUtils,
    type DateValue,
    type DateValueRange,
    DateValueUtils,
    type PopupTriggerFlags,
} from "@thewaver/ss-components";

import { SignalMirrorReactUtils } from "../../../Abstracts/SignalMirror/SignalMirrorReact.utils";
import { InteractionWrapper } from "../../../Primitives/InteractionWrapper/InteractionWrapper";
import { Popover } from "../../../Primitives/Popover/Popover";
import { PopupTrigger } from "../../../Primitives/PopupTrigger/PopupTrigger";
import { DateInput } from "../DateInput/DateInput";
import { RangeCalendar } from "../RangeCalendar/RangeCalendar";
import type { DateRangePickerProps } from "./DateRangePicker.types";

const toMonth = (value: DateValue): DateValue => DateValueUtils.getStartOfMonth(value);

export const DateRangePicker = (props: DateRangePickerProps) => {
    const [range] = props.value;

    const popupId = useId();
    const fallbackFieldId = useId();

    const endFieldId = `${props.id ?? fallbackFieldId}-end`;

    const rootRef = useRef<HTMLDivElement | null>(null);
    const isFocusReturnedRef = useRef(false);
    const [root, setRoot] = useState<HTMLDivElement>();
    const [isOpen, setIsOpen] = SignalMirrorReactUtils.useOptionalState(props.visibility, false);
    const monthState = useState(() => toMonth(range?.start ?? DateValueUtils.fromDate(new Date())));
    const [, setMonth] = monthState;

    const { first: startState, second: endState } = SignalMirrorReactUtils.useSplit<
        DateValueRange,
        DateValue,
        DateValue
    >(props.value, DateRangePickerUtils.SPLIT_DEFS);

    const isDisabled = props.isDisabled ?? false;

    const setRootRef = useCallback((element: HTMLDivElement | null) => {
        rootRef.current = element;
        setRoot(element ?? undefined);
    }, []);

    const open = () => {
        if (isDisabled) return;

        setIsOpen(true);
    };

    const dismiss = () => {
        if (!isOpen) return;

        isFocusReturnedRef.current = true;
        setIsOpen(false);
    };

    useEffect(() => {
        if (isOpen && isDisabled) setIsOpen(false);
    }, [isOpen, isDisabled]);

    useLayoutEffect(() => {
        if (isOpen && range?.start) setMonth(toMonth(range.start));
    }, [isOpen]);

    useEffect(() => {
        if (isOpen || !isFocusReturnedRef.current) return;

        isFocusReturnedRef.current = false;
        rootRef.current?.querySelector<HTMLInputElement>(`#${CSS.escape(endFieldId)}`)?.focus();
    }, [isOpen]);

    const renderCalendar = () => (
        <RangeCalendar
            value={props.value}
            month={monthState}
            minValue={props.minValue}
            maxValue={props.maxValue}
            isDisabled={props.isDisabled}
            locale={props.locale}
            weekStartsOn={props.weekStartsOn}
            ariaLabel={props.calendarLabel}
            computeIsDayDisabled={props.computeIsDayDisabled}
            renderDay={props.renderDay}
            renderWeekday={props.renderWeekday}
        />
    );

    return (
        <div ref={setRootRef} className={DateRangePickerStyles.dateRangePickerRoot}>
            <DateInput
                {...props}
                value={startState}
                id={props.id && `${props.id}-start`}
                name={props.name && `${props.name}-start`}
                ariaLabel={props.startLabel}
            />

            {props.renderSeparator?.()}

            <DateInput
                {...props}
                value={endState}
                id={endFieldId}
                name={props.name && `${props.name}-end`}
                ariaLabel={props.endLabel}
                renderTrailing={() => (
                    <InteractionWrapper<PopupTriggerFlags>
                        isDisabled={isDisabled}
                        extraFlags={{ isOpen }}
                        renderControl={(setElementRef, flags) => (
                            <PopupTrigger
                                ref={setElementRef}
                                id={props.triggerId}
                                popupId={popupId}
                                isOpen={isOpen}
                                ariaLabel={props.triggerAriaLabel}
                                flags={flags}
                                renderContent={props.renderTrigger}
                                onToggle={() => (isOpen ? dismiss() : open())}
                            />
                        )}
                    />
                )}
            />

            <Popover
                id={popupId}
                role={"dialog"}
                ariaAttributes={{ "aria-label": props.calendarLabel }}
                isOpen={isOpen}
                anchorRef={root}
                placement={props.placement ?? DATE_RANGE_PICKER_DEFAULTS.placement}
                offset={props.offset}
                transitionDurationMs={props.popupTransitionDurationMs}
                hasAutoFocus={true}
                onDismiss={(reason) => (reason === "escape" ? dismiss() : setIsOpen(false))}
                renderContent={(visibilityTarget, transitionDurationMs) =>
                    props.renderPopup(renderCalendar, monthState, visibilityTarget, transitionDurationMs)
                }
            />
        </div>
    );
};
