// playground-solid/src/App/PageComponents/CalendarCaption/CalendarPagedCaption.tsx
import { Button, CalendarUtils, DateValueUtils, access } from "@thewaver/ss-components-solid";

import { PageButtonContent } from "../../StyledComponents/ButtonContent/ButtonContent";
import { PageCalendarHeader, PageCalendarTitle } from "../../StyledComponents/CalendarContent/CalendarContent";
import type { PageCalendarPagedCaptionProps } from "./CalendarPagedCaption.types";

const PAGE_STEP = 1;
const WEEK_STARTS_ON = 1;
const YEAR_OPTIONS: Intl.DateTimeFormatOptions = { year: "numeric" };
const MONTH_TITLE_OPTIONS: Intl.DateTimeFormatOptions = { month: "long", year: "numeric" };

export const PageCalendarPagedCaption = (props: PageCalendarPagedCaptionProps) => {
    const getMonth = () => props.month[0]();

    const getTitle = () => {
        const precision = access(props.precision);
        const locale = access(props.locale);

        if (precision === "day") return DateValueUtils.format(getMonth(), MONTH_TITLE_OPTIONS, locale);
        if (precision === "month") return DateValueUtils.format(getMonth(), YEAR_OPTIONS, locale);

        const cells = CalendarUtils.getCells(getMonth(), precision, WEEK_STARTS_ON);

        return CalendarUtils.formatSpan(cells[0], cells[cells.length - 1], YEAR_OPTIONS, locale);
    };

    const page = (direction: 1 | -1) => {
        props.month[1]((prev) => CalendarUtils.stepPage(prev, access(props.precision), direction * PAGE_STEP));
    };

    return (
        <PageCalendarHeader>
            <Button
                id={() => `${access(props.key)}PreviousPage`}
                ariaLabel={props.previousLabel}
                renderContent={(getFlags) => <PageButtonContent flags={getFlags}>◀</PageButtonContent>}
                onClick={() => page(-1)}
            />

            <PageCalendarTitle flags={{}}>{getTitle()}</PageCalendarTitle>

            <Button
                id={() => `${access(props.key)}NextPage`}
                ariaLabel={props.nextLabel}
                renderContent={(getFlags) => <PageButtonContent flags={getFlags}>▶</PageButtonContent>}
                onClick={() => page(1)}
            />
        </PageCalendarHeader>
    );
};

// playground-svelte/src/App/PageComponents/CalendarCaption/CalendarPagedCaption.svelte
<script lang="ts">
    import { Button, CalendarUtils, DateValueUtils } from "@thewaver/ss-components-svelte";

    import PageButtonContent from "../../StyledComponents/ButtonContent/ButtonContent.svelte";
    import PageCalendarHeader from "../../StyledComponents/CalendarContent/PageCalendarHeader.svelte";
    import PageCalendarTitle from "../../StyledComponents/CalendarContent/PageCalendarTitle.svelte";
    import type { PageCalendarPagedCaptionProps } from "./CalendarPagedCaption.types";

    const PAGE_STEP = 1;
    const WEEK_STARTS_ON = 1;
    const YEAR_OPTIONS: Intl.DateTimeFormatOptions = { year: "numeric" };
    const MONTH_TITLE_OPTIONS: Intl.DateTimeFormatOptions = { month: "long", year: "numeric" };

    let props: PageCalendarPagedCaptionProps = $props();

    const month = $derived(props.month[0]());

    const getTitle = () => {
        if (props.precision === "day") return DateValueUtils.format(month, MONTH_TITLE_OPTIONS, props.locale);
        if (props.precision === "month") return DateValueUtils.format(month, YEAR_OPTIONS, props.locale);

        const cells = CalendarUtils.getCells(month, props.precision, WEEK_STARTS_ON);

        return CalendarUtils.formatSpan(cells[0], cells[cells.length - 1], YEAR_OPTIONS, props.locale);
    };

    const page = (direction: 1 | -1) => {
        props.month[1](CalendarUtils.stepPage(month, props.precision, direction * PAGE_STEP));
    };
</script>

<PageCalendarHeader>
    <Button id={`${props.itemKey}PreviousPage`} ariaLabel={props.previousLabel} onClick={() => page(-1)}>
        {#snippet renderContent(flags)}
            <PageButtonContent {flags}>◀</PageButtonContent>
        {/snippet}
    </Button>

    <PageCalendarTitle flags={{}}>{getTitle()}</PageCalendarTitle>

    <Button id={`${props.itemKey}NextPage`} ariaLabel={props.nextLabel} onClick={() => page(1)}>
        {#snippet renderContent(flags)}
            <PageButtonContent {flags}>▶</PageButtonContent>
        {/snippet}
    </Button>
</PageCalendarHeader>
