// playground-vue/src/App/Pages/Accordions/AccordionPage/Examples/Growing.vue
<script setup lang="ts">
import { useModel } from "vue";

import { Accordion, Button } from "@thewaver/ss-components-vue";
import type { AccordionItem } from "@thewaver/ss-components-vue";

import PageAccordionHeader from "../../../../StyledComponents/AccordionContent/PageAccordionHeader.vue";
import PageAccordionPanel from "../../../../StyledComponents/AccordionContent/PageAccordionPanel.vue";
import PageButtonContent from "../../../../StyledComponents/ButtonContent/ButtonContent.vue";
import type { AccordionGrowingExampleProps } from "../../Accordions.types";

const TRANSITION_DURATION_MS = 400;

const ITEMS: AccordionItem<string>[] = [{ value: "Shipping" }];

type Props = AccordionGrowingExampleProps;

const props = defineProps<Props>();

const expanded = useModel(props, "expanded");
</script>

<template>
    <Accordion v-model:expanded="expanded" :items="ITEMS" :transition-duration-ms="TRANSITION_DURATION_MS">
        <template #renderHeader="{ item, flags }">
            <PageAccordionHeader :flags="flags">{{ item.value }}</PageAccordionHeader>
        </template>

        <template #renderPanel="{ visibilityTarget, transitionDurationMs }">
            <PageAccordionPanel :visibility-target="visibilityTarget" :transition-duration-ms="transitionDurationMs">
                <Button id="addALine" @click="props.onAddLine">
                    <template #renderContent="flags">
                        <PageButtonContent :flags="flags">Add a line</PageButtonContent>
                    </template>
                </Button>

                <div v-for="index in extraLines" :key="index">
                    {{ `Line ${index} appeared after the panel was already open.` }}
                </div>
            </PageAccordionPanel>
        </template>
    </Accordion>
</template>

// playground-react/src/App/Pages/Accordions/AccordionPage/Examples/Growing.tsx
import { Accordion, Button } from "@thewaver/ss-components-react";
import type { AccordionItem } from "@thewaver/ss-components-react";

import {
    PageAccordionHeader,
    PageAccordionPanel,
} from "../../../../StyledComponents/AccordionContent/AccordionContent";
import { PageButtonContent } from "../../../../StyledComponents/ButtonContent/ButtonContent";
import type { AccordionGrowingExampleProps } from "../../Accordions.types";

const TRANSITION_DURATION_MS = 400;

const ITEMS: AccordionItem<string>[] = [{ value: "Shipping" }];

type Props = AccordionGrowingExampleProps;

export const GrowingExample = (props: Props) => {
    return (
        <Accordion
            items={ITEMS}
            expanded={props.expanded}
            transitionDurationMs={TRANSITION_DURATION_MS}
            renderHeader={(item, flags) => <PageAccordionHeader flags={flags}>{item.value}</PageAccordionHeader>}
            renderPanel={(_, visibilityTarget, transitionDurationMs) => (
                <PageAccordionPanel visibilityTarget={visibilityTarget} transitionDurationMs={transitionDurationMs}>
                    <Button
                        id={"addALine"}
                        renderContent={(flags) => <PageButtonContent flags={flags}>Add a line</PageButtonContent>}
                        onClick={props.onAddLine}
                    />

                    {Array.from({ length: props.extraLines }, (_unused, index) => (
                        <div key={index}>Line {index + 1} appeared after the panel was already open.</div>
                    ))}
                </PageAccordionPanel>
            )}
        />
    );
};
