// components-vue/src/Essentials/AudioSwitcher/AudioSwitcher.tsx
import { defineComponent } from "vue";

import { AUDIO_SWITCHER_DEFAULTS, AudioSwitcherUtils } from "@thewaver/ss-components";

import { watchAfterRender } from "../../Utils/effectUtils";
import { declareProps, useTwoWay } from "../../Utils/propUtils";
import type { AudioSwitcherProps } from "./AudioSwitcher.types";

export const AudioSwitcher = defineComponent(
    (props: AudioSwitcherProps) => {
        const isPlaying = useTwoWay(props, "playback", false);

        const getVolume = () => props.volume ?? AUDIO_SWITCHER_DEFAULTS.volume;

        const switcher = AudioSwitcherUtils.createSwitcher({
            getVolume,
            getCrossfadeMs: () => props.crossfadeMs ?? AUDIO_SWITCHER_DEFAULTS.crossfadeMs,
            getIsPlaying: () => isPlaying.value,
            setIsPlaying: (value) => {
                isPlaying.value = value;
            },
        });

        watchAfterRender([], () => switcher.mount());

        watchAfterRender([isPlaying], () => switcher.followPlayback());

        watchAfterRender([getVolume], () => switcher.applyVolume());

        watchAfterRender([() => props.src], ([src]) => switcher.setSource(src, props.shouldAutoPlayOnMount ?? false));

        watchAfterRender([], () => {
            props.onMount?.(switcher.controller);
        });

        return () => null;
    },
    {
        name: "AudioSwitcher",
        props: declareProps<AudioSwitcherProps>({
            "src": null,
            "crossfadeMs": null,
            "shouldAutoPlayOnMount": Boolean,
            "volume": null,
            "playback": Boolean,
            "onUpdate:playback": null,
            "onMount": null,
        }),
    },
);

// components-solid/src/Essentials/AudioSwitcher/AudioSwitcher.tsx
import { createEffect, on, onCleanup, onMount } from "solid-js";

import { AUDIO_SWITCHER_DEFAULTS, AudioSwitcherUtils } from "@thewaver/ss-components";

import { SignalMirrorSolidUtils } from "../../Abstracts/SignalMirror/SignalMirrorSolid.utils";
import { access } from "../../Utils/propUtils";
import type { AudioSwitcherProps } from "./AudioSwitcherSolid.types";

export const AudioSwitcher = (props: AudioSwitcherProps) => {
    const [getIsPlaying, setIsPlaying] = SignalMirrorSolidUtils.createOptional(() => props.playback, false);

    const getVolume = () => access(props.volume) ?? AUDIO_SWITCHER_DEFAULTS.volume;

    const switcher = AudioSwitcherUtils.createSwitcher({
        getVolume,
        getCrossfadeMs: () => access(props.crossfadeMs) ?? AUDIO_SWITCHER_DEFAULTS.crossfadeMs,
        getIsPlaying,
        setIsPlaying,
    });

    let stop: (() => void) | undefined;

    onCleanup(() => stop?.());

    createEffect(() => switcher.followPlayback());

    createEffect(on(getVolume, () => switcher.applyVolume()));

    createEffect(() => switcher.setSource(access(props.src), access(props.shouldAutoPlayOnMount) ?? false));

    onMount(() => {
        stop = switcher.mount();
        props.onMount?.(switcher.controller);
    });

    return null;
};
