// components/src/Essentials/Button/Button.tsx
import { createSignal } from "solid-js";

import { InteractionWrapper } from "../../Primitives/InteractionWrapper/InteractionWrapper";
import { access } from "../../Utils/propUtils";
import { LabelUtils } from "../Input/Label/Label.utils";
import { BUTTON_DEFAULTS } from "./Button.const";
import type { ButtonElementProps, ButtonFlags, ButtonProps } from "./Button.types";

import * as styles from "./Button.css";

const ButtonElement = (props: ButtonElementProps) => {
    const getAriaLabel = LabelUtils.resolveAriaLabel(
        props.ariaLabel === undefined ? undefined : () => access(props.ariaLabel)!,
    );

    const getIsDisabled = () => access(props.flags).isDisabled ?? false;

    const getIsPending = () => access(props.flags).isPending;

    const getIsRefusing = () => getIsDisabled() || getIsPending();

    return (
        <button
            id={access(props.id)}
            ref={(element) => props.ref?.(element)}
            type={access(props.type) ?? BUTTON_DEFAULTS.type}
            class={styles.buttonElement}
            aria-label={getAriaLabel()}
            aria-disabled={getIsDisabled() || undefined}
            aria-pressed={access(props.flags).isPressed}
            aria-busy={getIsPending() || undefined}
            onClick={(e) => {
                if (getIsRefusing()) {
                    e.preventDefault();

                    return;
                }

                void props.onClick?.(e);
            }}
            onPointerDown={(e) => {
                if (getIsRefusing()) return;

                void props.onPointerDown?.(e);
            }}
            onPointerUp={(e) => {
                if (getIsRefusing()) return;

                void props.onPointerUp?.(e);
            }}
            onPointerCancel={(e) => {
                if (getIsRefusing()) return;

                void props.onPointerUp?.(e);
            }}
            onMouseEnter={(e) => {
                if (getIsDisabled()) return;

                void props.onMouseEnter?.(e);
            }}
            onMouseLeave={(e) => {
                if (getIsDisabled()) return;

                void props.onMouseLeave?.(e);
            }}
        >
            {props.renderContent(() => access(props.flags))}
        </button>
    );
};

export const Button = (props: ButtonProps) => {
    const [getIsPending, setIsPending] = createSignal(false);

    const handleClick = (e: MouseEvent | KeyboardEvent) => {
        const result = props.onClick?.(e);

        if (!(result instanceof Promise)) return;

        setIsPending(true);

        void result.finally(() => setIsPending(false));
    };

    return (
        <InteractionWrapper<ButtonFlags>
            {...props}
            extraFlags={() => ({ isPending: getIsPending() })}
            onActivation={
                props.onActivation &&
                ((activation) => {
                    if (getIsPending()) return;

                    props.onActivation?.(activation);
                })
            }
            renderControl={(setElementRef, getFlags) => (
                <ButtonElement
                    ref={setElementRef}
                    ariaLabel={props.ariaLabel}
                    type={props.type}
                    id={props.id}
                    flags={getFlags}
                    renderContent={props.renderContent}
                    onClick={handleClick}
                    onPointerDown={props.onPointerDown}
                    onPointerUp={props.onPointerUp}
                    onMouseEnter={props.onMouseEnter}
                    onMouseLeave={props.onMouseLeave}
                />
            )}
        />
    );
};

// components-react/src/Essentials/Button/Button.tsx
import { useState } from "react";

import { BUTTON_DEFAULTS, type ButtonFlags, ButtonStyles } from "@thewaver/ss-components";

import { InteractionWrapper } from "../../Primitives/InteractionWrapper/InteractionWrapper";
import { LabelReactUtils } from "../Input/Label/LabelReact.utils";
import type { ButtonElementProps, ButtonProps } from "./Button.types";

const ButtonElement = (props: ButtonElementProps) => {
    const ariaLabel = LabelReactUtils.useAriaLabel(props.ariaLabel);

    const isDisabled = props.flags.isDisabled ?? false;
    const isPending = props.flags.isPending;
    const isRefusing = isDisabled || isPending;

    return (
        <button
            id={props.id}
            ref={props.ref}
            type={props.type ?? BUTTON_DEFAULTS.type}
            className={ButtonStyles.buttonElement}
            aria-label={ariaLabel}
            aria-disabled={isDisabled || undefined}
            aria-pressed={props.flags.isPressed}
            aria-busy={isPending || undefined}
            onClick={(e) => {
                if (isRefusing) {
                    e.preventDefault();

                    return;
                }

                void props.onClick?.(e);
            }}
            onPointerDown={(e) => {
                if (isRefusing) return;

                props.onPointerDown?.(e);
            }}
            onPointerUp={(e) => {
                if (isRefusing) return;

                props.onPointerUp?.(e);
            }}
            onPointerCancel={(e) => {
                if (isRefusing) return;

                props.onPointerUp?.(e);
            }}
            onMouseEnter={(e) => {
                if (isDisabled) return;

                props.onMouseEnter?.(e);
            }}
            onMouseLeave={(e) => {
                if (isDisabled) return;

                props.onMouseLeave?.(e);
            }}
        >
            {props.renderContent(props.flags)}
        </button>
    );
};

export const Button = (props: ButtonProps) => {
    const [isPending, setIsPending] = useState(false);

    const handleClick: ButtonProps["onClick"] = (e) => {
        const result = props.onClick?.(e);

        if (!(result instanceof Promise)) return;

        setIsPending(true);

        void result.finally(() => setIsPending(false));
    };

    return (
        <InteractionWrapper<ButtonFlags>
            {...props}
            extraFlags={{ isPending }}
            onActivation={
                props.onActivation &&
                ((activation) => {
                    if (isPending) return;

                    props.onActivation?.(activation);
                })
            }
            renderControl={(setElementRef, flags) => (
                <ButtonElement
                    ref={setElementRef}
                    ariaLabel={props.ariaLabel}
                    type={props.type}
                    id={props.id}
                    flags={flags}
                    renderContent={props.renderContent}
                    onClick={handleClick}
                    onPointerDown={props.onPointerDown}
                    onPointerUp={props.onPointerUp}
                    onMouseEnter={props.onMouseEnter}
                    onMouseLeave={props.onMouseLeave}
                />
            )}
        />
    );
};
