// playground-solid/src/App/StyledComponents/ButtonContent/ButtonContent.tsx
import type { ParentProps } from "solid-js";

import { access } from "@thewaver/ss-components-solid";
import * as styles from "@thewaver/ss-playground-core/App/StyledComponents/ButtonContent/ButtonContent.css";

import type { ButtonContentProps } from "./ButtonContent.types";

export const PageButtonContent = (props: ParentProps<ButtonContentProps>) => {
    return (
        <div
            class={styles.buttonContent}
            classList={{
                [styles.isHovered]: access(props.flags).isHovered,
                [styles.isActive]: access(props.flags).isActive,
                [styles.isDisabled]: access(props.flags).isDisabled,
                [styles.hasError]: access(props.flags).hasError,
            }}
        >
            {props.children}
        </div>
    );
};

// playground-react/src/App/StyledComponents/ButtonContent/ButtonContent.tsx
import type { PropsWithChildren } from "react";

import * as styles from "@thewaver/ss-playground-core/App/StyledComponents/ButtonContent/ButtonContent.css";

import type { ButtonContentProps } from "./ButtonContent.types";

export const PageButtonContent = (props: PropsWithChildren<ButtonContentProps>) => {
    return (
        <div
            className={[
                styles.buttonContent,
                props.flags.isHovered && styles.isHovered,
                props.flags.isActive && styles.isActive,
                props.flags.isDisabled && styles.isDisabled,
                props.flags.hasError && styles.hasError,
            ]
                .filter(Boolean)
                .join(" ")}
        >
            {props.children}
        </div>
    );
};
