// playground-vue/src/App/Pages/Carousels/CarouselPage/Examples/Scrolled.vue
<script setup lang="ts">
import { shallowRef, useModel } from "vue";

import { Carousel, ElementObserverVueUtils } from "@thewaver/ss-components-vue";
import {
    computeCarouselRotationLabel,
    computeCarouselStepLabel,
    computePositionLabel,
} from "@thewaver/ss-playground/App/PageComponents/Announcements/Announcements.const";
import * as styles from "@thewaver/ss-playground/App/Pages/Carousels/Carousels.css";

import type { CarouselExampleProps } from "../../Carousels.types";
import SlideBack from "./SlideBack.vue";
import SlideFront from "./SlideFront.vue";

type Props = Omit<CarouselExampleProps, "isLooping">;

const props = defineProps<Props>();

const index = useModel(props, "index");

const boxRef = shallowRef<HTMLElement>();
const runwayRef = shallowRef<HTMLElement>();

const progress = ElementObserverVueUtils.useScrollContainerProgress(runwayRef, boxRef);
</script>

<template>
    <div id="carouselScrollBox" ref="boxRef" :class="styles.scrollBox">
        <div :class="styles.scrollPinned">
            <Carousel
                v-model:index="index"
                :compute-placement="computePlacement"
                :slides="slides"
                :progress="progress"
                :is-looping="false"
                :is-disabled="isDisabled"
                :orientation="orientation"
                ariaLabel="Scrolled sampler"
                :compute-slide-label="computePositionLabel"
                :compute-step-label="computeCarouselStepLabel"
                :compute-rotation-label="computeCarouselRotationLabel"
            >
                <template #renderSlide="{ slide, state }">
                    <SlideFront :title="slide" :state="state" :frame-class="frameClasses.front" />
                </template>

                <template #renderSlideBack>
                    <SlideBack :frame-class="frameClasses.back" />
                </template>
            </Carousel>
        </div>

        <div ref="runwayRef" :class="styles.scrollRunway" />
    </div>
</template>

// playground-react/src/App/Pages/Carousels/CarouselPage/Examples/Scrolled.tsx
import { useRef } from "react";

import { Carousel, ElementObserverReactUtils } from "@thewaver/ss-components-react";
import {
    computeCarouselRotationLabel,
    computeCarouselStepLabel,
    computePositionLabel,
} from "@thewaver/ss-playground/App/PageComponents/Announcements/Announcements.const";
import * as styles from "@thewaver/ss-playground/App/Pages/Carousels/Carousels.css";

import type { CarouselExampleProps } from "../../Carousels.types";
import { SlideBack, SlideFront } from "./Slide";

const IGNORE = () => undefined;

type Props = Omit<CarouselExampleProps, "isLooping">;

export const ScrolledExample = (props: Props) => {
    const boxRef = useRef<HTMLDivElement | null>(null);
    const runwayRef = useRef<HTMLDivElement | null>(null);

    const progress = ElementObserverReactUtils.useScrollContainerProgress(runwayRef, boxRef);

    return (
        <div ref={boxRef} id={"carouselScrollBox"} className={styles.scrollBox}>
            <div className={styles.scrollPinned}>
                <Carousel
                    computePlacement={props.computePlacement}
                    slides={props.slides}
                    index={props.index}
                    progress={[progress, IGNORE]}
                    isLooping={false}
                    isDisabled={props.isDisabled}
                    orientation={props.orientation}
                    ariaLabel={"Scrolled sampler"}
                    computeSlideLabel={computePositionLabel}
                    computeStepLabel={computeCarouselStepLabel}
                    computeRotationLabel={computeCarouselRotationLabel}
                    renderSlide={(slide, state) => (
                        <SlideFront title={slide} state={state} frameClass={props.frameClasses.front} />
                    )}
                    renderSlideBack={() => <SlideBack frameClass={props.frameClasses.back} />}
                />
            </div>

            <div ref={runwayRef} className={styles.scrollRunway} />
        </div>
    );
};
