// playground-svelte/src/App/Pages/Menus/MenuPage/Examples/Driven.svelte
<script lang="ts">
    import { Button, Menu } from "@thewaver/ss-components-svelte";

    import PageButtonContent from "../../../../StyledComponents/ButtonContent/ButtonContent.svelte";
    import { renderPageHighlightFloater } from "../../../../StyledComponents/GlideFloater/GlideFloater.const.svelte";
    import PageMenuTriggerContent from "../../../../StyledComponents/MenuTriggerContent/MenuTriggerContent.svelte";
    import { ACTIONS, renderMenuItem, renderMenuPopup } from "../MenuPage.const.svelte";
    import type { MenuDrivenExampleProps } from "../MenuPage.types";

    type Props = MenuDrivenExampleProps;

    let { visibility = $bindable(), ...props }: Props = $props();

    let anchorRef = $state<HTMLElement>();
</script>

<Menu
    renderHighlightFloater={renderPageHighlightFloater}
    bind:visibility
    {anchorRef}
    items={ACTIONS}
    ariaLabel={"Edit actions"}
    renderItem={renderMenuItem}
    renderPopup={renderMenuPopup}
    onActivate={props.onActivate}
>
    {#snippet renderContent(flags)}
        <PageMenuTriggerContent {flags}>Edit</PageMenuTriggerContent>
    {/snippet}
</Menu>

<Button
    bind:ref={anchorRef}
    id={"menuToggle"}
    ariaLabel={"Toggle the menu from outside"}
    onClick={() => {
        visibility = !visibility;
    }}
>
    {#snippet renderContent(flags)}
        <PageButtonContent {flags}>{visibility ? "Close it" : "Open it"}</PageButtonContent>
    {/snippet}
</Button>

// playground-react/src/App/Pages/Menus/MenuPage/Examples/Driven.tsx
import { useState } from "react";

import { Button, Menu } from "@thewaver/ss-components-react";

import { PageButtonContent } from "../../../../StyledComponents/ButtonContent/ButtonContent";
import { renderPageHighlightFloater } from "../../../../StyledComponents/GlideFloater/GlideFloater";
import { PageMenuTriggerContent } from "../../../../StyledComponents/MenuTriggerContent/MenuTriggerContent";
import { ACTIONS, renderMenuItem, renderMenuPopup } from "../MenuPage.const";
import type { MenuDrivenExampleProps } from "../MenuPage.types";

type Props = MenuDrivenExampleProps;

export const DrivenExample = (props: Props) => {
    const [anchorRef, setAnchorRef] = useState<HTMLElement>();

    const [isOpen, setIsOpen] = props.visibility;

    return (
        <>
            <Menu
                renderHighlightFloater={renderPageHighlightFloater}
                visibility={props.visibility}
                anchorRef={anchorRef}
                items={ACTIONS}
                ariaLabel={"Edit actions"}
                renderContent={(flags) => <PageMenuTriggerContent flags={flags}>Edit</PageMenuTriggerContent>}
                renderItem={renderMenuItem}
                renderPopup={renderMenuPopup}
                onActivate={props.onActivate}
            />

            <Button
                ref={(element) => setAnchorRef(element ?? undefined)}
                id={"menuToggle"}
                ariaLabel={"Toggle the menu from outside"}
                renderContent={(flags) => (
                    <PageButtonContent flags={flags}>{isOpen ? "Close it" : "Open it"}</PageButtonContent>
                )}
                onClick={() => {
                    setIsOpen(!isOpen);
                }}
            />
        </>
    );
};
