// playground-svelte/src/App/Pages/Menus/MenuPage/Examples/Glide.svelte
<script lang="ts">
    import { Menu } from "@thewaver/ss-components-svelte";

    import PageGlideFloater from "../../../../StyledComponents/GlideFloater/PageGlideFloater.svelte";
    import PageMenuItemContent from "../../../../StyledComponents/MenuItemContent/MenuItemContent.svelte";
    import PageMenuTriggerContent from "../../../../StyledComponents/MenuTriggerContent/MenuTriggerContent.svelte";
    import { ACTIONS, renderMenuPopup } from "../MenuPage.const.svelte";
    import type { MenuExampleProps } from "../MenuPage.types";

    type Props = MenuExampleProps;

    let props: Props = $props();
</script>

<Menu items={ACTIONS} ariaLabel={"Edit actions, gliding"} renderPopup={renderMenuPopup} onActivate={props.onActivate}>
    {#snippet renderContent(flags)}
        <PageMenuTriggerContent {flags}>{"Edit"}</PageMenuTriggerContent>
    {/snippet}

    {#snippet renderItem(item, flags)}
        <PageMenuItemContent
            flags={{ ...flags, isHovered: false, isHighlighted: false }}
            kind={item.kind}
            shortcut={item.value.shortcut ?? ""}
        >
            {item.value.name}
        </PageMenuItemContent>
    {/snippet}

    {#snippet renderHighlightFloater(visibilityTarget, transitionDurationMs)}
        <PageGlideFloater kind={"highlight"} {visibilityTarget} {transitionDurationMs} />
    {/snippet}
</Menu>

// playground-react/src/App/Pages/Menus/MenuPage/Examples/Glide.tsx
import { Menu } from "@thewaver/ss-components-react";

import { PageGlideFloater } from "../../../../StyledComponents/GlideFloater/GlideFloater";
import { PageMenuItemContent } from "../../../../StyledComponents/MenuItemContent/MenuItemContent";
import { PageMenuTriggerContent } from "../../../../StyledComponents/MenuTriggerContent/MenuTriggerContent";
import { ACTIONS, renderMenuPopup } from "../MenuPage.const";
import type { MenuExampleProps } from "../MenuPage.types";

type Props = MenuExampleProps;

export const GlideExample = (props: Props) => {
    return (
        <Menu
            items={ACTIONS}
            ariaLabel={"Edit actions, gliding"}
            renderContent={(flags) => <PageMenuTriggerContent flags={flags}>{"Edit"}</PageMenuTriggerContent>}
            renderItem={(item, flags) => (
                <PageMenuItemContent
                    flags={{ ...flags, isHovered: false, isHighlighted: false }}
                    kind={item.kind}
                    shortcut={item.value.shortcut ?? ""}
                >
                    {item.value.name}
                </PageMenuItemContent>
            )}
            renderHighlightFloater={(visibilityTarget, transitionDurationMs) => (
                <PageGlideFloater
                    kind={"highlight"}
                    visibilityTarget={visibilityTarget}
                    transitionDurationMs={transitionDurationMs}
                />
            )}
            renderPopup={renderMenuPopup}
            onActivate={props.onActivate}
        />
    );
};
