// components/src/Exotics/ScanlineAnimation/ScanlineAnimation.tsx
import { createMemo, splitProps } from "solid-js";

import { access } from "../../Utils/propUtils";
import { CellAnimation } from "../CellAnimation/CellAnimation";
import { SCANLINE_ANIMATION_DEFAULTS } from "./ScanlineAnimation.const";
import type { ScanlineAnimationProps } from "./ScanlineAnimation.types";

export const ScanlineAnimation = (props: ScanlineAnimationProps) => {
    const [local, otherProps] = splitProps(props, ["lineCount", "orientation", "computeScanlineAnimation"]);

    const getOrientation = createMemo(() => access(local.orientation) ?? SCANLINE_ANIMATION_DEFAULTS.orientation);

    return (
        <CellAnimation
            {...otherProps}
            cellCount={() =>
                getOrientation() === "vertical"
                    ? { row: 1, col: access(local.lineCount) }
                    : { row: access(local.lineCount), col: 1 }
            }
            computeCellAnimation={(defs, timeline) => local.computeScanlineAnimation(defs, timeline)}
        />
    );
};

// components-react/src/Exotics/ScanlineAnimation/ScanlineAnimation.tsx
import { SCANLINE_ANIMATION_DEFAULTS } from "@thewaver/ss-components";

import { CellAnimation } from "../CellAnimation/CellAnimation";
import type { ScanlineAnimationProps } from "./ScanlineAnimation.types";

export const ScanlineAnimation = ({
    lineCount,
    orientation,
    computeScanlineAnimation,
    ...otherProps
}: ScanlineAnimationProps) => {
    const isVertical = (orientation ?? SCANLINE_ANIMATION_DEFAULTS.orientation) === "vertical";

    return (
        <CellAnimation
            {...otherProps}
            cellCount={isVertical ? { row: 1, col: lineCount } : { row: lineCount, col: 1 }}
            computeCellAnimation={computeScanlineAnimation}
        />
    );
};
