// playground-svelte/src/App/AppContent.svelte
<script lang="ts">
    import { Router } from "sv-router";
    import { untrack } from "svelte";

    import { Sidebar, Tree } from "@thewaver/ss-components-svelte";
    import type { SidebarPhase, TreeNode } from "@thewaver/ss-components-svelte";
    import * as styles from "@thewaver/ss-playground/App/App.css";
    import { restoreRootSlash } from "@thewaver/ss-playground/App/PageComponents/FrameworkSwitch/FrameworkSwitch.const";
    import { IS_BUILD_PROGRESS_SHOWN } from "@thewaver/ss-playground/App/PageComponents/BuildProgress/BuildProgress.utils";
    import {
        DEFAULT_PAGE_VIEW,
        PAGE_VIEW_KEYS,
        toBaseRoute,
    } from "@thewaver/ss-playground/App/PageComponents/ViewTabs/ViewTabs.const";

    import {
        MENU_COLLAPSED_WIDTH,
        MENU_CONFIGS,
        MENU_EDGE,
        MENU_EXPANDED_WIDTH,
        MENU_ID,
        SEARCH_FIELD_WIDTH,
    } from "./App.const";
    import {
        COMPONENT_CONFIGS_BY_ROUTE,
        componentToRouteName,
        flattenConfigs,
        getIsBranchConfig,
        route,
        toPageHref,
    } from "./App.router";
    import type { ComponentConfig, MenuBranchConfig, MenuNodeConfig } from "./App.types";
    import PageTextField from "./PageComponents/Field/PageTextField.svelte";
    import PageBuildProgress from "./PageComponents/BuildProgress/PageBuildProgress.svelte";
    import PageFrameworkMenu from "./PageComponents/FrameworkMenu/FrameworkMenu.svelte";
    import PageLayer from "./PageComponents/Layer/Layer.svelte";
    import PageNavLink from "./PageComponents/NavLink/NavLink.svelte";
    import type { ViewportAnchor } from "./PageComponents/NavSettings/NavSettings.types";
    import PageNavSettings from "./PageComponents/NavSettings/PageNavSettings.svelte";
    import PageRouterLink from "./PageComponents/RouterLink/RouterLink.svelte";
    import PageSidebarToggle from "./PageComponents/SidebarToggle/SidebarToggle.svelte";
    import PageViewTabs from "./PageComponents/ViewTabs/PageViewTabs.svelte";
    import type { PageViewKey } from "./PageComponents/ViewTabs/ViewTabs.types";
    import PageDependencies from "./PageDependencies.svelte";
    import PageTreeNodeContent from "./StyledComponents/TreeNodeContent/PageTreeNodeContent.svelte";

    const getIsMenuFaded = (phase: SidebarPhase) => phase === "collapsing" || phase === "collapsed";

    const toTreeNode =
        (view: PageViewKey) =>
        (node: MenuNodeConfig): TreeNode<MenuNodeConfig> =>
            getIsBranchConfig(node)
                ? { value: node, children: node.children.map(toTreeNode(view)) }
                : { value: node, href: toPageHref(node, view) };

    const collectAncestors = (
        nodes: MenuNodeConfig[],
        trail: MenuBranchConfig[],
        into: Map<MenuNodeConfig, MenuBranchConfig[]>,
    ) => {
        for (const node of nodes) {
            into.set(node, trail);

            if (getIsBranchConfig(node)) collectAncestors(node.children, [...trail, node], into);
        }
    };

    const filterTreeNode = (
        node: TreeNode<MenuNodeConfig>,
        getIsKept: (config: ComponentConfig) => boolean,
    ): TreeNode<MenuNodeConfig> | undefined => {
        if (!node.children) return getIsKept(node.value as ComponentConfig) ? node : undefined;

        const children = node.children
            .map((child) => filterTreeNode(child, getIsKept))
            .filter((child): child is TreeNode<MenuNodeConfig> => child !== undefined);

        return children.length > 0 ? { ...node, children } : undefined;
    };

    const collectBranchValues = (nodes: TreeNode<MenuNodeConfig>[]): MenuNodeConfig[] =>
        nodes.flatMap((node) => (node.children ? [node.value, ...collectBranchValues(node.children)] : []));

    const VISIBLE_MENU_CONFIGS = MENU_CONFIGS.filter((category) => !category.hidden);

    const MENU_NODES_BY_VIEW = Object.fromEntries(
        PAGE_VIEW_KEYS.map((view) => [view, VISIBLE_MENU_CONFIGS.map(toTreeNode(view))]),
    ) as Record<PageViewKey, TreeNode<MenuNodeConfig>[]>;

    const ANCESTORS_BY_CONFIG = new Map<MenuNodeConfig, MenuBranchConfig[]>();

    collectAncestors(VISIBLE_MENU_CONFIGS, [], ANCESTORS_BY_CONFIG);

    let { viewportAnchor = $bindable() }: { viewportAnchor: ViewportAnchor } = $props();

    let searchTerm = $state("");
    let showsDescriptionOnly = $state(false);
    let pageView = $state<PageViewKey>(DEFAULT_PAGE_VIEW);
    let isAutoHidden = $state(false);
    let browseExpanded = $state.raw<MenuNodeConfig[]>(VISIBLE_MENU_CONFIGS);

    const selectedConfig = $derived(COMPONENT_CONFIGS_BY_ROUTE[toBaseRoute(route.pathname)]);

    const isAboutSelected = $derived(route.pathname === "/");

    $effect(() => {
        void route.pathname;

        restoreRootSlash();
    });

    const isSearching = $derived(searchTerm.trim().length > 0);

    const visibleNodes = $derived.by(() => {
        const menuNodes = MENU_NODES_BY_VIEW[pageView];

        if (!isSearching && showsDescriptionOnly) return menuNodes;

        const term = searchTerm.trim().toLocaleLowerCase();

        const getIsKept = (config: ComponentConfig) => {
            if (config === selectedConfig) return true;

            if (isSearching) return config.name.toLocaleLowerCase().includes(term);

            return showsDescriptionOnly || config.component !== undefined;
        };

        return menuNodes
            .map((node) => filterTreeNode(node, getIsKept))
            .filter((node): node is TreeNode<MenuNodeConfig> => node !== undefined);
    });

    let searchExpanded = $derived(isSearching ? collectBranchValues(visibleNodes) : []);

    $effect.pre(() => {
        const config = selectedConfig;

        untrack(() => {
            const ancestors = config ? (ANCESTORS_BY_CONFIG.get(config) ?? []) : [];

            if (ancestors.length === 0) return;

            browseExpanded = [...browseExpanded, ...ancestors.filter((ancestor) => !browseExpanded.includes(ancestor))];
        });
    });

    const isMenuExpanded = $derived(!isAutoHidden);
</script>

<div class={styles.appFrame}>
    {#if IS_BUILD_PROGRESS_SHOWN}
        <PageBuildProgress />
    {/if}

    <div class={styles.appContent}>
        <Sidebar
            id={MENU_ID}
            edge={MENU_EDGE}
            collapsedSize={MENU_COLLAPSED_WIDTH}
            expandedSize={MENU_EXPANDED_WIDTH}
            isExpandedOnHover={isAutoHidden}
            bind:expanded={
                () => isMenuExpanded,
                (isExpanded) => {
                    isAutoHidden = !isExpanded;
                }
            }
        >
            {#snippet renderContent(phase, transitionDurationMs)}
                <nav class={styles.leftMenu} aria-label={"Library"}>
                    <PageLayer level={1}>
                        <div class={styles.leftMenuContent}>
                            <div class={styles.searchContainer}>
                                <PageSidebarToggle
                                    sidebarId={MENU_ID}
                                    edge={MENU_EDGE}
                                    isExpanded={isMenuExpanded}
                                    ariaLabel={isMenuExpanded ? "Auto-hide the menu" : "Keep the menu open"}
                                    onToggle={() => {
                                        isAutoHidden = isMenuExpanded;
                                    }}
                                />

                                <div
                                    class={[
                                        styles.frameworkHeading,
                                        getIsMenuFaded(phase) && styles.isFaded,
                                        phase === "collapsed" && styles.isHidden,
                                    ]}
                                    style:transition-duration={`${transitionDurationMs}ms`}
                                >
                                    <span class={styles.frameworkHeadingLabel}>ss-components for</span>

                                    <PageFrameworkMenu />
                                </div>
                            </div>

                            <div class={styles.searchContainer}>
                                <div class={styles.navSettingsBox}>
                                    <PageNavSettings bind:showsDescriptionOnly bind:pageView bind:viewportAnchor />
                                </div>

                                <div
                                    class={[
                                        styles.searchFields,
                                        getIsMenuFaded(phase) && styles.isFaded,
                                        phase === "collapsed" && styles.isHidden,
                                    ]}
                                    style:transition-duration={`${transitionDurationMs}ms`}
                                >
                                    <PageTextField
                                        value={searchTerm}
                                        width={SEARCH_FIELD_WIDTH}
                                        placeholder={"Search"}
                                        ariaLabel={"Search components"}
                                        onInput={(value) => {
                                            searchTerm = value;
                                        }}
                                    />
                                </div>
                            </div>

                            <div
                                class={[
                                    styles.aboutLink,
                                    getIsMenuFaded(phase) && styles.isFaded,
                                    phase === "collapsed" && styles.isHidden,
                                ]}
                                style:transition-duration={`${transitionDurationMs}ms`}
                            >
                                <PageNavLink href={"/"} isSelected={isAboutSelected}>About</PageNavLink>
                            </div>

                            <div
                                class={[
                                    styles.menuTree,
                                    getIsMenuFaded(phase) && styles.isFaded,
                                    phase === "collapsed" && styles.isHidden,
                                ]}
                                style:transition-duration={`${transitionDurationMs}ms`}
                            >
                                <Tree
                                    nodes={visibleNodes}
                                    bind:value={() => selectedConfig as MenuNodeConfig | undefined, () => undefined}
                                    bind:expanded={
                                        () => (isSearching ? searchExpanded : browseExpanded),
                                        (next) => {
                                            if (isSearching) searchExpanded = next ?? [];
                                            else browseExpanded = next ?? [];
                                        }
                                    }
                                    ariaLabel={"Library"}
                                    linkComponent={PageRouterLink}
                                    computeCustomText={(node) => node.value.name}
                                >
                                    {#snippet renderNode(node, renderProps)}
                                        <PageTreeNodeContent
                                            {renderProps}
                                            hasExamples={getIsBranchConfig(node.value) ||
                                                node.value.component !== undefined}
                                            detail={getIsBranchConfig(node.value)
                                                ? `${flattenConfigs(node.value.children).length}`
                                                : ""}
                                        >
                                            {node.value.name}
                                        </PageTreeNodeContent>
                                    {/snippet}
                                </Tree>
                            </div>
                        </div>
                    </PageLayer>
                </nav>
            {/snippet}
        </Sidebar>

        <main class={styles.pageColumn}>
            {#if selectedConfig}
                <div class={styles.pageBody}>
                    <div class={styles.pageHeader}>
                        <h1 class={styles.pageTitle}>{selectedConfig.name}</h1>

                        <PageDependencies name={selectedConfig.name} view={pageView} />

                        <PageViewTabs
                            baseRoute={componentToRouteName(selectedConfig.name)}
                            hasExamples={selectedConfig.component !== undefined}
                        />
                    </div>

                    <Router />
                </div>
            {:else}
                <Router />
            {/if}
        </main>
    </div>
</div>

// playground-vue/src/App/AppContent.vue
<script setup lang="ts">
import { computed, shallowRef, watch } from "vue";
import { useRoute } from "vue-router";

import { Sidebar, Tree } from "@thewaver/ss-components-vue";
import type { TreeNode } from "@thewaver/ss-components-vue";
import * as styles from "@thewaver/ss-playground/App/App.css";
import { IS_BUILD_PROGRESS_SHOWN } from "@thewaver/ss-playground/App/PageComponents/BuildProgress/BuildProgress.utils";
import { DEFAULT_PAGE_VIEW, toBaseRoute } from "@thewaver/ss-playground/App/PageComponents/ViewTabs/ViewTabs.const";

import { MENU_COLLAPSED_WIDTH, MENU_EDGE, MENU_EXPANDED_WIDTH, MENU_ID, SEARCH_FIELD_WIDTH } from "./App.const";
import type { ComponentConfig, MenuNodeConfig } from "./App.types";
import { AppUtils } from "./App.utils";
import PageBuildProgress from "./PageComponents/BuildProgress/PageBuildProgress.vue";
import PageTextField from "./PageComponents/Field/PageTextField.vue";
import PageFrameworkMenu from "./PageComponents/FrameworkMenu/FrameworkMenu.vue";
import PageLayer from "./PageComponents/Layer/Layer.vue";
import PageNavLink from "./PageComponents/NavLink/NavLink.vue";
import type { ViewportAnchor } from "./PageComponents/NavSettings/NavSettings.types";
import PageNavSettings from "./PageComponents/NavSettings/PageNavSettings.vue";
import PageRouterLink from "./PageComponents/RouterLink/RouterLink.vue";
import PageSidebarToggle from "./PageComponents/SidebarToggle/SidebarToggle.vue";
import PageViewTabs from "./PageComponents/ViewTabs/PageViewTabs.vue";
import type { PageViewKey } from "./PageComponents/ViewTabs/ViewTabs.types";
import PageDependencies from "./PageDependencies.vue";
import PageTreeNodeContent from "./StyledComponents/TreeNodeContent/PageTreeNodeContent.vue";

const viewportAnchor = defineModel<ViewportAnchor>("viewportAnchor", { required: true });

const route = useRoute();

const searchTerm = shallowRef("");
const showsDescriptionOnly = shallowRef(false);
const pageView = shallowRef<PageViewKey>(DEFAULT_PAGE_VIEW);
const isAutoHidden = shallowRef(false);
const browseExpanded = shallowRef<MenuNodeConfig[]>(AppUtils.VISIBLE_MENU_CONFIGS);
const searchExpanded = shallowRef<MenuNodeConfig[]>([]);

const selectedConfig = computed(() => AppUtils.COMPONENT_CONFIGS_BY_ROUTE[toBaseRoute(route.path)]);

const isAboutSelected = computed(() => route.path === "/");

const isSearching = computed(() => searchTerm.value.trim().length > 0);

const visibleNodes = computed(() => {
    const menuNodes = AppUtils.MENU_NODES_BY_VIEW[pageView.value];

    if (!isSearching.value && showsDescriptionOnly.value) return menuNodes;

    const term = searchTerm.value.trim().toLocaleLowerCase();

    const getIsKept = (config: ComponentConfig) => {
        if (config === selectedConfig.value) return true;

        if (isSearching.value) return config.name.toLocaleLowerCase().includes(term);

        return showsDescriptionOnly.value || config.component !== undefined;
    };

    return menuNodes
        .map((node) => AppUtils.filterTreeNode(node, getIsKept))
        .filter((node): node is TreeNode<MenuNodeConfig> => node !== undefined);
});

watch(
    () => (isSearching.value ? visibleNodes.value : undefined),
    (searchNodes) => {
        if (searchNodes) searchExpanded.value = AppUtils.collectBranchValues(searchNodes);
    },
    { immediate: true },
);

watch(
    selectedConfig,
    (config) => {
        const ancestors = config ? (AppUtils.ANCESTORS_BY_CONFIG.get(config) ?? []) : [];

        if (ancestors.length === 0) return;

        const previous = browseExpanded.value;

        browseExpanded.value = [...previous, ...ancestors.filter((ancestor) => !previous.includes(ancestor))];
    },
    { immediate: true },
);

const isMenuExpanded = computed(() => !isAutoHidden.value);

const setIsMenuExpanded = (isExpanded: boolean) => {
    isAutoHidden.value = !isExpanded;
};

const setExpanded = (next: unknown[]) => {
    if (isSearching.value) searchExpanded.value = next as MenuNodeConfig[];
    else browseExpanded.value = next as MenuNodeConfig[];
};

const refuseSelection = () => undefined;

const computeNodeText = (node: TreeNode<unknown>) => (node.value as MenuNodeConfig).name;
</script>

<template>
    <div :class="styles.appFrame">
        <PageBuildProgress v-if="IS_BUILD_PROGRESS_SHOWN" />

        <div :class="styles.appContent">
            <Sidebar
                :id="MENU_ID"
                :edge="MENU_EDGE"
                :collapsed-size="MENU_COLLAPSED_WIDTH"
                :expanded-size="MENU_EXPANDED_WIDTH"
                :is-expanded-on-hover="isAutoHidden"
                :expanded="isMenuExpanded"
                @update:expanded="setIsMenuExpanded"
            >
                <template #renderContent="{ phase, transitionDurationMs }">
                    <nav :class="styles.leftMenu" aria-label="Library">
                        <PageLayer :level="1">
                            <div :class="styles.leftMenuContent">
                                <div :class="styles.searchContainer">
                                    <PageSidebarToggle
                                        :sidebar-id="MENU_ID"
                                        :edge="MENU_EDGE"
                                        :is-expanded="isMenuExpanded"
                                        :ariaLabel="isMenuExpanded ? 'Auto-hide the menu' : 'Keep the menu open'"
                                        @toggle="setIsMenuExpanded(!isMenuExpanded)"
                                    />

                                    <div
                                        :class="[
                                            styles.frameworkHeading,
                                            AppUtils.getIsMenuFaded(phase) && styles.isFaded,
                                            phase === 'collapsed' && styles.isHidden,
                                        ]"
                                        :style="{ transitionDuration: `${transitionDurationMs}ms` }"
                                    >
                                        <span :class="styles.frameworkHeadingLabel">ss-components for</span>

                                        <PageFrameworkMenu />
                                    </div>
                                </div>

                                <div :class="styles.searchContainer">
                                    <div :class="styles.navSettingsBox">
                                        <PageNavSettings
                                            v-model:shows-description-only="showsDescriptionOnly"
                                            v-model:page-view="pageView"
                                            v-model:viewport-anchor="viewportAnchor"
                                        />
                                    </div>

                                    <div
                                        :class="[
                                            styles.searchFields,
                                            AppUtils.getIsMenuFaded(phase) && styles.isFaded,
                                            phase === 'collapsed' && styles.isHidden,
                                        ]"
                                        :style="{ transitionDuration: `${transitionDurationMs}ms` }"
                                    >
                                        <PageTextField
                                            :value="searchTerm"
                                            :width="SEARCH_FIELD_WIDTH"
                                            placeholder="Search"
                                            ariaLabel="Search components"
                                            @input="(value: string) => (searchTerm = value)"
                                        />
                                    </div>
                                </div>

                                <div
                                    :class="[
                                        styles.aboutLink,
                                        AppUtils.getIsMenuFaded(phase) && styles.isFaded,
                                        phase === 'collapsed' && styles.isHidden,
                                    ]"
                                    :style="{ transitionDuration: `${transitionDurationMs}ms` }"
                                >
                                    <PageNavLink href="/" :is-selected="isAboutSelected">About</PageNavLink>
                                </div>

                                <div
                                    :class="[
                                        styles.menuTree,
                                        AppUtils.getIsMenuFaded(phase) && styles.isFaded,
                                        phase === 'collapsed' && styles.isHidden,
                                    ]"
                                    :style="{ transitionDuration: `${transitionDurationMs}ms` }"
                                >
                                    <Tree
                                        :nodes="visibleNodes"
                                        :value="selectedConfig"
                                        :expanded="isSearching ? searchExpanded : browseExpanded"
                                        ariaLabel="Library"
                                        :link-component="PageRouterLink"
                                        :compute-custom-text="computeNodeText"
                                        @update:value="refuseSelection"
                                        @update:expanded="setExpanded"
                                    >
                                        <template #renderNode="{ node, renderProps }">
                                            <PageTreeNodeContent
                                                :render-props="renderProps"
                                                :has-examples="
                                                    AppUtils.getIsBranchConfig(node.value) ||
                                                    node.value.component !== undefined
                                                "
                                                :detail="
                                                    AppUtils.getIsBranchConfig(node.value)
                                                        ? `${AppUtils.flattenConfigs(node.value.children).length}`
                                                        : ''
                                                "
                                            >
                                                {{ node.value.name }}
                                            </PageTreeNodeContent>
                                        </template>
                                    </Tree>
                                </div>
                            </div>
                        </PageLayer>
                    </nav>
                </template>
            </Sidebar>

            <main :class="styles.pageColumn">
                <div v-if="selectedConfig" :class="styles.pageBody">
                    <div :class="styles.pageHeader">
                        <h1 :class="styles.pageTitle">{{ selectedConfig.name }}</h1>

                        <PageDependencies :name="selectedConfig.name" :view="pageView" />

                        <PageViewTabs
                            :base-route="AppUtils.componentToRouteName(selectedConfig.name)"
                            :has-examples="selectedConfig.component !== undefined"
                        />
                    </div>

                    <RouterView />
                </div>

                <RouterView v-else />
            </main>
        </div>
    </div>
</template>
