// playground-react/src/App/Pages/TreePage/Examples/Files.tsx
import { Tree } from "@thewaver/ss-components-react";
import type { TreeNode } from "@thewaver/ss-components-react";

import { renderPageHighlightFloater } from "../../../StyledComponents/GlideFloater/GlideFloater";
import { PageTreeNodeContent } from "../../../StyledComponents/TreeNodeContent/TreeNodeContent";
import { FILES } from "../TreePage.const";
import type { TreeExampleProps } from "../TreePage.types";

type Props = Partial<TreeExampleProps> & { nodes?: TreeNode<string>[] };

export const FilesExample = (props: Props) => {
    return (
        <Tree
            renderHighlightFloater={renderPageHighlightFloater}
            nodes={props.nodes ?? FILES}
            value={props.value}
            expanded={props.expanded}
            ariaLabel={"Repository"}
            renderNode={(node, renderProps) => (
                <PageTreeNodeContent isGliding renderProps={renderProps}>
                    {node.value}
                </PageTreeNodeContent>
            )}
        />
    );
};

// playground-svelte/src/App/Pages/TreePage/Examples/Files.svelte
<script lang="ts">
    import { Tree } from "@thewaver/ss-components-svelte";
    import type { TreeNode } from "@thewaver/ss-components-svelte";

    import { renderPageHighlightFloater } from "../../../StyledComponents/GlideFloater/GlideFloater.const.svelte";
    import PageTreeNodeContent from "../../../StyledComponents/TreeNodeContent/PageTreeNodeContent.svelte";
    import { FILES } from "../TreePage.const.svelte";
    import type { TreeExampleProps } from "../TreePage.types";

    type Props = Partial<TreeExampleProps> & { nodes?: TreeNode<string>[] };

    let { value = $bindable(), expanded = $bindable([]), ...props }: Props = $props();
</script>

<Tree
    renderHighlightFloater={renderPageHighlightFloater}
    nodes={props.nodes ?? FILES}
    bind:value
    bind:expanded
    ariaLabel={"Repository"}
>
    {#snippet renderNode(node, renderProps)}
        <PageTreeNodeContent isGliding {renderProps}>{node.value}</PageTreeNodeContent>
    {/snippet}
</Tree>
