// components-solid/src/Exotics/FlipCard/FlipCard.tsx
import { createMemo, on } from "solid-js";

import {
    FLIP_CARD_DEFAULTS,
    type FlipCardFace,
    type FlipCardState,
    FlipCardUtils,
    FlipCardStyles as styles,
} from "@thewaver/ss-components";

import { Barrel } from "../../Primitives/Barrel/Barrel";
import { access, accessSignal } from "../../Utils/propUtils";
import type { FlipCardProps } from "./FlipCardSolid.types";

export const FlipCard = (props: FlipCardProps) => {
    const [getIsFlipped] = accessSignal(() => props.flipped);

    const getShownFace = createMemo(() => FlipCardUtils.getShownFace(getIsFlipped()));

    const getRestingAngle = createMemo(
        on(getIsFlipped, (isFlipped, _, angle?: number) =>
            FlipCardUtils.computeRestingAngle(angle, isFlipped, access(props.turnDirection)),
        ),
    );

    const getPeekRatio = createMemo(() =>
        FlipCardUtils.getPeekRatio(access(props.peekRatio) ?? FLIP_CARD_DEFAULTS.peekRatio),
    );

    const getAngle = createMemo(() =>
        FlipCardUtils.computeAngle(getRestingAngle(), getIsFlipped(), getPeekRatio(), access(props.turnDirection)),
    );

    const getTransitionDurationMs = createMemo(() =>
        FlipCardUtils.getTransitionDurationMs(
            getPeekRatio(),
            access(props.transitionDurationMs) ?? FLIP_CARD_DEFAULTS.transitionDurationMs,
        ),
    );

    const getFaceLabel = (face: FlipCardFace) => props.computeFaceLabel(face);

    const getState = (face: FlipCardFace): FlipCardState => ({
        face,
        isShowing: face === getShownFace(),
    });

    return (
        <div
            class={styles.flipCardRoot}
            role="group"
            aria-roledescription={access(props.roleDescription) ?? FLIP_CARD_DEFAULTS.roleDescription}
            aria-label={access(props.ariaLabel)}
        >
            <Barrel<FlipCardFace>
                faces={[...FlipCardUtils.FACES]}
                axis={() => access(props.axis) ?? FLIP_CARD_DEFAULTS.axis}
                faceSize={() => access(props.size)}
                angle={getAngle}
                transitionDurationMs={getTransitionDurationMs}
                faceRoleDescription={() => access(props.faceRoleDescription) ?? FLIP_CARD_DEFAULTS.faceRoleDescription}
                computeFaceDefs={(index) => ({
                    ariaLabel: getFaceLabel(FlipCardUtils.FACES[index]!),
                    isHidden: FlipCardUtils.FACES[index] !== getShownFace(),
                })}
                renderFace={(getFace) =>
                    getFace() === "back"
                        ? props.renderBack(() => getState("back"))
                        : props.renderFront(() => getState("front"))
                }
            />
        </div>
    );
};

// components-react/src/Exotics/FlipCard/FlipCard.tsx
import { useState } from "react";

import {
    FLIP_CARD_DEFAULTS,
    type FlipCardFace,
    type FlipCardState,
    FlipCardStyles,
    FlipCardUtils,
} from "@thewaver/ss-components";

import { Barrel } from "../../Primitives/Barrel/Barrel";
import type { FlipCardProps } from "./FlipCard.types";

export const FlipCard = (props: FlipCardProps) => {
    const [isFlipped] = props.flipped;

    const [rest, setRest] = useState(() => ({
        angle: FlipCardUtils.computeRestingAngle(undefined, isFlipped, props.turnDirection),
        isFlipped,
    }));

    if (rest.isFlipped !== isFlipped) {
        setRest({
            angle: FlipCardUtils.computeRestingAngle(rest.angle, isFlipped, props.turnDirection),
            isFlipped,
        });
    }

    const shownFace = FlipCardUtils.getShownFace(isFlipped);
    const peekRatio = FlipCardUtils.getPeekRatio(props.peekRatio ?? FLIP_CARD_DEFAULTS.peekRatio);
    const angle = FlipCardUtils.computeAngle(rest.angle, isFlipped, peekRatio, props.turnDirection);
    const transitionDurationMs = FlipCardUtils.getTransitionDurationMs(
        peekRatio,
        props.transitionDurationMs ?? FLIP_CARD_DEFAULTS.transitionDurationMs,
    );

    const getState = (face: FlipCardFace): FlipCardState => ({ face, isShowing: face === shownFace });

    return (
        <div
            className={FlipCardStyles.flipCardRoot}
            role="group"
            aria-roledescription={props.roleDescription ?? FLIP_CARD_DEFAULTS.roleDescription}
            aria-label={props.ariaLabel}
        >
            <Barrel<FlipCardFace>
                faces={[...FlipCardUtils.FACES]}
                axis={props.axis ?? FLIP_CARD_DEFAULTS.axis}
                faceSize={props.size}
                angle={angle}
                transitionDurationMs={transitionDurationMs}
                faceRoleDescription={props.faceRoleDescription ?? FLIP_CARD_DEFAULTS.faceRoleDescription}
                computeFaceDefs={(index) => ({
                    ariaLabel: props.computeFaceLabel(FlipCardUtils.FACES[index]!),
                    isHidden: FlipCardUtils.FACES[index] !== shownFace,
                })}
                renderFace={(face) =>
                    face === "back" ? props.renderBack(getState("back")) : props.renderFront(getState("front"))
                }
            />
        </div>
    );
};
