// components-solid/src/Exotics/PointerEffects/LightCatcher/LightCatcher.tsx
import type { ParentProps } from "solid-js";
import { createMemo, createSignal } from "solid-js";

import { LIGHT_CATCHER_DEFAULTS, PointerEffectsUtils, LightCatcherStyles as styles } from "@thewaver/ss-components";

import { PointerTrackerSolidUtils } from "../../../Abstracts/PointerTracker/PointerTrackerSolid.utils";
import { SmootherSolidUtils } from "../../../Abstracts/Smoother/SmootherSolid.utils";
import { access } from "../../../Utils/propUtils";
import type { LightCatcherProps } from "./LightCatcherSolid.types";

const NO_STRENGTH = 0;

export const LightCatcher = (props: ParentProps<LightCatcherProps>) => {
    const [getRef, setRef] = createSignal<HTMLElement>();

    const getIsDisabled = createMemo(() => access(props.isDisabled) ?? false);

    const { getReading, getIsPointerPresent } = PointerTrackerSolidUtils.create(getRef, getIsDisabled, () =>
        access(props.pointSource),
    );

    const getIsResting = createMemo(() =>
        PointerEffectsUtils.getIsResting(
            getIsDisabled(),
            getIsPointerPresent(),
            getReading(),
            access(props.activeRangePx),
        ),
    );

    const getStrength = createMemo(() =>
        getIsResting()
            ? NO_STRENGTH
            : PointerEffectsUtils.computeEdgeStrength(
                  getReading(),
                  access(props.lightRangePx) ?? LIGHT_CATCHER_DEFAULTS.lightRangePx,
              ),
    );

    const getEased = SmootherSolidUtils.create(
        () => [getStrength()],
        () => access(props.smoothingMs) ?? LIGHT_CATCHER_DEFAULTS.smoothingMs,
    );

    const getFilter = createMemo(() => {
        const [strength] = getEased();

        return PointerEffectsUtils.computeLightFilter(strength, {
            restingBrightness: access(props.restingBrightness),
            maxBrightness: access(props.maxBrightness),
            restingLightness: access(props.restingLightness),
            maxLightness: access(props.maxLightness),
        });
    });

    return (
        <div ref={setRef} class={styles.lightCatcherRoot} style={{ filter: getFilter() }}>
            {props.children}
        </div>
    );
};

// components-svelte/src/Exotics/PointerEffects/LightCatcher/LightCatcher.svelte
<script lang="ts">
    import { LIGHT_CATCHER_DEFAULTS, PointerEffectsUtils, LightCatcherStyles as styles } from "@thewaver/ss-components";

    import { PointerTrackerSvelteUtils } from "../../../Abstracts/PointerTracker/PointerTrackerSvelte.utils.svelte.js";
    import { SmootherSvelteUtils } from "../../../Abstracts/Smoother/SmootherSvelte.utils.svelte.js";
    import type { LightCatcherProps } from "./LightCatcher.types.js";

    const NO_STRENGTH = 0;

    let props: LightCatcherProps = $props();

    let element = $state<HTMLDivElement>();

    const isDisabled = $derived(props.isDisabled ?? false);

    const pointer = PointerTrackerSvelteUtils.create(
        () => element ?? undefined,
        () => isDisabled,
        () => props.pointSource,
    );

    const isResting = $derived(
        PointerEffectsUtils.getIsResting(
            isDisabled,
            pointer.getIsPointerPresent(),
            pointer.getReading(),
            props.activeRangePx,
        ),
    );

    const strength = $derived(
        isResting
            ? NO_STRENGTH
            : PointerEffectsUtils.computeEdgeStrength(
                  pointer.getReading(),
                  props.lightRangePx ?? LIGHT_CATCHER_DEFAULTS.lightRangePx,
              ),
    );

    const getEased = SmootherSvelteUtils.create(
        () => [strength],
        () => props.smoothingMs ?? LIGHT_CATCHER_DEFAULTS.smoothingMs,
    );
</script>

<div
    bind:this={element}
    class={styles.lightCatcherRoot}
    style:filter={PointerEffectsUtils.computeLightFilter(getEased()[0], props)}
>
    {@render props.children?.()}
</div>
