// playground/src/App/StyledComponents/ColorAreaContent/ColorAreaContent.tsx
import type { ParentProps } from "solid-js";

import { access } from "@thewaver/ss-components";
import { assignInlineVars } from "@vanilla-extract/dynamic";

import { useLayerClass } from "../Layer/Layer.context";
import type {
    ColorAreaContentProps,
    ColorFieldTriggerProps,
    ColorSwatchProps,
    HueSliderProps,
} from "./ColorAreaContent.types";

import * as styles from "./ColorAreaContent.css";

const PERCENT = 100;

export const PageColorAreaContent = (props: ColorAreaContentProps) => {
    const getLayerClass = useLayerClass();

    return (
        <div
            class={styles.colorAreaSquare}
            classList={{
                [getLayerClass()]: true,
                [styles.isDragging]: access(props.renderProps).isDragging,
                [styles.isFocused]: access(props.renderProps).focusVisibleAxis !== undefined,
                [styles.isDisabled]: access(props.renderProps).isDisabled,
            }}
            style={{
                ...assignInlineVars({
                    [styles.hueVar]: `${access(props.renderProps).hsv.h}deg`,
                    [styles.thumbXVar]: `${access(props.renderProps).hsv.s}%`,
                    [styles.thumbYVar]: `${PERCENT - access(props.renderProps).hsv.v}%`,
                }),
                height: `${access(props.size)}px`,
            }}
        >
            <div class={styles.colorAreaThumb} />
        </div>
    );
};

const HUE_THUMB_SIZE = 18;
const HUE_MAX = 360;

export const PageHueSlider = (props: HueSliderProps) => {
    const getLayerClass = useLayerClass();

    return (
        <div class={[styles.hueSlider, getLayerClass()].join(" ")}>
            <div class={styles.hueTrack} />

            <div
                class={styles.hueThumb}
                classList={{ [styles.isFocused]: access(props.renderProps).focusVisibleThumb === 0 }}
                style={{
                    ...assignInlineVars({
                        [styles.swatchVar]: `hsl(${access(props.renderProps).values[0] % HUE_MAX} 100% 50%)`,
                    }),
                    left: `calc(${access(props.renderProps).ratios[0]} * (100% - ${HUE_THUMB_SIZE}px))`,
                }}
            />
        </div>
    );
};

export const PageColorSwatch = (props: ColorSwatchProps) => {
    const getLayerClass = useLayerClass();

    return (
        <div class={[styles.colorSwatchChecker, getLayerClass()].join(" ")}>
            <div class={styles.colorSwatch} style={assignInlineVars({ [styles.swatchVar]: access(props.value) })} />
        </div>
    );
};

export const PageColorChannelGrid = (props: ParentProps) => {
    const getLayerClass = useLayerClass();

    return <div class={[styles.colorChannels, getLayerClass()].join(" ")}>{props.children}</div>;
};

export const PageColorChannel = (props: ParentProps<{ label: string }>) => {
    const getLayerClass = useLayerClass();

    return (
        <div class={[styles.colorChannel, getLayerClass()].join(" ")}>
            <div class={styles.colorChannelLabel} aria-hidden="true">
                {props.label}
            </div>

            {props.children}
        </div>
    );
};

export const PageColorPickerPopup = (props: ParentProps) => {
    const getLayerClass = useLayerClass();

    return <div class={[styles.colorPickerPopup, getLayerClass()].join(" ")}>{props.children}</div>;
};

export const PageColorPickerRow = (props: ParentProps) => {
    const getLayerClass = useLayerClass();

    return <div class={[styles.colorPickerRow, getLayerClass()].join(" ")}>{props.children}</div>;
};

export const PageColorFieldTrigger = (props: ParentProps<ColorFieldTriggerProps>) => {
    const getLayerClass = useLayerClass();

    return (
        <div
            class={styles.colorFieldTrigger}
            classList={{
                [getLayerClass()]: true,
                [styles.isHovered]: access(props.flags).isHovered,
                [styles.isDisabled]: access(props.flags).isDisabled,
            }}
        >
            {props.children}
        </div>
    );
};

export const PageColorPreview = (props: ColorSwatchProps) => {
    const getLayerClass = useLayerClass();

    return (
        <div class={[styles.colorPreviewChecker, getLayerClass()].join(" ")}>
            <div class={styles.colorPreview} style={assignInlineVars({ [styles.swatchVar]: access(props.value) })} />
        </div>
    );
};

// playground-react/src/App/StyledComponents/ColorAreaContent/ColorAreaContent.tsx
import type { CSSProperties, PropsWithChildren } from "react";

import * as styles from "@thewaver/ss-playground/App/StyledComponents/ColorAreaContent/ColorAreaContent.css";
import { assignInlineVars } from "@vanilla-extract/dynamic";

import { useLayerClass } from "../Layer/Layer.context";
import type {
    ColorAreaContentProps,
    ColorFieldTriggerProps,
    ColorSwatchProps,
    HueSliderProps,
} from "./ColorAreaContent.types";

const PERCENT = 100;

export const PageColorAreaContent = (props: ColorAreaContentProps) => {
    const layerClass = useLayerClass();

    return (
        <div
            className={[
                styles.colorAreaSquare,
                layerClass,
                props.renderProps.isDragging && styles.isDragging,
                props.renderProps.focusVisibleAxis !== undefined && styles.isFocused,
                props.renderProps.isDisabled && styles.isDisabled,
            ]
                .filter(Boolean)
                .join(" ")}
            style={{
                ...(assignInlineVars({
                    [styles.hueVar]: `${props.renderProps.hsv.h}deg`,
                    [styles.thumbXVar]: `${props.renderProps.hsv.s}%`,
                    [styles.thumbYVar]: `${PERCENT - props.renderProps.hsv.v}%`,
                }) as CSSProperties),
                height: `${props.size}px`,
            }}
        >
            <div className={styles.colorAreaThumb} />
        </div>
    );
};

const HUE_THUMB_SIZE = 18;
const HUE_MAX = 360;

export const PageHueSlider = (props: HueSliderProps) => {
    const layerClass = useLayerClass();

    return (
        <div className={[styles.hueSlider, layerClass].join(" ")}>
            <div className={styles.hueTrack} />

            <div
                className={[styles.hueThumb, props.renderProps.focusVisibleThumb === 0 && styles.isFocused]
                    .filter(Boolean)
                    .join(" ")}
                style={{
                    ...(assignInlineVars({
                        [styles.swatchVar]: `hsl(${props.renderProps.values[0] % HUE_MAX} 100% 50%)`,
                    }) as CSSProperties),
                    left: `calc(${props.renderProps.ratios[0]} * (100% - ${HUE_THUMB_SIZE}px))`,
                }}
            />
        </div>
    );
};

export const PageColorSwatch = (props: ColorSwatchProps) => {
    const layerClass = useLayerClass();

    return (
        <div className={[styles.colorSwatchChecker, layerClass].join(" ")}>
            <div
                className={styles.colorSwatch}
                style={assignInlineVars({ [styles.swatchVar]: props.value }) as CSSProperties}
            />
        </div>
    );
};

export const PageColorChannelGrid = (props: PropsWithChildren) => {
    const layerClass = useLayerClass();

    return <div className={[styles.colorChannels, layerClass].join(" ")}>{props.children}</div>;
};

export const PageColorChannel = (props: PropsWithChildren<{ label: string }>) => {
    const layerClass = useLayerClass();

    return (
        <div className={[styles.colorChannel, layerClass].join(" ")}>
            <div className={styles.colorChannelLabel} aria-hidden="true">
                {props.label}
            </div>

            {props.children}
        </div>
    );
};

export const PageColorPickerPopup = (props: PropsWithChildren) => {
    const layerClass = useLayerClass();

    return <div className={[styles.colorPickerPopup, layerClass].join(" ")}>{props.children}</div>;
};

export const PageColorPickerRow = (props: PropsWithChildren) => {
    const layerClass = useLayerClass();

    return <div className={[styles.colorPickerRow, layerClass].join(" ")}>{props.children}</div>;
};

export const PageColorFieldTrigger = (props: PropsWithChildren<ColorFieldTriggerProps>) => {
    const layerClass = useLayerClass();

    return (
        <div
            className={[
                styles.colorFieldTrigger,
                layerClass,
                props.flags.isHovered && styles.isHovered,
                props.flags.isDisabled && styles.isDisabled,
            ]
                .filter(Boolean)
                .join(" ")}
        >
            {props.children}
        </div>
    );
};

export const PageColorPreview = (props: ColorSwatchProps) => {
    const layerClass = useLayerClass();

    return (
        <div className={[styles.colorPreviewChecker, layerClass].join(" ")}>
            <div
                className={styles.colorPreview}
                style={assignInlineVars({ [styles.swatchVar]: props.value }) as CSSProperties}
            />
        </div>
    );
};
