// playground-svelte/src/App/Pages/Menus/MenuPage/Examples/PlacedAbove.svelte
<script lang="ts">
    import { Menu } from "@thewaver/ss-components-svelte";

    import PageMenuTriggerContent from "../../../../StyledComponents/MenuTriggerContent/MenuTriggerContent.svelte";
    import { ACTIONS, renderMenuItem, renderMenuPopup } from "../MenuPage.const.svelte";
    import type { MenuExampleProps } from "../MenuPage.types";

    type Props = MenuExampleProps;

    let props: Props = $props();
</script>

<Menu
    items={ACTIONS}
    ariaLabel={"Edit actions"}
    placement={{ x: "left-in", y: "top-out" }}
    renderItem={renderMenuItem}
    renderPopup={renderMenuPopup}
    onActivate={props.onActivate}
>
    {#snippet renderContent(flags)}
        <PageMenuTriggerContent {flags}>Edit</PageMenuTriggerContent>
    {/snippet}
</Menu>

// playground/src/App/Pages/Menus/MenuPage/Examples/PlacedAbove.tsx
import { Menu } from "@thewaver/ss-components";

import { PageMenuTriggerContent } from "../../../../StyledComponents/MenuTriggerContent/MenuTriggerContent";
import { ACTIONS, renderMenuItem, renderMenuPopup } from "../MenuPage.const";
import type { MenuExampleProps } from "../MenuPage.types";

type Props = MenuExampleProps;

export const PlacedAboveExample = (props: Props) => (
    <Menu
        items={() => ACTIONS}
        ariaLabel={"Edit actions"}
        placement={() => ({ x: "left-in", y: "top-out" })}
        renderContent={(getFlags) => <PageMenuTriggerContent flags={getFlags}>Edit</PageMenuTriggerContent>}
        renderItem={renderMenuItem}
        renderPopup={renderMenuPopup}
        onActivate={props.onActivate}
    />
);
