// playground-react/src/App/Pages/TreePage/Examples/RecordValues.tsx
import { Tree } from "@thewaver/ss-components-react";

import { PageTreeNodeContent } from "../../../StyledComponents/TreeNodeContent/TreeNodeContent";
import { ASSETS } from "../TreePage.const";
import type { TreeRecordExampleProps } from "../TreePage.types";

type Props = TreeRecordExampleProps;

export const RecordValuesExample = (props: Props) => (
    <Tree
        nodes={ASSETS}
        value={props.value}
        expanded={props.expanded}
        ariaLabel={"Assets"}
        renderNode={(node, renderProps) => (
            <PageTreeNodeContent renderProps={renderProps} detail={node.value.kind}>
                {node.value.name}
            </PageTreeNodeContent>
        )}
    />
);

// playground-vue/src/App/Pages/TreePage/Examples/RecordValues.vue
<script setup lang="ts">
import { useModel } from "vue";

import { Tree } from "@thewaver/ss-components-vue";

import PageTreeNodeContent from "../../../StyledComponents/TreeNodeContent/PageTreeNodeContent.vue";
import { ASSETS } from "../TreePage.const";
import type { TreeRecordExampleProps } from "../TreePage.types";

type Props = TreeRecordExampleProps;

const props = defineProps<Props>();

const value = useModel(props, "value");
const expanded = useModel(props, "expanded");
</script>

<template>
    <Tree v-model:value="value" v-model:expanded="expanded" :nodes="ASSETS" ariaLabel="Assets">
        <template #renderNode="{ node, renderProps }">
            <PageTreeNodeContent :render-props="renderProps" :detail="node.value.kind">{{
                node.value.name
            }}</PageTreeNodeContent>
        </template>
    </Tree>
</template>
