// playground-react/src/App/Pages/ParticleFieldPage/Examples/Shaped.tsx
import { useCallback, useMemo, useRef } from "react";

import { ElementObserverReactUtils } from "@thewaver/ss-components-react";
import * as styles from "@thewaver/ss-playground/App/Pages/ParticleFieldPage/ParticleFieldPage.css";
import { ShapeConst, ShapeUtils, type Size2d } from "@thewaver/ss-utils";

import type { ParticleFieldExampleProps } from "../ParticleFieldPage.types";
import { DefaultExample } from "./Default";

const NO_EDGE_THICKNESSES = [0];

export const ShapedExample = ({
    shapeKind,
    joinRadius,
    ...otherProps
}: ParticleFieldExampleProps & { shapeKind: ShapeConst.DefaultShape; joinRadius: number }) => {
    const rootRef = useRef<HTMLDivElement>(null);

    const size = ElementObserverReactUtils.useBorderBoxSize(rootRef);

    const computeShapePoints = useCallback(
        (size: Size2d) => ShapeConst.getDefaultShapePoints(shapeKind, size),
        [shapeKind],
    );

    const shapeJoinRadii = useMemo(() => [joinRadius], [joinRadius]);

    const outlinePath = useMemo(
        () => ShapeUtils.getPaths(computeShapePoints(size), NO_EDGE_THICKNESSES, shapeJoinRadii).outerPath,
        [computeShapePoints, size, shapeJoinRadii],
    );

    return (
        <div ref={rootRef} className={styles.shapedRoot}>
            <svg className={styles.shapeOutline} aria-hidden="true">
                <path d={outlinePath} />
            </svg>

            <DefaultExample {...otherProps} computeShapePoints={computeShapePoints} shapeJoinRadii={shapeJoinRadii} />
        </div>
    );
};

// playground-svelte/src/App/Pages/ParticleFieldPage/Examples/Shaped.svelte
<script lang="ts">
    import { ElementObserverSvelteUtils } from "@thewaver/ss-components-svelte";
    import * as styles from "@thewaver/ss-playground/App/Pages/ParticleFieldPage/ParticleFieldPage.css";
    import { ShapeConst, ShapeUtils, type Size2d } from "@thewaver/ss-utils";

    import type { ParticleFieldExampleProps } from "../ParticleFieldPage.types";
    import DefaultExample from "./Default.svelte";

    const NO_EDGE_THICKNESSES = [0];

    let {
        shapeKind,
        joinRadius,
        playback = $bindable(),
        ...otherProps
    }: ParticleFieldExampleProps & { shapeKind: ShapeConst.DefaultShape; joinRadius: number } = $props();

    let root = $state<HTMLDivElement>();

    const getSize = ElementObserverSvelteUtils.createBorderBoxSizeObserver(() => root);

    const computeShapePoints = $derived((size: Size2d) => ShapeConst.getDefaultShapePoints(shapeKind, size));

    const shapeJoinRadii = $derived([joinRadius]);

    const outlinePath = $derived(
        ShapeUtils.getPaths(computeShapePoints(getSize()), NO_EDGE_THICKNESSES, shapeJoinRadii).outerPath,
    );
</script>

<div bind:this={root} class={styles.shapedRoot}>
    <svg class={styles.shapeOutline} aria-hidden="true">
        <path d={outlinePath} />
    </svg>

    <DefaultExample {...otherProps} bind:playback {computeShapePoints} {shapeJoinRadii} />
</div>
